### ISSUE TITLE
Adjustable font and text size

### ISSUE THREAD

**Issue by aluxian** [aluxian/Messenger-for-Desktop#100]

**Comment by iscrubscrubs** [comment]
Many people would like this feature added for larger screens and elders.

**Comment by RykarduSouza** [comment]
It was important to define the font size for the high-resolution screen.

**Comment by endquote** [comment]
+1 to this... would be nice to be able to command+ and command- to adjust sizing.

**Comment by Aluxian** [comment]
Have you tried those keyboard shortcuts? Please do and enjoy 😁



--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com
On Sat, Apr 30, 2016 at 7:29 PM, Josh Santangelo < notifications@github.com [notifications@github.com] > wrote:
+1 to this... would be nice to be able to command+ and command- to adjust sizing.

**Comment by endquote** [comment]
Yes... they don't work for me. OS X 10.11.4.

**Comment by Aluxian** [comment]
Oh... Sorry. I thought this was the repository for Whatsie. I've just realised it's the one for MFD 😑🙃

This should work in Whatsie. I am working on Messenger for Desktop 2, which will have this feature too (and many more). No ETA for now. Sorry again,  I'm very active working on Whatsie and when I got the email I didn't even look.

**Comment by endquote** [comment]
Cool! Yeah I started using Whatsie as well and like it. Nice work.

**Comment by anmcloughlin** [comment]
Seconding the request! This is important from an accessibility perspective.

**Comment by AmirRajabifar** [comment]
I'm using ubuntu 16.04 on Surface pro 4 and need a magnetic glass to see the text.

Microsoft has a fix to this issue and it's by scaling everything by %150.
Please add this feature

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
