### ISSUE TITLE
mac version installing trash

### ISSUE THREAD

**Issue by ttsda** [aluxian/Messenger-for-Desktop#1023]
when the mac dmg is clicked on the website an installer is downloaded which installs MacKeeper

**Comment by Sytten** [comment]
Pls see https://github.com/aluxian/Messenger-for-Desktop/issues/1153#issuecomment-283514347

**Comment by barbushin** [comment]
Everyone, please report Malware Abuse for https://messengerfordesktop.com on https://safebrowsing.google.com/safebrowsing/report_badware so Google will block it and remove from search results.

New web site URL is https://messengerfordesktop.org, and the old one installs malware!
