### ISSUE TITLE
Java Script error in main process when right click. Windo...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#1035]
**Description:**
Java Script error in main process when right click. Windows 10 Home 64, Kaspersky AV (paid).

**Steps to reproduce:**
Right click

**App version:**
2.0.1 beta

**OS:**
Windows 10 Home 64

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by cabban** [comment]
@Aluxian have the same annoying issue please fix
