### ISSUE TITLE
I think the links do not generate a preview when pasted t...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#1038]
**Description:**
I think the links do not generate a preview when pasted to the chat, like they do in the mobile version or the facebook chat. I don't know if a setting for that already exists and I missed it, but if it doesn't, it would be a very good feature to have

**Operating system:**
Windows

**Best thing about Whatsie:**
Performance, Ease of use, Design

**Worst thing about Whatsie:**
I just downloaded it, but so far I haven't found anything that bothers me. God job, guys!

**Extra:**
[Not answered]

**Comment by specious** [comment]
#353 is a duplicate.
