### ISSUE TITLE
Hi, not sure if this is a n issue experienced by anyone e...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#1039]
**Description:**
Hi, not sure if this is a n issue experienced by anyone else, but I'm not getting message notifications (Windows 10) whenever I receive a new message, even though I have enabled them at the notification center.

**Steps to reproduce:**
Not entirely sure about this, I simply open the app and notifications don't work.

**App version:**
2.0.1-beta

**OS:**
Windows 10, Version 1607

**Works in WhatsApp Web:**

**Extra:**
Not sure how this helps, but I also had another Messenger app installed, which would work fine but I didn't like the color combinations. If I would run Messenger for Desktop on its own, the notifications wouldn't work, as mentioned; but if I ran both Messenger apps, then I would indeed get notifications from Messenger for Desktop.

**Comment by Deuchnord** [comment]
Same issue here on Arch Linux, GNOME-Shell desktop.
