### ISSUE TITLE
CMD+M Minimizes. Doesn't follow standard Mac shortcut of CMD+W

### ISSUE THREAD

**Issue by voidstarfire** [Aluxian/Messenger-for-Desktop#1040]
OSX MacOS
2.02.

CMD+M Minimizes. Doesn't follow standard Mac shortcut of CMD+W

**Comment by Aluxian** [comment]
Can you give more info? I don't understand what's wrong. CMD+M and CMD+W wrong accordingly.

**Comment by voidstarfire** [comment]
Ahh yes, maybe I was on a previous version.
