### ISSUE TITLE
Update dialog forwards to potentially dangerous ads

### ISSUE THREAD

**Issue by stepjanssen** [aluxian/Messenger-for-Desktop#1041]
* Operating system:
Windows 8.1
* Messenger for Desktop version:
Unsure.

I clicked 'Ok' on the 'There's a new version' dialog, and got forwarded to this url (which was flagged by my firewall):
http://www.presentgiftcenter.com/exEgHZdhUox55iXe0hMppBGhQRjZoF2qa9s8RRAQBFHI4JlFhCqmnNoMlc4Vte8d_XxPj7Tno5_Pz+klytG3Af_oO_SjmzD3_ogUISJ5EcMQOHqG_CFKzYY9RCtMDim9aGolWQOavoRtcdGyiVI0K6UfRD7TGJwLiyGrc5760hxuy_DyujY=-GzwAAES3eX4Ket5aEZm0QeCQEz0gtAjSsGADTiTpYTyT7EmIAzmLqBEvzwLF5u1+Nr3+VW6aEQ==-e

**Comment by stepjanssen** [comment]
I investigated some more, the app opens the following URL:

https://updates.messengerfordesktop.com/download/mirror/installcore/latest?platform=win32

When I go to this URL it forwards to the previously mentioned URL. It seems like the site may have been compromised.

**Comment by jardicc** [comment]
I have same problem

**Comment by Sytten** [comment]
Im setting up a fork with a new clean site: https://messengerfordesktop.org/

**Comment by jardicc** [comment]
Does this contains bloatware as .com version?

**Comment by Sytten** [comment]
None that you cannot refuse, its still not entirely clean (we are working on cleaning them and releasing a fully clean version in two weeks).

**Comment by jardicc** [comment]
I already downloaded portable version from github... but it seem that I can't use this app without facebook account which is also bloatware :-D 
So it is useless for me.

**Comment by Sytten** [comment]
See https://github.com/aluxian/Messenger-for-Desktop/issues/1153#issuecomment-283514347
