### ISSUE TITLE
On high resolution screens it would be useful to have Tex...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#1050]
**Description:**
On high resolution screens it would be useful to have Text zoom option. The app has it, but only when using one chat window, when I go to another chat windows zoom goes back to smallest one. Please make zoom permament in all windows and after restart.

**Steps to reproduce:**
Just use zoom in FB messneger and go to another chat window

**App version:**
2.0.1 beta

**OS:**
Windows 10 64bit

**Works in WhatsApp Web:**

**Extra:**
No

**Comment by stomms** [comment]
It goes to smallest zoom position after changing a vhat window
