### ISSUE TITLE
While using the auto-hide sidebar feature, my chat goes o...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#1052]
**Description:**
While using the auto-hide sidebar feature, my chat goes outside the edge of the window by a large margin, and I am unable to read responses. When hovering over the left side the sidebar appears as intended, but the other person's messages remain outside the window.

**Steps to reproduce:**
Turn on auto-hide sidebar feature under the "View" menu.

**App version:**
2.01 Beta

**OS:**
Windows 10 (latest)

**Works in WhatsApp Web:**

**Extra:**
Great UI for this report site, clean and generally aesthetically pleasing. You have a great design team.

**Comment by hiiwave** [comment]
I'm able to reproduce this bug.
