### ISSUE TITLE
How about remove the DAMNED ads from the installer?

### ISSUE THREAD

**Issue by PhantomNeko** [aluxian/Messenger-for-Desktop#1091]
* Operating system: Microsoft Windows 8.1
* Messenger for Desktop version: None (Cancelled installation, because of adware in installer)
So, I wanted to use Messenger on a PC because Messenger takes up a lot of space on my phone, so I found this on the Internet and I wanted to install it. But after I saw the atrocious damned adware in the installer I very quickly clicked the "Cancel" button.
Just remove it. Please.

**Comment by Sytten** [comment]
See https://github.com/aluxian/Messenger-for-Desktop/issues/1153#issuecomment-283514347
