### ISSUE TITLE
The theme doesn't change

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#1098]
**Description:**
The theme doesn't change

**Steps to reproduce:**
1. Start Messenger
2. Log In
3. Go to Theme and select Mosaic 
4. Nothing changes

**App version:**
2.0.1-beta, downloaded ten minutes ago

**OS:**
Windows 10 Pro x64

**Works in WhatsApp Web:**

**Extra:**
No, nothing more as of now, but I'll make sure to suggest if I think of something :)

**Comment by stefanves** [comment]
Here's the original poster of that bug. 
The Messenger seems to have changed the Theme only after restarting the client, unlike in previous versions where it changed instantly.
