### ISSUE TITLE
Java type error when I press right mouse click.

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#1117]
**Description:**
Java type error when I press right mouse click.

**Steps to reproduce:**
Pressing right mouse click.

**App version:**
2.0.1-beta

**OS:**
Windows 7 32 bit

**Works in WhatsApp Web:**

**Extra:**
Great job, it makes my messaging easier!

**Comment by genchuba** [comment]
Cannot start messenger desktop as it returns the same JavaScript Error. 

![image](https://cloud.githubusercontent.com/assets/14154313/20734338/aa123b66-b6fd-11e6-9caa-83ce8f6a6db3.png)
