### ISSUE TITLE
Cannot drag n drop files

### ISSUE THREAD

**Issue by eKristensen** [aluxian/Messenger-for-Desktop#1123]
* Operating system: Windows 10 Enterprise, version 1607, OS Build 14393.447
* Messenger for Desktop version: 2.0.1-beta

I'm used to drag and dropping files to messenger, I can't do that in your app.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?

**Comment by eKristensen** [comment]
Its working fine now.
