### ISSUE TITLE
Clicking macOS desktop notifications crashes Messenger app

### ISSUE THREAD

**Issue by courtdemone** [aluxian/Messenger-for-Desktop#1124]
Whenever I click the desktop notification bubble that pops up when I get a message, the messenger app crashes. I've reported the crash data a few times. It also seems to be somewhat intermittent, but I haven't figured out what's different when it doesnn't crash.

* Operating system: macOS Sierra
* Messenger for Desktop version: 2.0.1-beta (2.0.1.26)

**Comment by Sytten** [comment]
Update to the latest version
