### ISSUE TITLE
Javascript error in the main process

### ISSUE THREAD

**Issue by mzso** [aluxian/Messenger-for-Desktop#1126]
Suddenly I get this and the app wouldn't work:
![main-processs](https://cloud.githubusercontent.com/assets/4479090/20789070/6f90d720-b7b3-11e6-9cb4-53ca72feb7bd.PNG)

Tried reinstalling 2.0.1, but I get the same thing. It just won't work anymore.

**Comment by JakesCode** [comment]
I'm getting the same error. Shame because, I have to use the older version which doesn't play video or audio files.

**Comment by Sytten** [comment]
We will continue the discussion here: https://github.com/aluxian/Messenger-for-Desktop/issues/1170
