### ISSUE TITLE
Cannot install from package repository

### ISSUE THREAD

**Issue by beruic** [aluxian/Messenger-for-Desktop#1133]
* Operating system: Ubuntu 16.05
* Messenger for Desktop version: Newest

Following the instructions to add repository, the package `messengerfordesktop` does not become available.

**Comment by aluxian** [comment]
I think it's because you chose stable or dev while only beta was available then. Now stable should work and soon there will be a dev release too.

**Comment by cmr624** [comment]
Any fix for this? Same issue...
