### ISSUE TITLE
Windows Installation Failed

### ISSUE THREAD

**Issue by zerolfc** [Aluxian/Messenger-for-Desktop#1134]
My anti virus detected Trojan Virus when installing? 
and server failed to download the software.
![capture](https://cloud.githubusercontent.com/assets/5167436/20919060/dc55d450-bb91-11e6-8719-c3234f1138f0.PNG)

**Comment by GEp1c** [comment]
Download it from here:
https://github.com/Aluxian/Messenger-for-Desktop/releases/tag/v2.0.1
