### ISSUE TITLE
Is the project dead or are there any updates coming up?

### ISSUE THREAD

**Issue by xbeyond1** [Aluxian/Messenger-for-Desktop#1136]

**Comment by kingmustard** [comment]
I'm wondering the same thing.

**Comment by xbeyond1** [comment]
I really hope it's not. Loving it so far.

**Comment by DroWnThePoor** [comment]
Wondering which version you guys are using? I can't really tell which I have currently installed.I'm fairly sure I installed from a deb on the messengerfordesktop.com,but for a while now there's been  a javascript prompt at startup offering an upgrade to 2.0.2, it never seemed to work until just now, but the deb it downloads is "Messenger_linux64_V150_beta1.deb", and then the latest beta on here is 2.0.1. So I'm very confused. Can any of you advise? 

And yes, I truly hope this app isn't dead, this is GREAT work, I know it's a web app built on Chromium engine, but it's still extremely functional. Before this I was using Pidgin, which also works great, but this definitely has more features.

**Comment by randalvance** [comment]
Download the latest release from here:
https://github.com/Aluxian/Messenger-for-Desktop/releases

**Comment by raptormama** [comment]
That's not the latest release. I have 2.0.1 but I keep getting told that 2.0.2 is available via an auto update check. I want 2.0.2 without any forced crapware installs, especially from Yahoo... which not only lost hundreds of millions of accounts before I got confronted with a Messenger installer peddling an unavoidable Yahoo crapware "bonus" but now has lost an extra billion. So crapware is a dealbreaker.

**Comment by timofonic** [comment]
I agree, this sucks. Someone with dev skills should fork it.

Any hopes to have videochat without need to open a new browser window?

**Comment by kingmustard** [comment]
The program was updated, albeit only slightly, 6 days ago.

**Comment by Aluxian** [comment]
I'm releasing 2.0.5 soon
