### ISSUE TITLE
Yahoo Search adware on Windows: Please remove it or make it optional

### ISSUE THREAD

**Issue by timofonic** [aluxian/Messenger-for-Desktop#1137]
Hello.

I'm very upset, because you try to force install of Yahoo Search adware. This make me very suspicious about the project.

Are you going to make it optional? Here on Windows 10 it tries to force the install.

Please modify the installers from all versions, this is a very evil practice. It's okay you try to get revenues, but not THIS WAY similar to Softonic and other adware places. Computers have enough crap with Microsoft, thanks.

Kind regards.

**Comment by BenjaVR** [comment]
Are you sure you have unchecked the box in the installer?

**Comment by raptormama** [comment]
The last time I tried the 2.0.2 installer, I couldn't see a way to do that. I've stuck on 2.0.1 ever since. It's incredibly bad form to try to force us to use software from a company that is so blind to security that it has lost the credentials to over a billion accounts.

**Comment by lesmo** [comment]
This is going to bring serious bad mojo to the project. This shouldn't be EVEN OPTIONAL. I agree that developers should get some sort of compensation for useful open-sourced and free (as in beer) software, and one of those means is donations... however, no mention of it is made in README or the website; it should the be the very first shot at getting some compensation, and then maybe consider doing some weird deals with Yahoo or whatever.

On Mac, it's also installing MacKeeper. What the F is that?

**Comment by Sytten** [comment]
Please see https://github.com/aluxian/Messenger-for-Desktop/issues/1153#issuecomment-283514347

**Comment by barbushin** [comment]
Everyone, please report Malware Abuse for https://messengerfordesktop.com on https://safebrowsing.google.com/safebrowsing/report_badware so Google will block it and remove from search results.

New web site URL is https://messengerfordesktop.org, and the old one installs malware!
