### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by hariom877** [aluxian/Messenger-for-Desktop#1138]
* Operating system:8.1`
* Messenger for Desktop version:2.0.1

JavaScript error occurred in the main process while opening messenger for desktop

![Uploading Screenshot (67).png…]()

**Comment by GEp1c** [comment]
Download it from here: 

https://github.com/Aluxian/Messenger-for-Desktop/releases/tag/v2.0.1

**Comment by Sytten** [comment]
cant see the screen shot, but I assume its the same as https://github.com/aluxian/Messenger-for-Desktop/issues/1170
