### ISSUE TITLE
25% CPU Usage on process 'exe'

### ISSUE THREAD

**Issue by domhauton** [aluxian/Messenger-for-Desktop#1140]
* Operating system: Ubuntu 16.04 LTS
* Messenger for Desktop version: 2.0.1-beta

messengerfordes─┬─Messenger───Messenger─┬─{AudioOutputDevi}
                │                       ├─{Chrome_ChildIOT}
                │                       ├─4*[{CompositorTileW}]
                │                       ├─{Compositor}
                │                       ├─{FFmpegDemuxer}
                │                       ├─{HTMLParserThrea}
                │                       ├─{Media}
                │                       ├─4*[{Messenger}]
                │                       ├─{ScriptStreamerT}
                │                       ├─{WorkerPool/2257}
                │                       ├─{WorkerPool/2393}
                │                       ├─2*[{WorkerPool/2480}]
                │                       └─{handle-watcher-}
                ├─exe─┬─{Chrome_ChildIOT}
                │     ├─{SGI_video_sync}
                │     ├─{Watchdog}
                │     └─{handle-watcher-}
                ├─{AudioThread}
                ├─3*[{BrowserBlocking}]
                ├─{BrowserWatchdog}
                ├─5*[{CachePoolWorker}]
                ├─{Chrome_CacheThr}
                ├─{Chrome_DBThread}
                ├─{Chrome_FileThre}
                ├─{Chrome_FileUser}
                ├─{Chrome_HistoryT}
                ├─{Chrome_IOThread}
                ├─{Chrome_ProcessL}
                ├─{CompositorTileW}
                ├─{CrShutdownDetec}
                ├─{D-Bus thread}
                ├─{IndexedDB}
                ├─{NetworkChangeNo}
                ├─{dconf worker}
                ├─{extension_crash}
                ├─{gdbus}
                ├─{gmain}
                ├─{gpu-process_cra}
                ├─{handle-watcher-}
                ├─{inotify_reader}
                ├─{sandbox_ipc_thr}
                └─{threaded-ml}

**Comment by Sytten** [comment]
The V2.0.4 seems fine to me.
