### ISSUE TITLE
Seen and Typing on v2 and above

### ISSUE THREAD

**Issue by KTsarlz** [Aluxian/Messenger-for-Desktop#1152]
* Operating system: Win 7
* Messenger for Desktop version: Latest stable

This is a feature request, is it possible to add the disable seen and typing unto the v2 and above beta's? I think it wouldn't hurt that much that would make the app unstable as it is a minor feature.

**Comment by Aluxian** [comment]
Added in 2.0.5, will be released soon

**Comment by KTsarlz** [comment]
Thanks man! Been waiting for this :)
