### ISSUE TITLE
alt+0 (to do "@") it changes the theme

### ISSUE THREAD

**Issue by aluxian** [aluxian/Messenger-for-Desktop#1156]
* Operating system:
* Messenger for Desktop version:

when i alt+0 (to do "@") it changes my theme, so I have to change it again by doing alt+3 ('#')
I know it's not much but it's really annoying since i often write "@" for emails and stuff

**Comment by jkuchar** [comment]
👍 Very annoying. (Windows 10)

**Comment by aluxian** [comment]
Fixed in 2.0.7 (will be released soon)
