### ISSUE TITLE
Video and Audio calls not working

### ISSUE THREAD

**Issue by vanushwashere** [Aluxian/Messenger-for-Desktop#1157]
* Operating system: Windows 10 x64 
* Messenger for Desktop version: 2.0.4-beta

When disabled "Open link in Browser" option clicking on the one of both call buttons opens new blank window and nothing happens.
With enabled "Open link in Browser" option, clicking on call buttons opens Windows "Open With" dialogue 
![image](https://cloud.githubusercontent.com/assets/24995381/21754373/1d104840-d618-11e6-855d-b836c62f9c75.png)

Answering on Incoming Calls also works with that logic.

**Comment by KamiOh** [comment]
i have same problem.
Win10 Enterprise 2016 LTSB x64

![messenger desktop error](https://cloud.githubusercontent.com/assets/13822730/21792402/7ddb5346-d6b7-11e6-945e-1f5f4a92479f.jpg)

**Comment by eqagunn** [comment]
Same problem here. Windows 10 Education 64-bit.
Messenger for Desktop 2.0.4-beta

I'd like to note this problem is present since I reinstalled my OS.
It was working fine before on the same version of Messenger for Desktop on W10 Enterprise 64-bit.

**Comment by Aluxian** [comment]
Fixed in 2.0.5, will be released soon

**Comment by vanushwashere** [comment]
Thanks, waiting for update 👍
