### ISSUE TITLE
Is there a way to permamently hide menu bar?

### ISSUE THREAD

**Issue by mosley93** [aluxian/Messenger-for-Desktop#1158]
After I configured options I don't need it anymore and it looks bad when I'm using dark theme. Also I'm using MfD on my Windows 10 tablet and I want to achieve full-screen only messenger look. When I'm toggling full screen app remembers about it when I open it another time, but when I'm disabling menu bar it appears again every time I start Messenger.
* Operating system: Windows 10 Home
* Messenger for Desktop version: 2.0.4

**Comment by aluxian** [comment]
Yes, Fixed in 2.0.7 (will be released soon)
