### ISSUE TITLE
Default Zoom Level 

### ISSUE THREAD

**Issue by nemysis** [aluxian/Messenger-for-Desktop#1161]
* Operating system: openSUSE
* Messenger for Desktop version: v2.0.4-beta

Please add Default Zoom Level to Menu.

Example: 50, 55,60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115 and so on to 250

**Comment by aluxian** [comment]
These can be changed with zoom in/out menus + kb shortcuts.
