### ISSUE TITLE
Application *requires* high performance graphics mode

### ISSUE THREAD

**Issue by kmishra9** [Aluxian/Messenger-for-Desktop#1163]
* Operating system: MacOS Sierra, Version 10.12.2 (16C67)
* Messenger for Desktop version: Version 2.0.4-beta (2.0.4.35)

On Macs with a discrete graphics card, automated graphics switching is implemented by the OS. Unfortunately, keeping Messenger for Desktop open forces the OS to use the high performance graphics card for everything instead of using the more power efficient Integrated graphics mode.  Battery life and heat are significantly worse when the app is open, making it thus... much more difficult to justify using.

![image](https://cloud.githubusercontent.com/assets/10662252/21958601/9f4dc10a-da66-11e6-9755-f80e02376c80.png)

![image](https://cloud.githubusercontent.com/assets/10662252/21958629/79cb4ae6-da67-11e6-8df9-05c7c6021b58.png)

(ignore barely decreased battery life estimate, trust me, having the discrete graphics card on sucks battery when other applications that integrated can handle easily, such as watching video or rendering chrome pages, takes 50 watts to do instead of 10)

**Comment by Sytten** [comment]
https://github.com/Aluxian/Messenger-for-Desktop/issues/1172

**Comment by Aluxian** [comment]
Fixed in next update
