### ISSUE TITLE
Build for Win32 produces bad exe

### ISSUE THREAD

**Issue by nistath** [Aluxian/Messenger-for-Desktop#1164]
* Operating system: Windows 8.1 x64
* Messenger for Desktop version: master branch as of 15/1/2017

I built the app for win32 after changing a few lines of code. It produced an .exe which gives the following message once launched: ![image](http://i.imgur.com/5WKB5yS.png)

I tried cloning again and built a clean version as found on GitHub. Same error.

The dependencies are installed when I build, I don't get why spellchecker is not found.

**Comment by Aluxian** [comment]
Have you tried to rebuild the node modules? https://github.com/Aluxian/Messenger-for-Desktop#native-modules
