### ISSUE TITLE
Takes ages to load on macOS

### ISSUE THREAD

**Issue by pkuczynski** [aluxian/Messenger-for-Desktop#1167]
* Operating system: macOS Sierra (OSX)
* Messenger for Desktop version: 2.0.4

It takes ages to load. The app is white for 2-3 minutes before it finish loading content.

**Comment by Sytten** [comment]
Some times a force reload or quit/restart helps.
Consider that its a browser under it with a full nodejs from what I remember so its heavy for sure...

**Comment by zomars** [comment]
In my case it's just a blank screen, and I if close it macOS takes it as a crash and pops up the crash reporter.

**Comment by aluxian** [comment]
Please update to 2.0.9 and reopen the issue if this is still a problem.

If it's still a problem: does messenger.com work normally in your Chrome/Chromium browser?

**Comment by zomars** [comment]
This is still a problem in 2.0.6, in chrome it works fine.
