### ISSUE TITLE
Not Found in Apt after following Steps.

### ISSUE THREAD

**Issue by benyanke** [aluxian/Messenger-for-Desktop#1171]
* Operating system: Ubuntu 16.04.1 LTS
* Messenger for Desktop version: Current

I followed the steps of adding the GPG key, then adding the apt sources, then apt update, and still, I get:

``` bash
user@hostname:/etc/apt/sources.list.d$ sudo apt-get install messengerfordesktop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package messengerfordesktop
```

Ideas?

**Comment by Sytten** [comment]
Duplicate https://github.com/aluxian/Messenger-for-Desktop/issues/1133
