### ISSUE TITLE
Use `--disable-gpu` to force using the intergrated GPU on MAC

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Messenger-for-Desktop#1172]
> As a suggestion to improve power efficiency and CPU/GPU usage on iMacs, Mac Pro’s, and MacBook Pro’s with discrete graphics cards, would it be possible to disable the app requiring the “High Performance GPU” mode? I noticed this behavior when the Messenger for Desktop app on my MacBook Pro was consuming an unusually large amount of power as well as keeping the High Perf. GPU activated, which is far less power efficient than the Integrated Graphics chip. 
> 
> MacOS programs can specify which graphics mode they’d like to be in and using the discrete graphics cards on computers is only really necessary for graphics intensive programs like games, Photoshop, and Final Cut Pro. 
> 
> Should be a relatively simple fix and improve the end user experience for quite a few Mac users!

Electron has `--disable-gpu`

https://github.com/electron/electron/issues/4380

**Comment by Sytten** [comment]
I also observed this behavior.
For now the quick fix is to lock it to the integrated gpu (can be done easily with gfxCardStatus).
I now have a mac too @Aluxian :)
