### ISSUE TITLE
[Feature request/Issue] Messenger requires external browser to download files

### ISSUE THREAD

**Issue by Unc3nZureD** [Aluxian/Messenger-for-Desktop#1173]
Actually it's somewhere between an issue and a feature request :)

So, when someone sends me a file, the app requires me to open an external browser to download the file. It would be amazing if I could download it within the messenger app.

**Comment by Sytten** [comment]
The problem is its difficult to differentiate a normal URL from a download URL...
You can download it directly in the app if you uncheck the setting that says to open links in the browser ;)

**Comment by Unc3nZureD** [comment]
Sure, it would be hard to generally detect directly downloadable things, but at the moment I mean _(probably forgot to specificate, sorry)_ the facebook-exclusive download links. For example I can upload a file, which looks like this:
http://i.imgur.com/1HXjZNO.png

It could be detected, because these links have a special format :)

**Comment by Sytten** [comment]
I agree that could be a simple regex. It could only be for links on the facebook domains as a start and maybe expand it after. 
It could include also my request to open video calls inside the app since its also on a facebook domain.

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Messenger-for-Desktop/commit/0ae86f7c35da9ec43a04d6e53fd1a29c87d101d2
