### ISSUE TITLE
Make exception in open URL in browser for facebook calls

### ISSUE THREAD

**Issue by Sytten** [Aluxian/Messenger-for-Desktop#1174]
* Operating system: OSX
* Messenger for Desktop version: 2.04

I wrote that exception in the 1.5.0, but its missing in the V2.
Should be pretty easy to do.

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Messenger-for-Desktop/commit/0e5f73ac6d8ca49a8b6406ebc47979dfa38e305a
