### ISSUE TITLE
To Disable Smooth-Scrolling: use "--disable-smooth-scrolling"

### ISSUE THREAD

**Issue by AncientRepositoryOfKnowledge** [Aluxian/Messenger-for-Desktop#1175]
Since Messenger for Desktop uses Chromium, you can start the main binary with flags. In this case, to disable smooth scrolling use the argument "--disable-smooth-scrolling".

**Comment by Aluxian** [comment]
The question is, why? What does this fix/improve?

**Comment by AncientRepositoryOfKnowledge** [comment]
Just to improve the user experience - since it's turned on by default (Chromium default flags), I thought I'd post it in case someone wants to know how to turn smooth scrolling off :)

**Comment by Aluxian** [comment]
So on Linux, at least for you, disabling smooth scrolling provides a better experience in the app?

**Comment by AncientRepositoryOfKnowledge** [comment]
I'm on Windows, but yeah it's far more easier for me to use lol

**Comment by Aluxian** [comment]
I'm sorry, you're the first to complain about this and I'd rather keep the Chromium default.

**Comment by AncientRepositoryOfKnowledge** [comment]
Oh well, at least it's there for people if they want to change it lol.
