### ISSUE TITLE
Change window title on new message

### ISSUE THREAD

**Issue by froxCZ** [Aluxian/Messenger-for-Desktop#1176]
* Operating system: ubuntu 16
* Messenger for Desktop version: 2.0.3 - beta

I just installed messenger for desktop via dpkg and the messenger window does not indicate whether I ahve some new unread messages.
Prior to installing messenger via dpkg I used downloaded .deb package, which changed title depending on new message.

**Comment by Aluxian** [comment]
Fixed in 2.0.5, will be released soon
