### ISSUE TITLE
bad macOS download on messengerfordesktop.com

### ISSUE THREAD

**Issue by rtharston** [aluxian/Messenger-for-Desktop#1179]
I found this app at messengerfordesktop.com for Linux and thought it was great so I went to download it on my wife's MacBook from the same website and the download for macOS was a spammy looking installer that I didn't feel like running to see what it would do. The download was just over one MB and the installer wasn't an official macOS installer. It threatened to make Yahoo my default search engine and home page, and wanted to install some other junk as well.

I thought that was all really weird since the Linux version downloaded just fine so I came snooping around here on GitHub and found that the macOS download from here was just the app itself with no installer, which was exactly what I was expecting.

So, I'm not sure who is in charge of that site and if they'll even see this, but I am thinking something is wrong with the download link on that site for the Mac version of the app, maybe even for the Windows version as well, I'm not sure.

**Comment by Sytten** [comment]
Yes it is known. The author sold the domain name and its now serving malware.
If you want clean installer you can go in the release part.
I'm setting a new domain with clean installers.

**Comment by Sytten** [comment]
messengerfordesktop.org is now online!

**Comment by Sytten** [comment]
please see https://github.com/aluxian/Messenger-for-Desktop/issues/1153#issuecomment-283514347
