### ISSUE TITLE
No video or voice calls possible

### ISSUE THREAD

**Issue by michaldybczak** [Aluxian/Messenger-for-Desktop#1181]
* Operating system: Manjaro KDE 16.10 Fringilla, Kernel, x86_64 Linux 4.9.9-1-MANJARO, KDE 5.31.0 / Plasma 5.9.2
* Messenger for Desktop version: 2.0.4-1 from AUR

In the past calls and video connections were possible. Now when I click on call, I see pop-up window: Error - KIOExec, Missing file: about:blank.

Here is screen of that window:

https://puu.sh/ua5re/844d713fed.png

Other then that, application seems to work fine, maybe except the fact that it global menu on Plasma shows but is not clickable on the panel.

**Comment by Aluxian** [comment]
Fixed in 2.0.5, will be released soon

**Comment by michaldybczak** [comment]
Thanks, will wait for the update.
