### ISSUE TITLE
Command-comma doesn't open preferences on OS X

### ISSUE THREAD

**Issue by specious** [aluxian/Messenger-for-Desktop#1187]
It is almost a universal convention for *Preferences* to be listed under the main menu, and <kbd>⌘</kbd> + <kbd>,</kbd> is the conventional shortcut.  For example, in [iTerm2](https://github.com/gnachman/iTerm2):

![preferences-osx](https://cloud.githubusercontent.com/assets/451178/23345068/cb8e818a-fc55-11e6-8d35-8c477103b7ed.png)

* Operating system: OS X 10.12.2
* Messenger for Desktop version: 2.0.4-beta (2.0.4.35)

**Comment by aluxian** [comment]
And what would happen when you clicked Preferences?

**Comment by aluxian** [comment]
Closing this until there's more info. I'm not against it, I just need to understand it.

**Comment by specious** [comment]
Same as clicking the gear and then choosing "Settings".

![settings](https://cloud.githubusercontent.com/assets/451178/23932629/a837a916-090f-11e7-8ad2-142ff541decb.png)

**Comment by aluxian** [comment]
Done in 2.0.7 (will be released soon)
