### ISSUE TITLE
Cannot close the app if dock disabled

### ISSUE THREAD

**Issue by Sytten** [aluxian/Messenger-for-Desktop#1190]
* Operating system: Mac osx
* Messenger for Desktop version: 2.0.4-beta

If you enable the menu bar and disable the dock you won't be able to close the app (with the X or ESC).
Also it would be nice to still have the other menus when the app is selected (like the view, theme, window, etc.)
EDIT: the X actually puts the app in the background instead for some reason.

**Comment by aluxian** [comment]
Hah indeed. Switch menu bar on, dock off, can't press X.

**Comment by aluxian** [comment]
Fixed in 2.0.7 (will be released soon)
