### ISSUE TITLE
Messenger error at startup - loading page

### ISSUE THREAD

**Issue by Zorakie** [aluxian/Messenger-for-Desktop#1193]
* Operating system: WINDOWS 10
* Messenger for Desktop version: 2.0.1
Messenger will not start, will not load the page (issue started today (maybe FB changed something?).

Reinstall didnt help.

![obrazek](https://cloud.githubusercontent.com/assets/14437576/23519806/8c52ab7e-ff78-11e6-9695-a3304ed69c10.png)

**Comment by aluxian** [comment]
Try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

**Comment by Zorakie** [comment]
Hi, sadly, even new version is not working. This time, every start, it throws slightly diffeerent error:

![obrazek](https://cloud.githubusercontent.com/assets/14437576/23525504/00df5ab2-ff8f-11e6-9600-2e9eb688d089.png)

**Comment by aluxian** [comment]
I think I know what the problem is, I'll try to fix it in the next update.

**Comment by Sytten** [comment]
Yea multiple people have that problem
https://github.com/aluxian/Messenger-for-Desktop/issues/1170
