### ISSUE TITLE
Support Retina display assets on OS X

### ISSUE THREAD

**Issue by LucasTizma** [Aluxian/Messenger-for-Desktop#12]
Currently, the icons in the app are not using Retina display assets:

![screen shot 2015-04-11 at 4 17 21 pm](https://cloud.githubusercontent.com/assets/66559/7103659/4c3748c0-e066-11e4-806a-b9deeea32216.png)

[messenger.com](messenger.com) has them. Any way to fix this?

**Comment by Aluxian** [comment]
I don't know whether there's a way to fix this. Someone else also reported that the app didn't use retina assets for them. For me, it looks as good as messenger.com (I zoomed in).

**Comment by dstaley** [comment]
FWIW, seeing low-res assets on Windows as well.
![image](https://cloud.githubusercontent.com/assets/88163/7184627/fd5bd786-e423-11e4-9768-846b291cd887.png)

**Comment by LucasTizma** [comment]
I've noticed that the behavior is inconsistent. Sometimes, if I switch resolutions on my MacBook Pro from Scaled to full-resolution, it won't refresh the icons. If I close and reopen the app, it'll display the icons at Retina resolution.

**Comment by dstaley** [comment]
Yup, noticing the same thing here too. Launched it today and I have nice, hires iconography.
![image](https://cloud.githubusercontent.com/assets/88163/7203745/827c5e68-e4e2-11e4-8f7b-6604cac655b2.png)

**Comment by mcescalante** [comment]
Quitting the app and re-opening fixes it, it might take 2 times. This is behavior from Facebook's messenger app actually - it decides whether to serve a retina or non-retina asset at loadtime. There is [a very similar discussion](https://github.com/rsms/fb-mac-messenger/issues/45) in another fbchat wrapper issue tracker which highlights it. 

Reloading the app should usually serve the proper images the second time around, but I noticed that when I reload this app, it's not changing any assets. Maybe adding something to "reserve" assets when reloaded would mitigate having to actually exit.
