### ISSUE TITLE
[improvement] Remember zoom

### ISSUE THREAD

**Issue by Zorakie** [aluxian/Messenger-for-Desktop#1207]
* Operating system: WIN10
* Messenger for Desktop version: 2.0.5

Now, the zoom resets just on change of someone who you want to talk to.
So if you chat with more people, you have to adjust zoom everytime you swap between that people.

But I would like to push that one step further.
The zoom should be app-global, that is clear.
But best thing would be, if the zoom level could be saved (app should automatically remember the zoom level in some config and upon app start, load that value and set the zoom.

**Comment by aluxian** [comment]
That's how it is *supposed* to work... tracked here: https://github.com/aluxian/Messenger-for-Desktop/issues/790
