### ISSUE TITLE
Messenger won't load at PC startup

### ISSUE THREAD

**Issue by Zorakie** [aluxian/Messenger-for-Desktop#1209]
* Operating system: WIN 10
* Messenger for Desktop version: 2.0.5

Messenger will not load at PC startup.
Every time I have to do the Window/Reload 
![obrazek](https://cloud.githubusercontent.com/assets/14437576/23751544/2b747ddc-04d2-11e7-9cf2-23947a669f1b.png)

**Comment by aluxian** [comment]
Similar to this, tracked there: https://github.com/aluxian/Messenger-for-Desktop/issues/1192
