### ISSUE TITLE
[Improvement] Restore number of notifications / badge on startup

### ISSUE THREAD

**Issue by Zorakie** [aluxian/Messenger-for-Desktop#1210]
* Operating system: WIN 10
* Messenger for Desktop version: 2.0.5

When you got new message, tray icon blinks and a number is also shown on taskbar.

But when you start messenger and you have some messages, it is not shown, so now you have to open the window and check manually by bold text at person name...

![obrazek](https://cloud.githubusercontent.com/assets/14437576/23752119/595639aa-04d4-11e7-95d7-f648caa66cca.png)

**Comment by aluxian** [comment]
1. The badge is designed to signal new notifications, like Messenger.com does by flicking its tab's/window's title. I think this behaviour is more appropriate and I won't change it unless more people request an alternative.
2. No app icon tracked here: https://github.com/aluxian/Messenger-for-Desktop/issues/1206
