### ISSUE TITLE
Hide right panel pushes content behind the window edge

### ISSUE THREAD

**Issue by Zorakie** [aluxian/Messenger-for-Desktop#1211]
* Operating system: WIN 10
* Messenger for Desktop version: 2.0.5

When you hide left panel, the middle conversation windows runs behind the edge, so you cannot see part of conversation bubbles and the hover area for re-show the right panel is also somewhere behind the edge

![obrazek](https://cloud.githubusercontent.com/assets/14437576/23752724/d1c17e52-04d6-11e7-8b1e-41a5ef99ad11.png)

**Comment by aluxian** [comment]
Thanks, tracked here: https://github.com/aluxian/Messenger-for-Desktop/issues/1211
