### ISSUE TITLE
Text color is too dark for unread messages in midnight theme

### ISSUE THREAD

**Issue by tjiang11** [aluxian/Messenger-for-Desktop#1214]
* Operating system: Ubuntu
* Messenger for Desktop version: Version 2.0.4-beta

Text for unread messages in the sidebar is too dark when using midnight theme. Can it be changed to be white or a lighter color?

![image](https://cloud.githubusercontent.com/assets/11807091/23819743/79c0a0d6-05d8-11e7-9227-d549ca408048.png)

**Comment by aluxian** [comment]
Fixed in 2.0.7 (will be released soon)
