### ISSUE TITLE
Icon is missing

### ISSUE THREAD

**Issue by Ligerx** [aluxian/Messenger-for-Desktop#1219]
* Operating system: Windows 10
* Messenger for Desktop version: 2.0.6

I upgraded to 2.0.6 and the icon in my taskbar is missing. I tried reinstalling and it's still missing.

![missing-icon](https://cloud.githubusercontent.com/assets/6577974/23879900/76c19aca-0826-11e7-9116-68c6ed6a107f.PNG)

**Comment by aluxian** [comment]
Can you try to unpin it and then pin it again?

**Comment by aluxian** [comment]
If you uninstall 2.0.6 and then install 2.0.4 (https://github.com/aluxian/Messenger-for-Desktop/releases/tag/v2.0.4), does the icon come back?

**Comment by aluxian** [comment]
Duplicate, will be tracked here: https://github.com/aluxian/Messenger-for-Desktop/issues/1206
