### ISSUE TITLE
Missing desktop file after upgrade

### ISSUE THREAD

**Issue by logileifs** [aluxian/Messenger-for-Desktop#1223]
* Operating system: Linux Ubuntu 14.04 x86_64
* Messenger for Desktop version: 2.0.6

I used to be able to launch messenger for desktop with my launcher simply by typing 'messenger' but after upgrade it doesn't work anymore and the only way to launch is from terminal.

**Comment by aluxian** [comment]
Have you identified which .desktop file is missing?

**Comment by logileifs** [comment]
@aluxian No way of knowing for me since it doesn't exist anymore. If you can tell me how I can install an older version of messenger I could see what file was being used in the earlier version

**Comment by aluxian** [comment]
you can get older versions here: https://github.com/aluxian/Messenger-for-Desktop/releases

Or if you use apt, you can search for a package's versions (can't remember the command though)

**Comment by logileifs** [comment]
in the 2.0.4 version it's there.
`cat /usr/share/applications/messengerfordesktop.desktop`
```[Desktop Entry]
Name=Messenger for Desktop
Comment=A simple &amp; beautiful desktop client for Facebook Messenger.
GenericName=Internet Messenger
Exec=/opt/messengerfordesktop/messengerfordesktop %U
Icon=messengerfordesktop
Terminal=false
Type=Application
StartupNotify=true
StartupWMClass=messengerfordesktop
Keywords=Facebook;Messenger;chat;desktop;
Categories=Network;InstantMessaging;
X-GNOME-UsesNotifications=true```

**Comment by aluxian** [comment]
That's weird, I can't reproduce it. Does `apt-get install` (or dpkg) show any errors? Maybe some permissions are wrong, somewhere?

Does it work if you install the latest version and then manually replace the .desktop file? This is the most up-to-date version:

```
Name=Messenger for Desktop
Comment=A simple &amp; beautiful desktop client for Facebook Messenger.
GenericName=Internet Messenger
Exec=/opt/messengerfordesktop/messengerfordesktop %U
Icon=messengerfordesktop
Terminal=false
Type=Application
StartupNotify=true
StartupWMClass=Messenger for Desktop
Keywords=Facebook;Messenger;chat;desktop;
Categories=Network;InstantMessaging;
X-GNOME-UsesNotifications=true
```

**Comment by logileifs** [comment]
okay after doing a clean installation of the 2.0.6 version it's working now, I'm not sure what was wrong, maybe something went wrong with the update but it's working now so I will close this issue :)
