### ISSUE TITLE
Why doesn't the spellchecker have Hungarian?

### ISSUE THREAD

**Issue by mzso** [aluxian/Messenger-for-Desktop#1230]
Doesn't it come from chromium? Chrome comes in Hungarian.
I see other uncommon languages (some less populous even) such as Slovak, Serbian, Romanian. There are a dozen form of spanish and english variants...

**Comment by aluxian** [comment]
What's your operating system?

**Comment by aluxian** [comment]
Hungarian added in next release

**Comment by mzso** [comment]
[**@aluxian**](https://github.com/aluxian) commented on [Mar 23, 2017, 12:41 PM GMT+1](https://github.com/aluxian/Messenger-for-Desktop/issues/1230#issuecomment-288693060 "2017-03-23T11:41:43Z - Replied by Github Reply Comments"):
> What's your operating system?

Windows 8.1

[**@aluxian**](https://github.com/aluxian) commented on [Mar 23, 2017, 12:44 PM GMT+1](https://github.com/aluxian/Messenger-for-Desktop/issues/1230#issuecomment-288693570 "2017-03-23T11:44:19Z - Replied by Github Reply Comments"):
> Hungarian added in next release

Great!

**Comment by mzso** [comment]
So I selected hungarian, but it doesn't seem to work. It never underlines anything, and there are no suggestions.
