### ISSUE TITLE
Remove the useless option

### ISSUE THREAD

**Issue by bandithedoge** [aluxian/Messenger-for-Desktop#1242]
* Operating system: Windows 10 64-bit
* Messenger for Desktop version: 2.0.8-beta

Hey! I found a useless option:
![messenger for desktop_2017-03-25_09-22-45](https://cloud.githubusercontent.com/assets/26331682/24320791/b2af1cc8-113c-11e7-8d33-74be5e45cf0c.png)
App>Settings

You can also acces this menu by clicking here:
![messenger for desktop_2017-03-25_09-24-59](https://cloud.githubusercontent.com/assets/26331682/24320802/f74a19be-113c-11e7-88ad-ec703d0a7bb0.png)
(I'm sorry for the language, "ustawienia" stands for "settings" in Polish)
I don't know why it's in the "App" dropdown menu. Please remove this.

**Comment by aluxian** [comment]
It's there so people can use the keyboard shortcut to open it. I won't remove it, but thanks for the suggestion.
