### ISSUE TITLE
[improvement] Remember maximized window state to next launch

### ISSUE THREAD

**Issue by Zorakie** [aluxian/Messenger-for-Desktop#1243]
* Operating system: WIN 10 //ANY(?)
* Messenger for Desktop version: 2.0.8 - dev /// ANY

Messenger now remembers only last size of the window. It would be great, if if will be able to remember, if it was maximized last time.

Because now, if you have maximized window if will not make the window maximized next launch, and what more, it lets a little bit wierd size (the image shows it in little bit more expression way, in real, it is just a few pixels, but still, in some cases, e.g. Messege textbox for conversation writing is by ~1/5 covered by taskbar ... )

![obrazek](https://cloud.githubusercontent.com/assets/14437576/24321166/3d964024-1146-11e7-8702-dabc08056442.png)

Also Setting in App Link/Properties/Link(?) -> Launch: In maximized window 
DOES NOT WORK, it will still shows the window in last remembered state
(Sorry for czech image here, I do not use English wins so often to remember exact name of strings :) )

![obrazek](https://cloud.githubusercontent.com/assets/14437576/24321185/d3e70a90-1146-11e7-8fda-d911dc9a35e2.png)

**Comment by aluxian** [comment]
Thanks for the detailed report! I've already implemented this feature, but it seems it's not working for some people. Duplicate: https://github.com/aluxian/Messenger-for-Desktop/issues/884

>  it lets a little bit wierd size

I fixed this resizing issue in 2.0.10, which will be released soon.
