### ISSUE TITLE
Block seen and typing indicators stops working after program restart

### ISSUE THREAD

**Issue by bartech9** [aluxian/Messenger-for-Desktop#1245]
* Operating system: Win10 
* Messenger for Desktop version: 2.0.8

As the title says. After the restart even though the menu item is checked, it doesn't work. You have to recheck it for the function to start working again.

**Comment by Sytten** [comment]
Duplicate https://github.com/aluxian/Messenger-for-Desktop/issues/1244

**Comment by KTsarlz** [comment]
Why was this closed? Was this fixed?

**Comment by beRoller** [comment]
@KTsarlz  this was a duplicate issue .. :)

**Comment by KTsarlz** [comment]
But was it fixed?

**Comment by Sytten** [comment]
If the related issue is not closed, no
