### ISSUE TITLE
Ticking runOnOSStart  closes the app

### ISSUE THREAD

**Issue by MikeDabrowski** [aluxian/Messenger-for-Desktop#1247]
* Operating system: Win10
* Messenger for Desktop version: 2.0.8

```
If you're reporting a bug and think that a log would help, please do the following:
1. Open the app
2. Go to Menu > Run in debug mode
3. Try to reproduce the bug
4. Go to Menu > Open debug log
5. Paste it here
```

First of all I have the problem locating the app on PC. It does not appear in programs, nor desktop. I searched all programfiles folders and appdata.

About the issue : App opened right after installation, I ticked run on startup, app closed and now I still cant find it on my PC. During installation there is no option to choose where to install it. Sad. Will provide log when I find the app. 

Did scan for 'messenger' on C drive:
 - in appdata\local\messengerfordesktop there is no exe file. no app AFAIK
 - appdata\local\messengerfordesktop\SquirrelTemp sits there doint nothing, being not 'temporary'... it has *full.nupkg file which is 54MB lost for nothing ?
 - installing it again did not help

**Comment by aluxian** [comment]
Hi, the app should be located in `C:\Users\<user>\AppData\Local\messengerfordesktop`. Can you please try a complete wipe (Uninstall from Control Panel, remove folders in `C:\Users\<user>\AppData\Local` and `C:\Users\<user>\AppData\Roaming`)

Please reopen when you have more info so I can take another look. Thanks!

**Comment by MikeDabrowski** [comment]
Facebook purple started working again so I am not using messenger for desktop.

**Comment by aluxian** [comment]
No problem. What is Facebook Purple?

**Comment by MikeDabrowski** [comment]
It's library/plugin for Pidgin and Pidgin is multicommunicator. I use it all the time because it merges fb, telegram, slack, gmail/hangouts and many more.

Some time ago FB disabled XMPP for its messenger so someone made that plugin.
