### ISSUE TITLE
Pixelated app icon in the dock

### ISSUE THREAD

**Issue by Deuchnord** [aluxian/Messenger-for-Desktop#1249]
* Operating system: Arch Linux
* Messenger for Desktop version: 2.0.6

The application has a very low quality. Below is a screenshot in Cairo-Dock, but the icon also appears like this in GNOME Shell's dock.

![capture du 2017-03-30 21-19-43](https://cloud.githubusercontent.com/assets/7600265/24522464/faadc658-158f-11e7-95c8-3e87b611eb17.png)

**Comment by aluxian** [comment]
Please update to 2.0.9 and reopen if this is still a problem.
