### ISSUE TITLE
Um... what?

### ISSUE THREAD

**Issue by bandithedoge** [aluxian/Messenger-for-Desktop#1256]
* Operating system: Windows 10 64-bit
* Messenger for Desktop version: 2.0.9-stable

Honestly, this is the weirdest glitch I ever encountered while using this app.
Yesterday, I was asking a friend (using the app of course) about homework stuff. He told me what I wanted, akd I just replied "k".
Today, I'm booting my PC and what? I get a SHITLOAD of notifications from the app. They're just about me saying "k" like I sent it to myself.
I'm sorry for no screenshots, next time I will catch this sucker.

**Comment by aluxian** [comment]
Weird, something similar happened to a friend: she sent a message from her Android phone to a group and everyonein the group received the same message duplicated 10 times. I think it's a Facebook Messenger issue... please reopen if you can reproduce it.
