### ISSUE TITLE
Notifications on Linux

### ISSUE THREAD

**Issue by amankhoza** [aluxian/Messenger-for-Desktop#1263]
* Operating system: Linux (Fedora 24)
* Messenger for Desktop version: v2.0.9-stable

Not sure if it's a bug or feature request but currently on the Linux app there are no notifications for when you receive a new message. The indicator (icon in tray) turns blue which is good, but I think notifications would be really useful. I'm running GNOME as my desktop environment.

**Comment by SolarLiner** [comment]
Try going to Messenger's settings and turning on desktop notifications. They're handled by libnotify through ```notify-send``` so when the website sends a notification, they should display natively.

**Comment by amankhoza** [comment]
Whoops forgot to check settings, notifications work for me too :)
