### ISSUE TITLE
Clicking macOS desktop notifications crashes Messenger app

### ISSUE THREAD

**Issue by spyro92** [aluxian/Messenger-for-Desktop#1271]
* Operating system: macOS
* Messenger for Desktop version: v2.0.9-stable

Steps to replicate:
1. Command - W to close the window
2. Click the notification when it appears
3. start from step 1 again, the third time a notification appears the app will crash after you click it

[1493186790661.txt](https://github.com/aluxian/Messenger-for-Desktop/files/957400/1493186790661.txt)
I attached a log file, not sure if it helps...

**Comment by aluxian** [comment]
Thanks for the additional info! Duplicate: https://github.com/aluxian/Messenger-for-Desktop/issues/679
