### ISSUE TITLE
2.0.9 Windows Installer just runs the app instead

### ISSUE THREAD

**Issue by gregcotten** [aluxian/Messenger-for-Desktop#1272]
* Operating system: Windows 10
* Messenger for Desktop version: 2.0.9

I'm sure it's unintentional but it seems like the Windows 10 setup executable ("messengerfordesktop-2.0.9-win32-setup.exe") doesn't install but instead runs the application.

https://github.com/aluxian/Messenger-for-Desktop/releases/tag/v2.0.9

**Comment by aluxian** [comment]
That's how the installer works. When you run it, it will:

1. Copy the app into your AppData folder (i.e. install)
2. Create shortcuts (desktop, start menu)
3. Launch the app
4. You can now delete the installer

**Comment by gregcotten** [comment]
👍
