### ISSUE TITLE
Settings icon overlap.

### ISSUE THREAD

**Issue by purevertigo** [aluxian/Messenger-for-Desktop#1275]
* Operating system: Mac
* Messenger for Desktop version: 0.1.13

```
If you're reporting a bug and think that a log would help, please do the following:
1. Open the app
2. Go to Menu > Run in debug mode
3. Try to reproduce the bug
4. Go to Menu > Open debug log
5. Paste it here
```

The settings icon is obstructed by the red, yellow, and green mac windows resize icons. Refreshing usually fixes the bug.

**Comment by aluxian** [comment]
This is the wrong repository, there's no 0.1.13 version. Download the latest Messenger for Desktop version from here: https://github.com/aluxian/Messenger-for-Desktop/releases

**Comment by purevertigo** [comment]
You need to update the website then, https://messengerfordesktop.com/ shows as v1.0 still.
