### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by yjzhu1** [aluxian/Messenger-for-Desktop#1276]
I really enjoy this application. I was just wondering if you based any of the themes, in particular the midnight theme, off of any vim themes.

**Comment by aluxian** [comment]
I did not create them myself, if you click on each .css you’ll find the source in the header comment:

https://github.com/aluxian/Messenger-for-Desktop/tree/master/src/themes <https://github.com/aluxian/Messenger-for-Desktop/tree/master/src/themes>
