### ISSUE TITLE
Sounds for different events

### ISSUE THREAD

**Issue by msuchye** [aluxian/Messenger-for-Desktop#1282]
* Operating system: Windows 10
* Messenger for Desktop version: 2.09

Can you add to next beta or official version possibility to play sounds at different events? It is for example sound for sending and receiving message,  when user receive and read message etc. It would be useful mainly for blind users, because it is well accessible program for Windows.

**Comment by aluxian** [comment]
Nice idea. I'm not interested, but maybe someone is and will develop this. Duplicate issue: https://github.com/aluxian/Messenger-for-Desktop/issues/336
