### ISSUE TITLE
Trojan detected ?

### ISSUE THREAD

**Issue by BunnyBerserk** [aluxian/Messenger-for-Desktop#1304]
* Operating system: Windows 7 64 Home
* Messenger for Desktop version: v2.0.9-stable

```
This shows up after trying to reinstall the MSN for the second time after fresh Windows Installation.
The first time running the MessengerForDesktopSetup.exe doesn't find any trojan, but the second time it triggers that allert.
![image](https://image.prntscr.com/image/4-MGbP_sTgqXBfmEA2n1EA.png)

```

**Comment by joeyfigaro** [comment]
@BunnyBerserk haven't experienced this, but iobit's malware fighter isn't effective at fighting malware/does little to nothing. Should look into an alternative, which may help out.

**Comment by Sytten** [comment]
If you downloaded the software from the .com domain it contains ads than might be picked up as trojan. The .org builds are clean and in this case it's a false positive.
