### ISSUE TITLE
[suggestion] separate tray icon into separate package

### ISSUE THREAD

**Issue by andykais** [aluxian/Messenger-for-Desktop#1306]
Personally I dont have a strong need for the full desktop platform, the web app works well enough for me. However, I think you have an awesome tray icon packaged with the electron app. I dont know of any alternatives to simply get a tray update when you have new messages and am wondering if it could be separated into another, smaller project.

**Comment by aluxian** [comment]
Sorry, that’s not possible because the entire app is built on Electron.
