### ISSUE TITLE
Messenger for desktop newer version. When it will be released?

### ISSUE THREAD

**Issue by grigoris79** [aluxian/Messenger-for-Desktop#1330]
Windows 7 sp1 ultimate
2.0.9 stable

I want to know when you released the new version of messenger for desktop cause that 2.0.9 stable version is toooooo unstable cause many times when i open the program and write to some of my friend the text bat i write the messages is disappear and the only solution is to RESTART the program.

PLEASE FIX THIS ISSUE.

**Comment by Sytten** [comment]
We are not paid to update this software so fell free to contribute, I personally don't have a lot of time to give to this project anymore.
