### ISSUE TITLE
Virus and Bloatware being installed

### ISSUE THREAD

**Issue by RickyMindanao** [aluxian/Messenger-for-Desktop#1345]
* Operating system: WIn10
* Messenger for Desktop version: Latest

I installed this many yrs ago, and enjoyed it on my old laptop.  Decided to give it a new try a couple weeks ago..  but sadly it seems that project has started installing sneaky software, including a trojan into your machine with its installer now.  

```
If you're reporting a bug and think that a log would help, please do the following:
1. Open the app
2. Go to Menu > Run in debug mode
3. Try to reproduce the bug
4. Go to Menu > Open debug log
5. Paste it here
```

**Comment by FlaminSarge** [comment]
#1334
