### ISSUE TITLE
Drag and drop outside input area

### ISSUE THREAD

**Issue by derfl0** [Aluxian/Messenger-for-Desktop#136]
If you drag n drop any file outside the input area you get the normal browser reaction. In case of pictures this is to show them fullscreen, which without knowing the default back shortcut makes the messenger unusable until restart.

Version 1.4.3 
OS: OSX 10.10.3

**Comment by Aluxian** [comment]
I think I have an idea how I to fix this.

**Comment by Aluxian** [comment]
Duplicate: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/171
