### ISSUE TITLE
Add option for [x] to completely close app instead of minimize to tray

### ISSUE THREAD

**Issue by hikaritenchi** [Aluxian/Messenger-for-Desktop#140]
Since I only use Windows, I only know it happens there, but it'd be nice to have an option to have the [x] button completely close the app instead of just minimizing to the notification tray. My use case requires me to right click the notification tray icon and exit the app, which I consider an additional step that doesn't need to be there. (The Slack Windows app has this option.) Also related would be to have the [esc] key have its own options, because currently it's also mapped to "minimize to tray".

**Comment by Sytten** [comment]
Yes I will add it. Thanks
Meanwhile please try our new beta.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
