### ISSUE TITLE
No notifications immediately after login

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Messenger-for-Desktop#141]
I have 10.10.3; and I set it Messenger for Desktop to run at login. 
Notifications do not fully function (the sound does though) until I first click one of the facebook messages. 

After I click any message inside the window, and then X the program, the notifications pop up works! 

Summary:
1. Sound always works. 
2. Notification Banner alert works only after clicking a message.
3. Never however, do the alerts stay in Notification center.

**Comment by Sytten** [comment]
I don't have this issue on linux, will need testing on mac.
