### ISSUE TITLE
NSHighResolutionCapable: true

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Messenger-for-Desktop#143]
Might fix low-res on OS X.

**Comment by Sytten** [comment]
Will look at it.

**Comment by Aluxian** [comment]
Should be added here: https://github.com/Aluxian/Facebook-Messenger-Desktop/blob/master/gulpfile.coffee

In macPlist

**Comment by Sytten** [comment]
Ho thats means it would only apply on mac...
I think we should find a general solution for Windows and Linux HiDPI too.
