### ISSUE TITLE
Save position/windows size between sessions

### ISSUE THREAD

**Issue by Excitor** [Aluxian/Messenger-for-Desktop#145]
Would be great if the position windows size was saved in between sessions. For example making the windows smaller next time I log in and open up messenger it'll be the same small size not making me have to resize it again.

**Comment by KurtBliss** [comment]
I notice that it does, but not when using the snap feature, if you use it then it doesn't remember (only the last time you didn't use it). For windows 7 at least.

**Comment by SlavekT** [comment]
Two days ago I reinstalled Windows 10 and now Messenger doesn't remember the window size and position. It worked for me before. Any idea why? I can't find any settings for this.

**Comment by Sytten** [comment]
Please try our new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
This should now be handled automatically.
I will however check for myslef before closing the issue.
