### ISSUE TITLE
Spell checking disabled on OS X

### ISSUE THREAD

**Issue by bfred-it** [Aluxian/Messenger-for-Desktop#154]
All apps on OS X can use the system's spellchecker, but it appears to be disabled in FMD

**Comment by TheBlackViper1996** [comment]
Having the same issue on Linux as well

**Comment by gbardhoshi** [comment]
Any progress on this?

**Comment by bfred-it** [comment]
Same as this: https://github.com/sindresorhus/caprine/issues/14

**Comment by tnegoshi** [comment]
Seems another OS X FBMessenger app has the feature enabled [fb-mac-messenger/Enable spell checking #57](https://github.com/rsms/fb-mac-messenger/pull/57)

**Comment by bfred-it** [comment]
That doesn't look like it's based on Electron, that's the whole problem.

**Comment by Sytten** [comment]
I will check if I can enable that. It will depend mostly if the framework supports it...
