### ISSUE TITLE
[Windows] Portable Mode

### ISSUE THREAD

**Issue by jesseschoff** [Aluxian/Messenger-for-Desktop#156]
Would you consider allowing the app to run in portable mode and pull settings/account info from an INI file in the application's root directory?

**Comment by HRoland1** [comment]
+1

**Comment by iliyang** [comment]
+1

It would be really awesome to have this app in a self-contained folder with all settings being written there.

**Comment by iliyang** [comment]
Just noticed that Whatsie has a portable version!! It should be easy to port this functionality to Messenger, no?

**Comment by Sytten** [comment]
Yes its fairly easy. I will try for a future beta.
Meanwhile please try the new beta release.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/359 for more information about it.

**Comment by Sytten** [comment]
Yes its fairly easy. I will try for a future beta.
Meanwhile please try the new beta release.
See #458 for more information about it.
