### ISSUE TITLE
[Feature request] Button for all emot icons. 

### ISSUE THREAD

**Issue by Sjano** [Aluxian/Messenger-for-Desktop#161]
Facebook has alot of hidden emot icons in their chat.  I was wondering if you some how could add these to a button, you can find list over all on sites like this::
http://www.symbols-n-emoticons.com/p/facebook-emoticons-list.html

Also thank alot for making this available on the desktop

**Comment by Sytten** [comment]
That would be a nice feature, but I don't have the time to implement it. Still I encourage you to test our new beta version.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information about it.
