### ISSUE TITLE
Supply Ubuntu PPA

### ISSUE THREAD

**Issue by cdelahousse** [Aluxian/Messenger-for-Desktop#166]
This would be a nice to have but not very high priority.

**Comment by Aluxian** [comment]
I'll create a personal one after the new release.

**Comment by tristan-k** [comment]
Any news on that?

**Comment by Sytten** [comment]
It is still planned but not for the next month I would say,
Meanwhile please test our new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Comment by PiotrDabr** [comment]
Any update on that? Or is it already implemented but does not work for me?

**Comment by Sytten** [comment]
It will done for the V2, dont know when
