### ISSUE TITLE
Windows 10 Notification Center

### ISSUE THREAD

**Issue by pedroabrunhosa** [aluxian/Messenger-for-Desktop#170]
First of all great job doing this! I love the app. I guess it would be a nice add-on to connect the app desktop with the notification center on Windows 10. Make it popup when we receive a message.
Keep the awesome work.

**Comment by aarodynamics** [comment]
This would be a great feature to have.

**Comment by losboss86** [comment]
I'd love to see this also. It doesn't seem to have any notifications except for on the icon itself - I'd love to see the option of having it show a small preview of who's messaging and a little of the content of the message. Regardless of that though, this is exactly what I've been looking for. Great app! Thanks.

**Comment by EudesRobin** [comment]
+1

Awesome work btw ;)

**Comment by Solymi007** [comment]
Someone know a proper solution for this problem? I'm using win10  but my notification center can't recognize the Messenger and the  messages don't even appearing in the right side.This is a little bit frustating :) . I like your app and you are doing a great job with this.

**Comment by jackwilsdon** [comment]
Looks like NW.js supports native notifications (issue nwjs/nw.js#27), so as long as we can capture the notifications from messenger.com, it should be possible.

**Comment by Sytten** [comment]
I will take a look if its possible with our current framework.
Meanwhile please test our latest beta, see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
We now use chrome-like notifications

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
