### ISSUE TITLE
Windows icon bad antialiasing

### ISSUE THREAD

**Issue by Frexuz** [Aluxian/Messenger-for-Desktop#173]
Not sure why this happens, and the `icon.ico` seems nice. But compared to other apps, it looks really bad. (Windows 7, 1920x1080)

Screenshot:

![image](https://cloud.githubusercontent.com/assets/49692/8553310/d55f6b08-24e2-11e5-9356-a59c6ec49831.png)

**Comment by HRoland1** [comment]
+1

**Comment by Sytten** [comment]
I don't see the problem here
