### ISSUE TITLE
Separate conversation and friend-list windows

### ISSUE THREAD

**Issue by chrylis** [Aluxian/Messenger-for-Desktop#177]
I'm coming from Pidgin, which was finally just disconnected from Facebook, and I prefer having my friend list open all the time and having conversations open in a separate window (and I used a shared tabbed window in Pidgin). It would be nice to be able to put the sidebar in its own window; I'm not sure whether this is what #55 is referring to.

**Comment by AndreiTelteu** [comment]
+1
The Skype windows app can separate these two things. :)

**Comment by Sytten** [comment]
This would require a lot of work (since we are only a web-wrapper), but I will add it to the TODO.
Meanwhile please try our beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
