### ISSUE TITLE
Support for multiple accounts

### ISSUE THREAD

**Issue by deekej** [Aluxian/Messenger-for-Desktop#179]
Hey!

Please, add the support to have multiple accounts enabled - many people, including me, have multiple FB accounts for some different reasons.

It would be good to be able to chat with people from all the accounts. Pidgin, e.g. was able to do this.

Thanks.

**Comment by deekej** [comment]
Well, thanks for the reply... I guess... :D

**Comment by Aluxian** [comment]
Sorry, I don't have plans to support this soon. I'll accept PRs.
