### ISSUE TITLE
"Keep the conversation going from your phone" banner

### ISSUE THREAD

**Issue by benbristow** [Aluxian/Messenger-for-Desktop#18]
I've noticed that on the desktop app there's a message banner that says:
"Keep the conversation going from your phone"
And it wastes quite a lot of space, and looks out of place.

It would be cool if this could be hidden upon launch.

![Screenshot](http://a.pomf.se/irpvhi.png)

**Comment by Aluxian** [comment]
Hey @benbristow, does that banner appear every time you use https://www.messenger.com too?

**Comment by mzgol** [comment]
It appears for me every time I use messenger.com.

**Comment by Aluxian** [comment]
@mzgol Can you please go to messenger.com, right-click on the black banner, select "Inspect Element" ([see here](http://cl.ly/image/3O3x0M1L2a28)) and send me a screenshot with the code on the right?

**Comment by Aluxian** [comment]
@mzgol I will find an account on which I can reproduce this and I'll remove the banner.

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/74af9c6c3716b1e5dc9e5f87b600b99eccef911d

**Comment by lampuiho** [comment]
This banner is showing on Windows version for me

**Comment by petercunha** [comment]
Banned is showing for me, and I even have the app. This needs to be fixed.

**Comment by sunildhillon** [comment]
This banner is showing on Windows 8.1, chrome version: 53.0.2785.143 m (64bit)

**Comment by nistath** [comment]
The banner is still showing on Chrome and Messenger for Desktop (2.0.1-beta), as of now.
document.getElementsByClassName("_s15") returns for me the banner's div. Delete that @Aluxian and it disappears.
