### ISSUE TITLE
Online Friends List

### ISSUE THREAD

**Issue by joejelly** [Aluxian/Messenger-for-Desktop#183]
Is it possible to add a list of online friends to this program?

**Comment by tzaroon** [comment]
please add an icon like android of online friend list
... Amazing app.........

**Comment by Sytten** [comment]
I will add it as a feature request, but there is little chance it will be implemented shortly, sorry.
Meanwhile please try the new beta, see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information about it.
