### ISSUE TITLE
Add an option to see who's online & Last online time

### ISSUE THREAD

**Issue by Manojworld** [Aluxian/Messenger-for-Desktop#201]
Like mobile messenger please add an option to see online users and last online time.

**Comment by nelson6e65** [comment]
:+1:

**Comment by HRoland1** [comment]
+1

**Comment by kyle1602** [comment]
This would also make it better

**Comment by Sytten** [comment]
I agree that would be nice, but since its only a web wrapper of the website I don't think that would be possible (at least not easily).
