### ISSUE TITLE
Incoming call, no notification/flash/alert/sound

### ISSUE THREAD

**Issue by AndreiTelteu** [Aluxian/Messenger-for-Desktop#202]
When I get an incoming call on facebook messenger for desktop i don't get any alert or notification or sound.
Future feature:
- notification when incoming call
- select ringtone for incoming call

**Comment by Sytten** [comment]
Ho that is true, I will see to that.
Meanwhile please try the new beta.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
