### ISSUE TITLE
huge energy impact

### ISSUE THREAD

**Issue by sscryp** [Aluxian/Messenger-for-Desktop#210]
App consumes an enormous amount of energy on OS X. On average 600 times more than the second most energy consumer app, I think this is an issue!

**Comment by imsys** [comment]
Yes, it's an issue, and I'm also waiting for this fix. : S
#162

**Comment by iainelder** [comment]
Wow. Messenger App is off the chart, even when it is doing nothing. ![image](https://cloud.githubusercontent.com/assets/5024311/14322234/64b3aaa6-fc1c-11e5-80bb-9a04face8966.png)

**Comment by Sytten** [comment]
We know this issue, we reduced the energy impact in the latest beta (see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458), but we still have some problems when the window is visible (on mac it seems to be worse)...
