### ISSUE TITLE
Where can I record a voice message?

### ISSUE THREAD

**Issue by crisjansayson** [Aluxian/Messenger-for-Desktop#215]
I downloaded this because I saw the"voice record" feature on the website but later I found out that the feature I was looking forward was not even there. :(

**Comment by jackwilsdon** [comment]
It looks like messenger.com doesn't have the feature either. You may be thinking of Messenger for Mobile devices.

**Comment by crisjansayson** [comment]
![but](https://cloud.githubusercontent.com/assets/13714998/9157628/de34765a-3f37-11e5-86f6-232c06e6e35f.PNG)

**Comment by crisjansayson** [comment]
but :(

**Comment by jackwilsdon** [comment]
Looks like that needs removing from the site.

**Comment by crisjansayson** [comment]
https://www.messenger.com/features#voicemessages
heres the url of the voice message

**Comment by jackwilsdon** [comment]
Yes, but that's on Messenger mobile (the mobile app).

**Comment by unitbroker** [comment]
New job with southern Cali apparel manufacturer
Here's a 5$ coupon. http://shop.pe/iD1nT
If I sell $500 dollars by 5pm <x-apple-data-detectors://2> I keep my lights
on!
We have really cool stuff!
Have a good weekend!

On Saturday, August 8, 2015, crisjansayson <notifications@github.com> wrote:

> I downloaded this because I saw the"voice record" feature on the website
> but later I found out that the feature I was looking forward was not even
> there. :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/215>.
>


-- 
Rob Estes
Ipad_1
Unitbroker@gmail.com
602-319-4052

**Comment by Sytten** [comment]
That would be a nice feature, but not top priority right now.
Meanwhile please see the beta if you are still interested in the app: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
