### ISSUE TITLE
Please provide an option to change notification sound

### ISSUE THREAD

**Issue by lordganja** [Aluxian/Messenger-for-Desktop#217]
Please provide an option so we can change the notification sound. I don't want to disable the annoying sound but I want to change it. Maybe something like we can select and locate the wav file in our desktop so we can provide a notification sound that we like. thanks!

**Comment by Sytten** [comment]
That would be a great feature, but it requires some work (not a priority right now)
Meanwhile please see the beta: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
