### ISSUE TITLE
Bitmoji support

### ISSUE THREAD

**Issue by ekolis** [Aluxian/Messenger-for-Desktop#219]
http://www.bitmoji.com/

Customizable avatar emoji. There's a Chrome extension which lets you pick an emoji from a popup; perhaps the same sort of thing could be integrated into this app?

**Comment by Sytten** [comment]
That would be a nice feature also proposed here:
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/309#issuecomment-228928263

Meanwhile please try the new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
