### ISSUE TITLE
Can't see who is online.

### ISSUE THREAD

**Issue by zaxad23** [Aluxian/Messenger-for-Desktop#23]
Hi,
can you make a section of people who are on Facebook?
Thanks.

**Comment by rahul467** [comment]
Kk thanks

**Comment by abdelhamidabid** [comment]
yes we cant see who is online ! plz fix it

**Comment by tzaroon** [comment]
add an icon like android of Online Users......
Amazing app............ (y)

**Comment by rahul467** [comment]
Hi,

I’m using GoGo and wanted to recommend this app to you.
GoGo is a personalised lock screen app for your android phone. GoGo shows
you the latest news and stories. Also you earn Free Talktime every time you
read a story or unlock your phone

GoGo is light, fun and easy to use. Also it is very addictive! On top of
this, the free talktime is simply great!

Click below URL to install GoGo now & get 500 GoGo points
http://r.planetgogo.com/ma05v/5

You can thank me when we meet next.

Cheers
