### ISSUE TITLE
Cannot zoom in on pictures

### ISSUE THREAD

**Issue by FedericoNaranjo** [Aluxian/Messenger-for-Desktop#230]
I cannot zoom in on any pictures, this is a feature I would like as opposed as having to download the images if I want a closer look.

**Comment by jackwilsdon** [comment]
Looks like this is an open issue with NW.js itself: nwjs/nw.js#3266

**Comment by Sytten** [comment]
That would be a nice feature, but first we must handle the shortcuts properly.
Meanwhile please see our new beta. More information here: #458
