### ISSUE TITLE
Ability to hide thumbnail when sending link

### ISSUE THREAD

**Issue by ShaneOH** [Aluxian/Messenger-for-Desktop#233]
messenger.com doesn't support this, and this app seems to be based on that design, but when using facebook.com, pasting a link in a message box gives you the ability to remove the thumbnail before sending. That would be a great feature to include here too if possible!

**Comment by Sytten** [comment]
First of all, we are only a wrapper around messenger.com so features like this one are hard to implement since we usually don't mess up with the html.
That being said I agree that would be a nice feature.
Meanwhile please see our new beta. More information here: #458
