### ISSUE TITLE
Copy + Paste Image (maybe file too) Feature Please!

### ISSUE THREAD

**Issue by ekokthx** [Aluxian/Messenger-for-Desktop#236]
For example, in the Hangouts App, you can copy and image from your computer, or the internet, and then just press Cntrl+V (or Paste) into the messenger window and instantly have your picture/file there ready to send!

This would be a really great feature to have :+1: 

Honestly, you guys have done a fantastic job with this Messenger app.  Very professional and looks like it belongs to facebook cause it's so nice.  Well done!!

**Comment by HRoland1** [comment]
+1

**Comment by NoNameProvided** [comment]
> you can copy and image from your computer

It already works for me on Windows. You have to open the image with the built in image viewer (pre Windows 10 or Windows 10 Universal photo app) and press Ctrl + C while the app has focus. After this pressing Ctrl + V in a conversation should insert the image. 

> Honestly, you guys have done a fantastic job with this Messenger app. Very professional and looks like it belongs to facebook cause it's so nice. Well done!!

Actually it belongs to Facebook, the app is a wrapper around the official messenger.com website.

**Comment by Sytten** [comment]
Would be a nice feature, but its low priority...
Meanwhile please see our latest beta. More information here https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Comment by ekokthx** [comment]
The whole purpose of postimage is to be able to effectively post an image.
Dragging+dropping an image is 1/3rd of the applicable nature of posting an
image.  I believe that it would be incredibly beneficial to retain this
feature.

**Comment by Sytten** [comment]
So what do you propose really? Drag/drop or Copy/Paste (and where should that copy/paste work, not sure to understand fully your request).

**Comment by ekokthx** [comment]
The old version allows you to drag & drop a file from your Windows folder
into the file upload field.  I don't see this feature in the new version;
even though the interface looks cleaner.  Without this feature, users are
forced to click on the upload button and search for their file in the file
system.


Regards

**Comment by Sytten** [comment]
The drag and drop works perfectly here on windows and linux!
Still not understanding your request...
