### ISSUE TITLE
Allow us to customize the theme

### ISSUE THREAD

**Issue by kyle1602** [aluxian/Messenger-for-Desktop#237]
It'd be nice if we were able to change the color scheme of Messenger using a color wheel or something because at some lightings, the font really isn't readable nor the pictures seen very well in some settings

**Comment by Sytten** [comment]
With the new beta the themes should be better. Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458.
I will keep your request open, but I don't promise I will find time to develop it.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
