### ISSUE TITLE
Escape key bug on windows

### ISSUE THREAD

**Issue by hjwright** [Aluxian/Messenger-for-Desktop#239]
When the "esc" button is pressed while on messenger the window closes and keeps the messenger.exe process running thus not allowing you to open a new window unless the previous process is terminated on task manager.

**Comment by jackwilsdon** [comment]
Do you have the same problem when right clicking the window and clicking "Quit Messenger"?

**Comment by hjwright** [comment]
It's not in the tray after hitting escape, and yes, i do have the same problem after right clicking and closing

**Comment by jackwilsdon** [comment]
It's possible that it's not exiting due to the ongoing `setInterval` [here](https://github.com/Aluxian/Facebook-Messenger-Desktop/blob/master/src/components/dispatcher.js#L4). The best way to deal with this would probably be to store the ID returned by it and `clearInterval` it on window close.

**Comment by Sytten** [comment]
Please try the new beta, see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
The setInterval should be better handled now.
I will leave this issue open until I get a confirmation that the issue is gone.
