### ISSUE TITLE
App crashes when Video call is made

### ISSUE THREAD

**Issue by faizaanceg** [Aluxian/Messenger-for-Desktop#24]
On clicking either the Phone icon or the Video call icon, the app crashes.

**Comment by Aluxian** [comment]
Let's see how we can debug this.

1. Does it work on messenger.com?
2. Have you managed to build the app yourself so far?

**Comment by faizaanceg** [comment]
1. Yes both when clicked, open a new window for the call
2. I did download the repo and ran node build.js after installing the dependencies

**Comment by Aluxian** [comment]
Can you please do these steps:

1. go to `./src/package.json`
2. change `toolbar: false` to `true`
3. build the app and run it
4. there's a cog icon near the address bar, press that and it should open a chrome dev tools window
5. tell me what is in there, and do you notice anything when clicking the voice call button? i.e. does any error appear there?

What OS are you running?

**Comment by faizaanceg** [comment]
I am running Ubuntu 14.04 32-bit, I have attached a screenshot of the dev tools window

![screenshot from 2015-04-14 20 18 10](https://cloud.githubusercontent.com/assets/6629172/7139393/a9715e7a-e2e3-11e4-8292-32a31de41938.png)

**Comment by Aluxian** [comment]
Thanks. Is this all that appears in the dev tools window? Those errors are about something else. I don't know why it would crash.

**Comment by faizaanceg** [comment]
Well, I am not familiar of how to catch those errors, when I click on either of the buttons, I can see a new window trying to open up but then it closes and thereby everything closes including the tray icon.

**Comment by Aluxian** [comment]
I still have no clue. We'll see if more users report this, so far you seem to be the only one. Have you tried updating? There's a new release (v1.2.2).

**Comment by faizaanceg** [comment]
Downloading and building it now.

**Comment by Aluxian** [comment]
Or you can just download from here https://github.com/Aluxian/Facebook-Messenger-Desktop/releases

**Comment by faizaanceg** [comment]
Oops, didn't see the link. Anyway built it and ran now. Alas, same result :-1:

**Comment by Aluxian** [comment]
This sucks. :/

**Comment by omarojo** [comment]
Same crashing happening with me.
