### ISSUE TITLE
Cmd+Ctrl+Space shortcut doesn't work on OS X

### ISSUE THREAD

**Issue by tgkokk** [aluxian/Messenger-for-Desktop#253]
If you press `⌘⌃Space` (Cmd+Ctrl+Space) on OS X, you should get the "Special Characters" popup. However, the shortcut doesn't work, but going through the Edit menu does.

**Comment by toralux** [comment]
I can confirm this is still a problem in May 2016. As emoticons picks up and get more and more important on phones, also desktop should support them just as easily when the OS support it (as OS X does with Cmd+Ctrl+Space).

**Comment by GandalfSaxe** [comment]
Confirming, this is still an issue.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
