### ISSUE TITLE
Global keyboard shortcut to bring Messenger to front?

### ISSUE THREAD

**Issue by josefdlange** [Aluxian/Messenger-for-Desktop#257]
Am I really dense? I can't seem to find a way to bring Messenger to the foreground in Mac OS X with my keyboard, since it's not in the Command-Tab application switcher. If there isn't the functionality here presently, I'd love to see it happen -- even if it means me implementing it. I'd probably need to be pointed in the right direction but I'm more than willing to contribute my Cocoa knowledge if need be.

**Comment by dufferzafar** [comment]
Yes, there should be a global shortcut key - for when the app is running in the Menu Bar mode on mac.

**Comment by Newgap** [comment]
Has this been implemented? It is not quite clear. If yes, I can't find the shortcut.
