### ISSUE TITLE
Window restore outside of screen

### ISSUE THREAD

**Issue by saper-2** [Aluxian/Messenger-for-Desktop#268]
Hi,

Sometimes I use 2nd screen with my laptop, and I dragged window to that 2nd monitor, now window shows up where it was in that 2nd monitor but the extra monitor is no longer connected.

So please add check for desktop bounds and window location when window is restoring.

**Comment by devstu** [comment]
I am having the same problem. No matter what I do I can't get the screen to come back into the main window.  My only solution is to plug back into an external monitor pull it back over to the main screen and close and re-open. 

Love the app, but this bug is really affecting usability.
