### ISSUE TITLE
Video's won't play

### ISSUE THREAD

**Issue by sheldonhull** [Aluxian/Messenger-for-Desktop#269]
So far I can't get videos to play in the app. It will open the overlay, but no video will play. Is anyone else experiencing this problem?

**Comment by jackwilsdon** [comment]
Does it work on messenger.com for you?

**Comment by Takuaraa** [comment]
I have the same problem.

**Comment by juanjotoronja** [comment]
yeah it does play in the web page but doesn't play Video/Sound received it just keeps loading

**Comment by TrololoManPL** [comment]
The same problem.

**Comment by s22su** [comment]
Same here.
