### ISSUE TITLE
Make window stay on top

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Messenger-for-Desktop#270]
Add option

**Comment by supercoolprogramguy** [comment]
Personally, this hasn't been an issue because I use an autohotkey script that allows a persistent window:

maybe it could help you if you're trying to develop this functionality natively?
http://www.howtogeek.com/196958/the-3-best-ways-to-make-a-window-always-on-top-on-windows/

**Comment by Iodailis** [comment]
I'd ke this option
