### ISSUE TITLE
Suggestion: why not Hangouts?

### ISSUE THREAD

**Issue by gabrihellmateus** [Aluxian/Messenger-for-Desktop#271]
https://hangouts.google.com/

Keep the good work. I appreciated.

**Comment by shortspider** [comment]
+1. Please

**Comment by cassiodoroVicinetti** [comment]
+1

**Comment by Sytten** [comment]
Its not planned for the near future, but I agree it would be nice to have a global app for multiple accounts and services.
For reference: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/158
