### ISSUE TITLE
[Feature Request] Notifications without message text

### ISSUE THREAD

**Issue by supercoolprogramguy** [Aluxian/Messenger-for-Desktop#274]
Basically being able to receive a notification without the message content for using at work. If you're a Pushbullet user you might know this as "Only show notification title" in their settings menu. 

They've also managed to implement the first really viable chatheads system that I've used on a desktop, so that'd be cool too (but I imagine that would be incredibly difficult lol).

Thanks for your work on this great app!

**Comment by Sytten** [comment]
That should be something easy to do.

Please try our latest beta.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Comment by ekolis** [comment]
Do we even have notifications? The only notifications I'm getting are from Pushbullet, and when I click on one of those, it opens a messenger.com tab in my browser, not the existing Messenger for Desktop window.

**Comment by Sytten** [comment]
No it was there in 1.5, I had to switch them as chrome notifications because at the time NWJS had stopped providing native ones.
You should probably activate them in the facebook settings ;)

**Comment by ekolis** [comment]
Looks like enabling desktop notifications on either facebook.com or messenger.com (I forget which) solved my problem!
