### ISSUE TITLE
RaspberryPi arm v6/7 support?

### ISSUE THREAD

**Issue by PeterDaveHello** [Aluxian/Messenger-for-Desktop#284]
Hi there,

This project is awesome! I just wonder is there official support to use it on Raspberry Pi on raspbian? If not, any one tried it? Because Raspberry Pi is not so fast, so just wanna ask first, if no body tried before, maybe I can try it and share the result.

Thanks a lot!

**Comment by Sytten** [comment]
Just install it on a raspbian, should work out of the box.

**Comment by PeterDaveHello** [comment]
Thanks @Sytten, is it possible to provide the deb package for raspbian? Current release packages look like for PC only, thanks.

**Comment by Aluxian** [comment]
@sytten how can it work out of the box? Our builds are x86 and x64, not ARM. 

@peterdavehello we currently don't support ARM computers, but we might do in Messenger for Desktop 2 (planned for this summer). 

I'll reopen this to have it as a feature request.

**Comment by PeterDaveHello** [comment]
Thanks! Feel free to ping me if you need somebody to help test it!

**Comment by Sytten** [comment]
@Aluxian Yep true, I wasn't thinking about the architecture.
Don't think electron supports ARM anyway...

**Comment by Aluxian** [comment]
@sytten well... Look again :D They have linux-arm releases on the releases page. I checked myself before I wrote the other comment.

**Comment by Sytten** [comment]
Yes its maybe possible then. Still you have different types of ARM, but since the RPI is a popular device they probably provide the support for it.
