### ISSUE TITLE
Conversation out of frame, when width is less than 640 pixels

### ISSUE THREAD

**Issue by chinhan1991** [Aluxian/Messenger-for-Desktop#290]
When the window is scale down to less than 640 pixels in width, friend's chat jumps out of frame.
OS: Ubuntu 14.04.
AutohideSideBar = true
![screenshot from 2015-11-18 12 01 14](https://cloud.githubusercontent.com/assets/4354717/11239419/260a9ae2-8dec-11e5-907a-b549f0b8bff4.png)

**Comment by Sytten** [comment]
The auto-hide sidebar isnt working very well. I will take a look at it.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 meanwhile
