### ISSUE TITLE
High CPU usage and laptop heating

### ISSUE THREAD

**Issue by eallik** [Aluxian/Messenger-for-Desktop#293]
I'm on 1.4.3 and OS X 10.9.5, and Messenger.app routinely uses 2 cores with both being at 25% of usage, leading to laptop heating and battery drain.

**Comment by torokati44** [comment]
Since Messenger uses the same engine as Chrome and Chromium under the hood, this might be related to this: https://code.google.com/p/chromium/issues/detail?id=518209 ?
Do(es) the process(es) causing high CPU usage have anything to do with GPU handling in your case?

**Comment by eallik** [comment]
I have no idea about the GPU handling question, I'm afraid..

**Comment by sentientredstripe** [comment]
I've been having this issue too on Windows except the CPU usage only spikes when the app is displaying gifs.

**Comment by EWER115** [comment]
also battery drain on rMBP 2015 13" model, osx el capitan 10.11.1. In activity monitor i can see high average battery usage in comparison to other apps: https://screencloud.net/v/32U9. After closing the app battery life improved significantly.

**Comment by djdiaz** [comment]
I'm seeing constant 5-10% CPU usage from each of two "nwjs Helper" processes while the app is open (v1.4.3) on OS X 10.11.4. No GIFs or other heavy content displayed, just text.

**Comment by barbushin** [comment]
Same problem in Win 10x64. Using 1.4.3 version. If Messenger is not minimized, it's always using 10-15% of my Intel i7 CPU. May be it's because of some GIF stickers are played in background? Anyway, there is screenshot of Dev Tools Profile tab.

![image](https://cloud.githubusercontent.com/assets/683352/15121257/42a0b70c-164c-11e6-95cd-d857953e20c6.png)

**Comment by etrnljg** [comment]
10% of CPU usage on Linux Mint... Strange since Whatsie is under 3%.

**Comment by Aluxian** [comment]
Messenger for Desktop doesn't run on what Whatsie runs yet (Electron). However, Messenger for Desktop 2 will run on Electron. ETA: this summer

**Comment by Sytten** [comment]
Still having so performances issues due to the useless renders being made. 
Working on it.

**Comment by etrnljg** [comment]
Up!
Just got MessengerFD2 as update -> **low CPU usage \o/**

However, the CPU goes from 0.1 to 24% for 2 or 3 seconds when switching between plenty of conversations super fast (just a detail, in case you are still searching for optimizations).

I think you can now close that issue.

**Comment by Sytten** [comment]
Well its a browser under, so animations are costly for sure ;)
Glad Electron reduced the overall rendering cost
