### ISSUE TITLE
Linux version, dark theme

### ISSUE THREAD

**Issue by WassiliaPL** [Aluxian/Messenger-for-Desktop#298]
When using auto-hide sidebar and dark theme the sidebar is transparent for the first person on list and for the search panel. This is so annoying. I want to use that theme but can't because of this issue.

**Comment by Sytten** [comment]
The auto-hide sidebar inst working very well.
Please try the new beta release.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
