### ISSUE TITLE
HiDPI Support ?

### ISSUE THREAD

**Issue by medemine** [Aluxian/Messenger-for-Desktop#301]
Application looks very small in HiDPI screen (3200x1800).
is there any tweak to configure messenger to support HiDPI in Gnome 3.16 ?

**Comment by cydrobolt** [comment]
Same issue. I also have a 3200x1800 panel on my 13" laptop and the text is extraordinarily tiny.
I'm running GNOME 3.18.2

I love the app, please fix :(

**Comment by Sytten** [comment]
I might try to fix that if I have some time, but cant test since I dont have a screen like that.

**Comment by kernschatten** [comment]
Running `messengerfordesktop --force-device-scale-factor=2` in the Linux terminal worked for me using 2880x1620 display.
