### ISSUE TITLE
Feature Request: Integrate option to enable/disable display of yahoo messenger emoticons 

### ISSUE THREAD

**Issue by danielmihai** [Aluxian/Messenger-for-Desktop#309]
Some of us still use the emoticons from yahoo messenger and type them directly in the message. I offer to contribute to this feature request, if you'd like. There is a chrome plugin that enables this in the facebook chat from facebook.com. 

Please take the time to consider my request and please respond asap. I would like to develop it asap. 

Thanks, 
Daniel.

**Comment by Sytten** [comment]
Actually the dev isnt maintaining this software. He is in the process of creating a new version with another framework (NWJS isnt very well documented nor very flexible). But during that time I decided to maintain my own fork. If you want to develop that option, please make a pull request to my fork so I can add it.

**Comment by Sytten** [comment]
Is it still something needed. 
I would be glad to have you on board to make that feature appear in the software.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Comment by danielmihai** [comment]
Hi @Sytten ,

Glad to be hearing from you. What are the terms for an official maintainer? 
And besides the question, I would like to know more about the feature request implementation. 

Looking forward to hearing from you asap

Warm Regards,
Daniel M. Colceag.

**Comment by Sytten** [comment]
Not sure to understand what you mean by terms for official maintainer.
I develop the software until @Aluxian release the v2.
You can contribute if you want by doing some PR.

Its your feature request, you tell me want you want to do :)

**Comment by danielmihai** [comment]
what does it mean to be an official maintainer?

do you want me to create the story for the feature?

**Comment by Sytten** [comment]
Mostly to do some bug fixing and releasing the builds.
You have full control over the code.

Yes create the story. I don't have the time to implement it myself, but someone might do it (or you if you feel like it)

**Comment by danielmihai** [comment]
the story was to be reviewed by both and then discuss the details of implementation, ux/ui details, coding style and so on and so forth.
what do you say?

and after we finish discussing the details and I implement it, we review it and see if you or aluxian  like the imlementation, I could take some bug fixing on the list, if I have the time

**Comment by Sytten** [comment]
I like it! 
The code is a bit messy right now, so a discussion about the implementation would be more than welcomed. I know the v2.0 will be an entirely new code, but I don't like the idea of increasing the mess for no reason. 
You can join me on gitter if you want to chat, I'm always connected (Time zone East Canada).
I have a busy week, but maybe this week-end would be a good time for that.

Thanks for your help!
