### ISSUE TITLE
Install problem in Kubuntu 15.10

### ISSUE THREAD

**Issue by impulsive1976** [Aluxian/Messenger-for-Desktop#320]
So all was well when I tried running this fantastic app in Ubuntu-Gnome 15.10 but it has broken apt-get completely in Kubuntu 15.10. 
I ran the install using the provided 64bit.deb file from your site for both the facebook messenger and what's app messenger and they seemed to work fine but when I went to look in the menu to find and run the app post install I found the app was not in the menu and that when I looked for the executable in /usr/bin it wasn't there either. which on it's own I wouldn't be to concerned but now when ever I run a command in apt it errors out with the following:

Setting up messengerfordesktop (1.4.3) ...
/var/lib/dpkg/info/messengerfordesktop.postinst: line 7: desktop-file-install: command not found
dpkg: error processing package messengerfordesktop (--configure):
 subprocess installed post-installation script returned error exit status 127
Setting up whatsappfordesktop (1.1.0) ...
/var/lib/dpkg/info/whatsappfordesktop.postinst: line 7: desktop-file-install: command not found
dpkg: error processing package whatsappfordesktop (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 messengerfordesktop
 whatsappfordesktop  
E: Sub-process /usr/bin/dpkg returned an error code (1)   

I managed to get rid of the apt error by running the apt-get remove command for both applications but still I would really like to be able to use this app under Kubuntu :)

**Comment by cassiodoroVicinetti** [comment]
In my Plasma 5 64-bit system, this application is working fine.

The executable should be in `/opt`, not `/usr/bin`.

Try to install the deb file from the terminal:
>`sudo dpkg -i Messenger_linux64.deb`

What does the shell print out?

**Comment by SalahAdDin** [comment]
Any new change for this great app¡?

**Comment by evgeni-tsn** [comment]
I have the same problem. Here is the output.

$ sudo dpkg -i Messenger_linux64.deb
Selecting previously unselected package messengerfordesktop.
(Reading database ... 188906 files and directories currently installed.)
Preparing to unpack Messenger_linux64.deb ...
Unpacking messengerfordesktop (1.4.3) ...
Setting up messengerfordesktop (1.4.3) ...
/var/lib/dpkg/info/messengerfordesktop.postinst: line 7: desktop-file-install: command not found
dpkg: error processing package messengerfordesktop (--install):
 subprocess installed post-installation script returned error exit status 127
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
messengerfordesktop

**Comment by cassiodoroVicinetti** [comment]
Install the [`desktop-file-utils` package](http://packages.ubuntu.com/wily/desktop-file-utils). The script uses `desktop-file-install` to install the launcher (a .desktop file). @Sytten Maybe this package should be put as a dependency in the .deb installer.

**Comment by Sytten** [comment]
Yeah I could do that. Currently I'm quite very busy and don't have time to work on that...

**Comment by evgeni-tsn** [comment]
@cassiodoroVicinetti Thanks, it works now. Can I make it to stay in background? For example when I hit Esc or X the messenger close itself and I can't receive msgs.

**Comment by evgeni-tsn** [comment]
Today when I tried to open Messenger i got this in terminal:

[17977:0119/161231:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

**Comment by Sytten** [comment]
@evgeni-tsn use my fork if you want it to stay in background.
As for the other problem, I dont know where it comes from but suspect that its how the NWJS is implemented in chromium

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
@cassiodoroVicinetti pointed out a good thing about the dependencies so I will let this thread open
