### ISSUE TITLE
OS X El Capitan - performance issues 

### ISSUE THREAD

**Issue by ondrejfuhrer** [Aluxian/Messenger-for-Desktop#330]
Hi,

after starting the app on MacBook Pro (OS X El Capitan) I experience very high processor load (especially when writing with someone). Is anyone else experiencing this? Can this be fixed?

![messenger processor load](https://cloud.githubusercontent.com/assets/10830505/12536187/bb760a9a-c29d-11e5-846d-5b2ece818e56.png)

Thanks.

**Comment by tatwater** [comment]
+1

**Comment by Samgarr** [comment]
Same on Arch Linux!

**Comment by how2945ard** [comment]
+1

**Comment by Sytten** [comment]
Performances should be a little better, but the issue is still valid.
