### ISSUE TITLE
Press Enter to Send

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Messenger-for-Desktop#342]
I would like to recommend you to add a toggle feature already existing on the official Facebook website:
"Press Enter to Send." which would allow users to write paragraphs rather than just a single block of text and avoid sending a message by mistake.

**Comment by rajatshah92** [comment]
If you want to go to the next line, you can use shift+enter.

**Comment by NitsuSaiNeko** [comment]
@rajatshah92  Exactly. Both Ctrl+Enter or Shift+Enter would go to the next line. In fact, most messenger or send-upon-enter text box works like this.
