### ISSUE TITLE
Missing URL preview

### ISSUE THREAD

**Issue by mrbax** [Aluxian/Messenger-for-Desktop#353]
In browser Messenger chat, one can paste a URL and a preview pops up.  One can then replace the URL with comments.  Neither step works on Messenger for Desktop.
![preview1-or8](https://cloud.githubusercontent.com/assets/13304143/13002094/6dc78a18-d174-11e5-8e64-068065f6238e.png)
![preview2-or8](https://cloud.githubusercontent.com/assets/13304143/13002096/7313d85a-d174-11e5-9a47-df36af635ebd.png)

**Comment by specious** [comment]
I think some way of triggering the generation of a preview would be a popular feature.  I, for one, find myself often opening the official client just to send a link as a plain preview.

**Comment by specious** [comment]
As a corollary, sometimes I want to send a URL most definitely without the preview, and would love to know there's a way to prevent it from being generated at all.

Like here:

![url-bundle-with-preview](https://user-images.githubusercontent.com/451178/31401474-f4397514-adc0-11e7-9469-2c2d1cfed520.png)

**Comment by specious** [comment]
@aluxian, maybe this issue should be reopened?
