### ISSUE TITLE
OS X Full Screen

### ISSUE THREAD

**Issue by DanD21** [Aluxian/Messenger-for-Desktop#365]
Full Screen won't work correctly:
1. Can't see the bottom of the app - Dock is over it always
2. Can't see the top bar - can't press the resize button
Overall, can't exit Full Screen Mode!

**Comment by romancement** [comment]
I have the exact same issue and it is driving me insane. I've tried uninstalling and reinstalling the app, no luck.

**Comment by ichbinsteffen** [comment]
+1 
Makes it unusable right now. 
I did go into fullscreen at home in 1920x1080 and opened Messenger somewhere else, where it started as fullscreen app for 1920x1080. Unable to see the bottom. Unable to resize it in any way. 
The app shouldn't start in the last used View-container!

**Comment by Sytten** [comment]
Thanks for reporting.
Please try to use the beta, see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
I will investigate that problem for the future beta releases
