### ISSUE TITLE
SSL support --> https://messengerfordesktop.com/

### ISSUE THREAD

**Issue by UdoKifferbrehl** [Aluxian/Messenger-for-Desktop#383]
Hey there,

what do you think of using SSL for your website https://messengerfordesktop.com/?
You can get free certificates from Let's Encrypt or WoSign. 
Thank you very much 😙

**Comment by groovenectar** [comment]
The downloads are over SSL via GitHub, I'm happy with that. But can look into https://letsencrypt.org/ if investment is an issue...

**Comment by nevercast** [comment]
Another viable option is using someone like CloudFlare. They'll cache your traffic and encrypt free of charge. Provided you fall under their bandwidth constraints. As the downloads are over Github I'd hope you'd not have a problem. (With that said, I am not aware of how much bandwidth you use)
