### ISSUE TITLE
Oversized tray menu on high-DPI Windows

### ISSUE THREAD

**Issue by nclm** [Aluxian/Messenger-for-Desktop#387]
I tried the application on a Windows 10 laptop with a high-DPI display. The contextual menu on the tray icon is oversized:

![Screenshot of a very big menu](https://cloud.githubusercontent.com/assets/923008/14580647/7e05126e-03d4-11e6-85be-3375a8d122d7.png)

The contextual menu in the app itself is fine.

**Comment by MayankXCODER** [comment]
Windows scaling is pathetic.
