### ISSUE TITLE
Unreliable taskbar and system tray indications for unread messeges

### ISSUE THREAD

**Issue by iliyang** [Aluxian/Messenger-for-Desktop#390]
I love this app, it's absolutely brilliant! But I have a small issue with notifications.

I'm running Windows 8.1 64-bit, and I'm seeing some weird behavior from the system tray and chat window title notifications for unread messages. Whenever I receive a new message:
1. The red dot that appears on top of the system tray icon flashes rapidly at some indeterminate rate.
2. The window title starts sporadically alternating between "(1) Messenger" and "Mark messaged you" (a few times a second!).

As a small feature request, when the chat window is open and a new message arrives, would it be possible to also flash the window in the taskbar, similarly to how other apps such as Skype do it? Here's an example (notice the yellow in the taskbar):
![taskbar window flash notification](http://i26.tinypic.com/2zof3bp.png)

And another tiny nitpick: the red dot in the system tray icon could be a little larger.

**Comment by Sytten** [comment]
@nevercast Do we fix that?

**Comment by nevercast** [comment]
This is also a feature request.

**Comment by nevercast** [comment]
I will look in to this :) But it wont be in the next release.
