### ISSUE TITLE
MIT license permits, but prior purchase this license note cannot be read

### ISSUE THREAD

**Issue by gnanet** [Aluxian/Messenger-for-Desktop#391]
See here:
https://apps.ubuntu.com/cat/applications/messenger-desktop/

Also a user has raised voice about this: https://www.facebook.com/help/community/question/?id=10153462970561888

**Comment by gnanet** [comment]
This guy keshavnrj@gmail.com seem to be a copycat who earns money by reusing free works 
found his email here http://www.ktechpit.com/advertisement/

And proven that, he copies everything he can make money of:
His article: http://www.ktechpit.com/ubuntu/things-installing-ubuntu-16-04-lts-xenial-xerus/

The original article:
http://www.webupd8.org/2016/04/things-to-do-after-installing-ubuntu-1604-lts-xenial-xerus.html

And this guy says it is his development:
http://www.ktechpit.com/ubuntu/facebook-app-for-ubuntu-desktop-demo/

> Facebook desktop app using nw.js developed by keshav bhatt.

**Comment by gnanet** [comment]
found him
https://github.com/keshavbhatt?tab=repositories

**Comment by Sytten** [comment]
We will look at this very closely. Thank you very much for your search, I will talk to @Aluxian and @nevercast about it.

**Comment by Aluxian** [comment]
Oh wow @gnanet, splendid investigation! Thanks for reporting this issue. I'll try to report his app in Ubuntu's apps directory and get it removed.

**Comment by nevercast** [comment]
In my experience, Ubuntu have been pretty reasonable with getting stuff taken down. So I hope this is speedy.

**Comment by Aluxian** [comment]
@gnanet How do you know he used my app and not another codebase?

I was just writing the email to Ubuntu and then I took a closer look at the screenshots and I thought about this.

**Comment by gnanet** [comment]
Because i raised the issue, we can check best if i get the app, that pair of bucks will not hurt anymore.

For me the thing is, it looks too similar to be different, and i did not found much other solutions like yours, also his statements how it is done (nwjs) and the fact that i found traces that he copies also publications without declaring source led me to that conlclusion.

**Comment by gnanet** [comment]
I kept my word:

1. I paid for it, Ubuntu software center was unable to download/install the stuff. 
2. I fished out the authenticated link from my syslog, and downloaded the package, the tar.xz and the dsc.


I extracted the application from the DEB, and started it manually, and first thing is **It is unable to connect to the messenger website** :
./messenger-ubuntu-desktop
```
[9439:0523/022252:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[9439:0523/022252:ERROR:process_singleton_posix.cc(253)] readlink(/tmp/.org.chromium.Chromium.3bjeNG/SingletonCookie) failed: Permission denied
ATTENTION: default value of option force_s3tc_enable overridden by environment.
ATTENTION: option value of option force_s3tc_enable ignored.
[9439:0523/022252:ERROR:nss_util.cc(819)] After loading Root Certs, loaded==false: NSS error code: -8018
ATTENTION: option value of option force_s3tc_enable ignored.
ATTENTION: option value of option force_s3tc_enable ignored.
[9439:0523/022252:INFO:native_window_aura.cc(491)] if transparency does not work, try with --enable-transparent-visuals --disable-gpu
[9439:0523/022252:ERROR:nw_shell.cc(335)] TypeError: Cannot set property 'onload' of null
    at file:///tmp/.org.chromium.Chromium.4wKhSK/app.js:73:15
[9439:0523/022252:INFO:CONSOLE(73)] "Uncaught TypeError: Cannot set property 'onload' of null", source: file:///tmp/.org.chromium.Chromium.4wKhSK/app.js (73)
[9439:0523/022252:INFO:native_window_aura.cc(491)] if transparency does not work, try with --enable-transparent-visuals --disable-gpu
[9439:0523/022253:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR

```


So where shall i place and which content for inspection?

**Comment by gnanet** [comment]
The first lines of **app.html** says a lot:
```
<!doctype html>
<html>
  <head>
  <meta charset="UTF-8">
  <title>Welcome Whatsapp-Ubuntu</title>

```

**Comment by gnanet** [comment]
Anyway from view of a USER i could not find a place where i could access the MIT license, or any other license, but the structure and most parts of code seem to resemble the Facebook/Whatsapp codebase i have seen here, for example the context menu is suspicious:

- Reload
- Open Links in the Browser
- Launch on Startup (with lanucher name: 'Unofficial WhatsApp' .... no comment)
- Check for Update on Launch
- separator
- Check for Update (without any url in the manifest this is useless .. no comment again)
- Launch Dev Tools

**Comment by Aluxian** [comment]
I'd ask you to send me the deb but I believe that's against Ubuntu's terms of service. Can you show me the folder structure in the deb? I.e. the folders and the files in them.

**Comment by gnanet** [comment]
I ask myself if sharing the content of /tmp which is not the content of the DEB  i purchased, would violate any terms?

But without sharing the content, i still could give you a complete folder and file list with SHA checksums of the files from the /tmp, which would at least give insight about what was 100% copied, and which files are used if they differ but essentially indicating that it is a copy of your work.

Based on sha1sum i compared the master of Facebook-Messenger-Desktop and WhatsApp-Desktop and found following identical checksums:


Facebook-Messenger-Desktop identical files:

```

./Facebook-Messenger-Desktop/src/themes/dark.css - 17a737fcb150e5b820aaa93361b1c6c7de37851d  ./app-of-keshav-bhatt/themes/dark.css
./Facebook-Messenger-Desktop/src/themes/default.css - d3de3c18cadbe49014eb28cdd3349c13f1505cfa  ./app-of-keshav-bhatt/themes/default.css
./Facebook-Messenger-Desktop/src/themes/mosaic.css - a54d95394544c54bf3b9b624b93cf7748b13c872  ./app-of-keshav-bhatt/themes/mosaic.css
./Facebook-Messenger-Desktop/src/components/themer.js - 9c6356106d33b499cb735ddbb6d6edb862ee44bc  ./app-of-keshav-bhatt/components/themer.js
./Facebook-Messenger-Desktop/src/components/updater.js - c91d46ee32e2934715e6e6b108997ecb3de2c463  ./app-of-keshav-bhatt/components/updater.js
./Facebook-Messenger-Desktop/src/components/dispatcher.js - 159fb67d2993cd6631d2efb168b035931f25154c  ./app-of-keshav-bhatt/components/dispatcher.js
./Facebook-Messenger-Desktop/src/components/notification.js - 3763921730f16996cd08091358ce820a156045ff  ./app-of-keshav-bhatt/components/notification.js
./Facebook-Messenger-Desktop/src/components/utils.js - 6d52d73378e5f41a4ca880d39d1fb3ef4ef02ef8  ./app-of-keshav-bhatt/components/utils.js
./Facebook-Messenger-Desktop/src/components/platform.js - a04b4bfbf9e6dfd6d5753e7a7f5a590c082041b9  ./app-of-keshav-bhatt/components/platform.js

```

Whatsapp-Desktop identical files
```
./WhatsApp-Desktop/src/components/window-behaviour.js - 584008030390b07b65affdb683f9003dda03b4b9  ./app-of-keshav-bhatt/components/window-behaviour.js
./WhatsApp-Desktop/src/components/updater.js - c91d46ee32e2934715e6e6b108997ecb3de2c463  ./app-of-keshav-bhatt/components/updater.js
./WhatsApp-Desktop/src/components/dispatcher.js - 159fb67d2993cd6631d2efb168b035931f25154c  ./app-of-keshav-bhatt/components/dispatcher.js
./WhatsApp-Desktop/src/components/notification.js - 3763921730f16996cd08091358ce820a156045ff  ./app-of-keshav-bhatt/components/notification.js
./WhatsApp-Desktop/src/components/menus.js - b018e78d4f4643b93b51c6d8f4a460cebb8be6da  ./app-of-keshav-bhatt/components/menus.js
./WhatsApp-Desktop/src/components/settings.js - 72860afe77568b32c8a5fe89837a42b69fbef0de  ./app-of-keshav-bhatt/components/settings.js
./WhatsApp-Desktop/src/components/platform.js - a04b4bfbf9e6dfd6d5753e7a7f5a590c082041b9  ./app-of-keshav-bhatt/components/platform.js

```

**Comment by gnanet** [comment]
I found out, that both Messenger and WhatsApp are based on your nwjs-starter so i made also a compare there, result:

```
./nwjs-starter/src/components/updater.js - c91d46ee32e2934715e6e6b108997ecb3de2c463  ./app-of-keshav-bhatt/components/updater.js
./nwjs-starter/src/components/dispatcher.js - 159fb67d2993cd6631d2efb168b035931f25154c  ./app-of-keshav-bhatt/components/dispatcher.js
./nwjs-starter/src/components/platform.js - a04b4bfbf9e6dfd6d5753e7a7f5a590c082041b9  ./app-of-keshav-bhatt/components/platform.js

```

**Comment by Sytten** [comment]
Thats really suspicious... I think we have a pretty good case against this app to report it.

**Comment by gnanet** [comment]
If there is a possibility to look for other apps of the same developer on SoftwareCenter i suggest to check if he also done same with WhatsApp for desktop

**Comment by Sytten** [comment]
@Aluxian dont forget to tell canonical about it

**Comment by Aluxian** [comment]
Tried to contact Ubuntu's app store, nobody replied. I don't feel like following up on this anymore
