### ISSUE TITLE
Title bar

### ISSUE THREAD

**Issue by DotTheI** [Aluxian/Messenger-for-Desktop#400]
Currently the title bar looks like this:
![2016-05-09 9 11 04](https://cloud.githubusercontent.com/assets/10737439/15105003/e53b4a1e-15ce-11e6-820a-ca91e1f17a0f.png)
Would love to see the title bar gone so that it looks like this (taken from Goofy):
![2016-05-09 9 10 28](https://cloud.githubusercontent.com/assets/10737439/15105019/fb146f8c-15ce-11e6-9ca7-2414cba3353c.png)

Also the window can be reduced to this:
![2016-05-09 9 11 31](https://cloud.githubusercontent.com/assets/10737439/15105030/0893cd06-15cf-11e6-900a-9fe8682f7d65.png)
It shouldn't be like that.

**Comment by Sytten** [comment]
Handled in my fork

**Comment by DotTheI** [comment]
@Sytten Just installed 1.4.7. The title bar is there as well. Am I missing something?

**Comment by Sytten** [comment]
Was talking about your second point. The first point is impossible to do with the current framework...

**Comment by Sytten** [comment]
@nevercast If you agree its a wontfix for me

**Comment by nevercast** [comment]
I'll mark this as investigation for now with no milestone. It looks like it's currently not achievable with the current framework. But I wont rule it out without checking first.

**Comment by Aluxian** [comment]
It's possible with Electron, but it should be a setting, disabled by default.
