### ISSUE TITLE
NWJS 0.13 Adds Window persistence.

### ISSUE THREAD

**Issue by nevercast** [Aluxian/Messenger-for-Desktop#411]
- There is an id to identify each window. This will be used to remember the size and position of the window and restore that geometry when a window with the same id is later opened. It could be specified in Window.open or id of window subfields in manifest

http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

Consider removing our own settings implementation.

**Comment by nevercast** [comment]
I'm going to focus on getting our settings implementation to work since it's used for more than just window locations. 

They are currently broken due to cross-context manipulation.

**Comment by Sytten** [comment]
Should be handle automatically now no?
