### ISSUE TITLE
DevTools seems jailed, no components.

### ISSUE THREAD

**Issue by nevercast** [Aluxian/Messenger-for-Desktop#413]
With 0.13 and 0.14 of nwjs, It now uses Chrome Extensions. This change has caused require() to work differently. `components/*` has since disappeared from DevTools.

I'd like it to come back.

**Comment by Sytten** [comment]
When you right click on the page you can have another devtool where the components are there. However the right-click is disabled in the code. Commenting the line 62 should do the trick: https://github.com/Aluxian/Facebook-Messenger-Desktop/blob/V1.5.X/src/app.js
