### ISSUE TITLE
Cant uncheck MenuItem with code on linux

### ISSUE THREAD

**Issue by Sytten** [aluxian/Messenger-for-Desktop#416]
Its working great on Windows, but not on linux.

![screenshot from 2016-05-16 22 10 48](https://cloud.githubusercontent.com/assets/2366731/15310092/b4b75468-1bba-11e6-8fba-6b69a187e774.png)

**Comment by nevercast** [comment]
I believe you said you wanted this one, so I've assigned you. Feel free to assign me if you've not the time.

**Comment by Sytten** [comment]
I will try to fix it, but feel free to have a look (on linux :P)

**Comment by nevercast** [comment]
I'll install a virtual machine.

**Comment by Sytten** [comment]
Lets say we will fix that later, not a big deal for now
