### ISSUE TITLE
Doesn't scale to HIDPI

### ISSUE THREAD

**Issue by thorhop** [Aluxian/Messenger-for-Desktop#42]
The WebKit won't scale - perhaps either using `@media screen and (YxX)` or setting the `device-pixel-ratio` of the webkit runtime. In any case, I run on **3200x1800** and I need **2.0** pixel ratio for it to scale properly. Any tips on getting it set up quickly?

**Comment by Aluxian** [comment]
[Here](http://peter.sh/experiments/chromium-command-line-switches/) I found [--ash-host-window-bounds](http://peter.sh/experiments/chromium-command-line-switches/#ash-host-window-bounds) and [--force-device-scale-factor](http://peter.sh/experiments/chromium-command-line-switches/#force-device-scale-factor) which I could pass to Chromium, I'll try on Tuesday or Wednesday.

**Comment by Aluxian** [comment]
I tried them today, but `window.devicePixelRatio` is always 2 on my machine. In `package.json` I tried setting `chromium-args` to these values:

    "chromium-args": "--device-scale-factor=3"
    "chromium-args": "--device-scale-factor 3"
    "chromium-args": "--force-device-scale-factor 3"

Nothing worked or changed anything. Actually, I tried another user-agent string and the website looked different, I'm not sure what changed. Can you try adding `"user-agent": "%name %ver %nwver %webkit_ver %osinfo"` to `./src/package.json`, build them app and see if anything changes?

**Comment by thorhop** [comment]
So I added the user agent thingy to ./src/package.json - and nothing changed. I even tried your former attempt, but neither yielded any fruit I'm fraid :/ I got the package building process ready for testing, so let me know what other things I could try. 

Cheers!

**Comment by mcanders** [comment]
running 'messengerfordesktop --force-device-scale-factor=2' from the terminal scales assets properly

**Comment by mcanders** [comment]
But some images are lower resolution so they appear fuzzy when scaled up

**Comment by Aluxian** [comment]
Nice find! I'll check it out when I get home.


--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On Wed, Jun 03, 2015 at 5:11 am, mcanders < notifications@github.com [notifications@github.com] > wrote:
running 'messengerfordesktop --force-device-scale-factor=2' from the terminal
scales assets properly

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/42#issuecomment-108162079] .[https://github.com/notifications/beacon/ABWmdoaC9gsad4ldw9LkGDrC3t08rPx1ks5oPlnCgaJpZM4EDzZQ.gif]

**Comment by umpirsky** [comment]
`messengerfordesktop --force-device-scale-factor=2` worked for me. Would be nice to support it out of the box.

**Comment by dcrystalj** [comment]
umpirsky thank you! works nice on my obuntu 15.10 and yoga 2 pro
