### ISSUE TITLE
OS X: Portrait external monitor and Window placement

### ISSUE THREAD

**Issue by borgand** [Aluxian/Messenger-for-Desktop#427]
I have multiple external monitors on my MacBook Pro (**OS X 10.11.5**), one in landscape and other in portrait and usually the lid is closed.

When I use Messenger on the non-primary external monitor (portrait) and then disconnect the monitors, all other application's windows are gathered to the MacBook Pro's internal display, but not the Messenger.
When I use Exposé to see all windows, I see the Messenger's window, but clicking on it, it moves out of the lower bounds of the viewable area.

Probably the Y coordinate of the window stays from the Portrait monitor and is not reset to actual viewable area when displays are disconnected.

**Comment by Sytten** [comment]
This is very specific issue... Next version will be out soon, I would like you to test it again then. Thanks
