### ISSUE TITLE
New messages

### ISSUE THREAD

**Issue by cdbjr** [aluxian/Messenger-for-Desktop#433]
For myself, I would like the app to open new messages when received. Or perhaps make it a choice in settings

**Comment by rikai** [comment]
This request doesn't seem very clear to me at all, could you explain more in depth what you mean?

**Comment by cdbjr** [comment]
If you know Apple Messages, when a new message is received, the app message window will open on the desktop. That would work best cross-platform.

As a thought only, with OS X, you have the ability to have notifications appear on screen when new messages are received, like the attached settings image

**Comment by Sytten** [comment]
Maybe in a future release

**Comment by cdbjr** [comment]
Of course it might be a future version any change is made to. I would like to suggest something else to be considered.

If using cmd-Q to close the window, the whole app quits. 1) The shortcut is not shown as an option in the menu list 2) I, myself, would prefer if I use cmd-Q it just close the window and not quit the whole app and leave that to choosing it from the menu bar icon. I know this is one of those some like one way and some another.

I do realize that cmd-W will close the window now that I have looked for it

**Comment by Sytten** [comment]
It should be easy to handle, just have to intercept the shortcut. So many things to do right now...

**Comment by cdbjr** [comment]
I understand entirely and there are just suggestions

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

You can run the app in tray mode.
