### ISSUE TITLE
The top bar of the app is hidden by the OS top bar in OS X

### ISSUE THREAD

**Issue by jaxon58** [Aluxian/Messenger-for-Desktop#437]
Happened on first launch after a restart. I am using multiple displays, moving the app around displays with mission control doesn't help. It means that you cant move the app around the screen anywhere or use the x - + buttons.

Thanks.

<img width="468" alt="screen shot 2016-06-06 at 11 14 52 am" src="https://cloud.githubusercontent.com/assets/1647753/15809617/f2b9511c-2bd7-11e6-8c2e-2ff1d689c817.png">

**Comment by Sytten** [comment]
Try to remove the application and delete the cache/config folder. That should reset the whole thing.

**Comment by jaxon58** [comment]
Hi,

Yes doing a clean install fixed the problem.

The problem is this keeps happening, reinstalling the app every time I want to use it isn’t a great solution.

Is there any chance you’ll actually fix this bug?

Cheers,
Jaxon

**Comment by Sytten** [comment]
It will be fixed in the V2 probably.
@Aluxian check this out :)

**Comment by Aluxian** [comment]
I can't say whether it'll be fixed because Electron is a different platform and I don't know the low-level differences between the 2. But I guess it will be.
