### ISSUE TITLE
Unable to reply messages - 4K monitor on 15 inch laptop

### ISSUE THREAD

**Issue by bobnerland** [aluxian/Messenger-for-Desktop#438]
![4k](https://cloud.githubusercontent.com/assets/15942824/15961042/e96be40c-2f02-11e6-9084-b49149f3891c.PNG)

**Comment by bobnerland** [comment]
![messenger2](https://cloud.githubusercontent.com/assets/15942824/15961101/435c7c9c-2f03-11e6-9014-f24e9952c56e.PNG)

**Comment by Sytten** [comment]
Since @nevercast and I dont have a 4K its really hard for us to debug that problem. Scaling is one issue that we face and we hope to resolve it by the release 1.5.0 or before if possible...

**Comment by Sytten** [comment]
V1 not supported anymore
