### ISSUE TITLE
Sound recordings won't play

### ISSUE THREAD

**Issue by ekolis** [Aluxian/Messenger-for-Desktop#448]
If I receive a sound recording and try to play it back, nothing happens but a spinning circle.

**Comment by Sytten** [comment]
This is known, will be resolved in V1.4.9

**Comment by ekolis** [comment]
Thank you very much! I didn't think this app was still under development,
but I figured it wouldn't hurt to file an issue...

**Comment by MarcinWieczorek** [comment]
@ekolis There are other branches which are updated daily.

**Comment by ekolis** [comment]
Oh, interesting! Where can I find those, and will I need to build from
source?

**Comment by MarcinWieczorek** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/tree/V1.4.X
https://github.com/Aluxian/Facebook-Messenger-Desktop/tree/V1.5.X

Sytten says we should use 1.5.X despite the fact the latest version is 1.4.8 and there is only newer tag which is a beta version (v1.5.0-beta.0). You can build the app with instructions provided in README. If you're still having trouble please join gitter: https://gitter.im/Aluxian/Facebook-Messenger-Desktop

**Comment by Sytten** [comment]
Thanks @MarcinWieczorek

**Comment by Sytten** [comment]
I'm trying to write a gulp plugin to replace the dll/so file. Meanwhile if you want sound you can replace the librairie yourself: https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases
We use NWJS v0.12.3

**Comment by Sytten** [comment]
Ok I manually replaced the files and it works for now.
I don't have the time to make a script so I will keep it open and move it to the next release.
