### ISSUE TITLE
Have a zoom feature 

### ISSUE THREAD

**Issue by ooker777** [Aluxian/Messenger-for-Desktop#450]
In the webpage version, I can zoom it. The font size is easier to read than ever. I have tried to look at the devtool, but I can't find where the font-size tag locates. I'm still novice. 
### Normal font-size

![2016-06-18 13_58_15-messenger](https://cloud.githubusercontent.com/assets/6695517/16169533/c78b7b26-355c-11e6-8692-26d0aa832a2a.png)
### Larger font-size

![2016-06-18 13_27_16-messenger](https://cloud.githubusercontent.com/assets/6695517/16169518/59802ad2-355c-11e6-82ed-27686be40597.png)

**Comment by Sytten** [comment]
@ooker777 How do you usually zoom on the browser, I need an idea for the implementation

**Comment by ooker777** [comment]
I just zoom it as usual: <kdb>ctrl++</kdb>. You can also enlarge the font size. 

Ooker.




On Tue, Jun 28, 2016 at 8:03 AM +0700, "Émile Fugulin" <notifications@github.com> wrote:












@ooker777 How do you usually zoom on the browser, I need an idea for the implementation

**Comment by Sytten** [comment]
Good thank you!

**Comment by manfreed** [comment]
Also one might use Ctrl+Mouse wheel to zoom. When we are talkin about zoom in the browser everything on the page get's bigger proportionally, not just the text. However in this case a simple bigger+smaller chat text option would suffice.
