### ISSUE TITLE
More noticeable visual notifications.

### ISSUE THREAD

**Issue by mzso** [Aluxian/Messenger-for-Desktop#457]
Hi!

I think the visual notifications are not quite enough. There's only something like tiny a red exclamation mark in the bottom right corner.

I think these might be more useful:
- Add open the window (in the background to be not to obtrusive) and flash the taskbar button.
- Flash the notification are icon continuously. (Might not be as noticeable, but still a lot better)

**Comment by Sytten** [comment]
Flashing the notification is annoying so I wont do that.
As for open the window that would probably be something I could do, but I don't think I have the option to choose where the window appears.

Also you should have a native notification appearing. Those will be changed for chrome-like notifications eventually.

**Comment by mzso** [comment]
[**@Sytten**](https://github.com/Sytten) commented on [2016. jún. 26. 13:55 CEST](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/457#issuecomment-228597668 "2016-06-26T11:55:27Z - Replied by Github Reply Comments"):
> Flashing the notification is annoying so I wont do that.  
> 
> As for open the window that would probably be something I could do, but I don't think I have the option to choose where the window appears.

You mean the icon? I don't think it's bothersome due to it's small size and out-of-the way nature. (It could be optional)
Flashing the taskbar button on the other hand is kind of the standard way to bring attention. (You obviously need to open the window for that.)


[**@Sytten**](https://github.com/Sytten) commented on [2016. jún. 26. 13:55 CEST](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/457#issuecomment-228597668 "2016-06-26T11:55:27Z - Replied by Github Reply Comments"):
> Also you should have a native notification appearing. Those will be changed for chrome-like notifications eventually.

What does "native notification" and "chrome like" notification mean. I don't use chrome much, "native" can mean many things. Including the notification area ballon popups which are really annoying.

**Comment by Sytten** [comment]
The taskbar button should be changing name. I removed the flashing icon, but I could add it as an option later.

Native notification is different depending on your system, on yours its probably the balloon pop-up yes. Chrome notification is a white rectangle usually in some corner of the screen.

**Comment by ekolis** [comment]
On Windows 10 it's a gray box in the corner that disappears after a user-configurable amount of time; on previous versions it's a beige balloon that stays there until you dismiss it (is there a way to dismiss it  without actually opening it?)

**Comment by Sytten** [comment]
ekolis, I think its an option.
I would need to double check with the NWJS documentation though, I'm not sure...

**Comment by mzso** [comment]
[**@Sytten**](https://github.com/Sytten) commented on [2016. jún. 26. 13:55 CEST](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/457#issuecomment-228597668 "2016-06-26T11:55:27Z - Replied by Github Reply Comments")
> Also you should have a native notification appearing. Those will be changed for chrome-like notifications eventually.

I don't know what the chrome-like notification would be like. (probably annoying) But the horrible ballons I disable immediately after I installed windows.

**Comment by mzso** [comment]
[**@ekolis**](https://github.com/ekolis) commented on [2016. júl. 4. 15:38 CEST](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/457#issuecomment-230292906 "2016-07-04T13:38:48Z - Replied by Github Reply Comments"):
> On Windows 10 it's a gray box in the corner that disappears after a user-configurable amount of time; on previous versions it's a beige balloon that stays there until you dismiss it (is there a way to dismiss it  without actually opening it?)

Are they still in win 8.1? I don't remember disabling them, but I also didn't get any of them.

**Comment by mzso** [comment]
[**@Sytten**](https://github.com/Sytten) commented on [2016. jún. 26. 13:55 CEST](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/457#issuecomment-228597668 "2016-06-26T11:55:27Z - Replied by Github Reply Comments"):
> Flashing the notification is annoying so I wont do that.  

Actually it's a matter of preference. Some might want a strong visual indicator to be certain to not miss a message instead of a sound that lasts for a fraction of a second.

**Comment by Sytten** [comment]
I agree we can make this a setting, I'm really busy right now with school but I will do my best to make it happen.

**Comment by zackexplosion** [comment]
In OSX just like LINE and slack with a red dot on dock, it will be better.

![image](https://cloud.githubusercontent.com/assets/5180966/16712107/1f5f5b3a-46ae-11e6-8018-5b03d30d098a.png)

**Comment by randalvance** [comment]
+1 on the flashing taskbar notification. I don't sometimes here headphones so I won't know if there is a new message.

**Comment by Aluxian** [comment]
There's a dock badge now.
