### ISSUE TITLE
[v1.5.0-beta.0] Disable the right click

### ISSUE THREAD

**Issue by Sytten** [Aluxian/Messenger-for-Desktop#459]
Forgot to disable it before release.
Just need to uncomment line 62 of https://github.com/Aluxian/Facebook-Messenger-Desktop/blob/V1.5.X/src/app.js

**Comment by skyli91** [comment]
Why disable it? Now i can right click - paste to the textfield and also right click - delete messages.

**Comment by Sytten** [comment]
From what I remember the right give access too other features that we don't necessarily want end users to see (but maybe I did disable that, I need to check) :)

**Comment by Sytten** [comment]
![screenshot from 2016-06-28 22 20 00](https://cloud.githubusercontent.com/assets/2366731/16438529/a05b41e2-3d7e-11e6-9817-5928ffa1553f.png)

@skyli91 What do you think of that?
I can more options if needed

**Comment by skyli91** [comment]
looks good :) just make sure deleting messages will still work
![image](https://cloud.githubusercontent.com/assets/7442913/16445456/119b33d0-3de3-11e6-9588-bbe514159cfa.png)

**Comment by Sytten** [comment]
It still, but the context menu appears over it... I think I will prevent the delete button from appearing and move its logic to our context menu.
