### ISSUE TITLE
Hot keys

### ISSUE THREAD

**Issue by Nifled** [Aluxian/Messenger-for-Desktop#477]
Something similar was asked a relatively long time ago, but not in detail. There should be key shortcuts to do all the general stuff like cycle through conversations, create a new message, find a message/conversation/person, etc. I think this would make the app complete, as hot keys are a necessary convention.

**Comment by Sytten** [comment]
Yes, we have PR for this.
I need to test it and integrate it.
It will be in the next beta release :)

**Comment by dufferzafar** [comment]
Also for https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/257

**Comment by Nifled** [comment]
Great, thanks!

**Comment by Nifled** [comment]
Great, thanks!

**Comment by Sytten** [comment]
PR not working, I will have to work on it.
It will be for the next release.

**Comment by henriqueiv** [comment]
Hot key for reload the page would be nice!
