### ISSUE TITLE
`CTRL + Enter` or `Alt +Enter` to send message....

### ISSUE THREAD

**Issue by 4evermaat** [Aluxian/Messenger-for-Desktop#480]
I noticed that when I press `enter`, it sends the message.  But I want option to use `CTRL + Enter` or `ALT + Enter` to send message.  This way, I can type several paragraphs without having to send the message accidentally.

Skype, LINE, and other chat programs have implemented this.  Screenshot proof.
![skype option to send line break vs send message](https://cloud.githubusercontent.com/assets/830306/16789251/21824c4a-48d6-11e6-9a63-b15d5927f966.gif)
![line option to send line break vs send message](https://cloud.githubusercontent.com/assets/830306/16789322/d92e77ba-48d6-11e6-97df-b67949abb0d2.gif)

**Comment by Sytten** [comment]
Yeah it has been already requested. Might add it with the shortcuts issue later on.

**Comment by 4evermaat** [comment]
so @Sytten @aluxian, did you add the feature or not?

**Comment by Aluxian** [comment]
I think it's better to keep it simple. You can insert new lines using shift+enter or ctrl+enter in Messenger.
