### ISSUE TITLE
[MAC OS X, El Capitan] Application won't show buttons for Exit/Minimize/Fullscreen

### ISSUE THREAD

**Issue by CubicProgramming** [Aluxian/Messenger-for-Desktop#491]
<img width="668" alt="screen shot 2016-07-22 at 10 30 36 pm" src="https://cloud.githubusercontent.com/assets/20539793/17076028/49f75a16-505c-11e6-86df-c67f4d46dc63.png">
<img width="968" alt="screen shot 2016-07-22 at 10 30 50 pm" src="https://cloud.githubusercontent.com/assets/20539793/17076029/4a15d25c-505c-11e6-90d4-8872fe597bd5.png">

This issue appeared when I full-screened an application, and dragged Messenger onto the same "Space," splitting the newly created "Fullscreen" tab into two parts: One for messenger and the other for the other app. When I tried to revert Messenger back to its original, Desktop configuration, I realized that I couldn't find the close/minimize/fullscreen buttons anywhere!

**Comment by Sytten** [comment]
Yes its known issue. Will be fixed in a beta soon. 
Are you using the latest stable or the latest beta?

**Comment by CubicProgramming** [comment]
Sorry about that! Must have overlooked it while browsing the issues list!

I'm using the one on the front page of messengerfordesktop.com (which I'm assuming is the latest stable)

**Comment by Sytten** [comment]
Yes probably the latest stable.
Right now I don`t know how to fix this really and the V2 (based on another framework) will be out sometime in august I think so it will be fixed then.
