### ISSUE TITLE
Emojis from "Command + Control + Spacebar" shortcut not showing up on Messenger

### ISSUE THREAD

**Issue by dnamorim** [aluxian/Messenger-for-Desktop#493]
When i try to add a emoji from the Cmd+Ctrl+Space emoji shortcut on Mac OS X 10.11.6, the emoji symbol does not show up. I need to copy the emoji from another app and paste it into the app. Tested with the last stable version available on your page app.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
