### ISSUE TITLE
Ubuntu Gnome Notifications

### ISSUE THREAD

**Issue by mantasjk** [Aluxian/Messenger-for-Desktop#494]
Previous versions of the messenger had message notifications integrated into Ubuntu Gnome 3.20 (looked like all system notifications), while the new version shows notifications as if I were using fb.com on Chrome browser. They don't look as good and breaks overall vibe.

**Comment by cassiodoroVicinetti** [comment]
https://github.com/nwjs/nw.js/issues/4560#issuecomment-240387166
