### ISSUE TITLE
Wasting all free space on drive C

### ISSUE THREAD

**Issue by mzso** [Aluxian/Messenger-for-Desktop#495]
Facebook messenger wasted all free space by creating a 110MB folder every day, and half the time multiple times a day (every program start?) in the temp folder. Today I was greeted with crashing programs because of the zero disk space remaining.

![nw-fbm](https://cloud.githubusercontent.com/assets/4479090/17132037/4e210d28-5320-11e6-846d-8d8048b42bd1.png)

PS: Even deleting it takes a while, 116000+ files...

**Comment by Sytten** [comment]
I checked on my desktop and I have 5-6 different folders for nwjs. It seems to replicate itself in the temp folder which is not a normal behavior. Are you on Windows 10?

**Comment by Sytten** [comment]
Its actually supposed to delete the folder when closing, I don`t know what went wrong in you system... Maybe a setting prevent it from removing files in the temp directory...

**Comment by mzso** [comment]
[**@Sytten**](https://github.com/Sytten) commented on [2016. júl. 28. 00:44 CEST](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/495#issuecomment-235744461 "2016-07-27T22:44:16Z - Replied by Github Reply Comments"):
> I checked on my desktop and I have 5-6 different folders for nwjs. It seems to replicate itself in the temp folder which is not a normal behavior. Are you on Windows 10?

I'm on win8.1.

[**@Sytten**](https://github.com/Sytten) commented on [2016. júl. 28. 00:47 CEST](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/495#issuecomment-235745089 "2016-07-27T22:47:30Z - Replied by Github Reply Comments"):
> Its actually supposed to delete the folder when closing, I don`t know what went wrong in you system... Maybe a setting prevent it from removing files in the temp directory...

I changed nothing of the sort. I did morve the location of the temp folder though. But that shouldn't be a problem if you use %temp% properly

**Comment by Sytten** [comment]
Actually its the framework we use that takes care of deleting the files after, so its probably a bug in that framework which doesnt support the move of the temp folder.
It would be interesting to test it with the latest framework version and report the bug if necessary.

**Comment by mzso** [comment]
[**@Sytten**](https://github.com/Sytten) commented on [2016. júl. 29. 05:25 CEST](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/495#issuecomment-236085665 "2016-07-29T03:25:13Z - Replied by Github Reply Comments"):
> Actually its the framework we use that takes care of deleting the files after, so its probably a bug in that framework which doesnt support the move of the temp folder.  
> 
> It would be interesting to test it with the latest framework version and report the bug if necessary.

Well, some way of dealing with it would be nice. It's rather annoying that it keeps eating up space.

**Comment by Sytten** [comment]
I reported it to the dev.
Since we are moving to an electron based software, that might resolve the issue.
