### ISSUE TITLE
Close Directly Option

### ISSUE THREAD

**Issue by Kharmium** [Aluxian/Messenger-for-Desktop#497]
Hello, I'm not a programmer but thanks for the great work.

I'd like to know if there's a way to close the program directly instead of minimizing it to tray. I've searched for it but just don't see it. (Request maybe? hehe)

I know this is Messenger for Desktop but also can't find such option on Whatsapp for Desktop.

Thanks in advance for your help :)

**Comment by Sytten** [comment]
That would be a nice option.
