### ISSUE TITLE
Notifications on the desktop and dual-monitor

### ISSUE THREAD

**Issue by ForumLiker** [aluxian/Messenger-for-Desktop#499]
Hi. I have two monitors. Primary and secondary. The notification displayed on a secondary monitor that is disabled. 
Archlinux. DE: Cinnamon 3.0.7. Messenger 1.5.0.beta 1

**Comment by Sytten** [comment]
Thats probably a setting on your side. The notification always display in the primary monitor as set in your settings.
There is nothing we can do for you.

**Comment by ForumLiker** [comment]
the same problem and Skype. because the the notification is not displaying means of DE

**Comment by Sytten** [comment]
Sorry to tell you but your sentence makes no sense...
Cinnamon probably as a setting to specify which screen to use when displaying notifications.

**Comment by ForumLiker** [comment]
![2016-08-06 20-18-20](https://cloud.githubusercontent.com/assets/11502792/17458192/39790dde-5c13-11e6-9a7b-52906c982024.png)
![2016-08-06 20-20-00](https://cloud.githubusercontent.com/assets/11502792/17458194/3f22aa92-5c13-11e6-906a-626c20f76637.png)

**Comment by Sytten** [comment]
V1 not supported anymore
