### ISSUE TITLE
Typing dots get pushed into a breakline

### ISSUE THREAD

**Issue by AliasDidge** [aluxian/Messenger-for-Desktop#508]
This is what the issue looks like if the window is a certain size. Only happens when the window is small and not large. 
![capture](https://cloud.githubusercontent.com/assets/8867407/17721633/bbcca668-63f9-11e6-966b-7c3497c9efce.JPG)

**Comment by Sytten** [comment]
Yes I noticed that also, I will need to check the css for that.
Thanks for reporting!

**Comment by AliasDidge** [comment]
You're welcome! Hope it gets fixed.



On Mon, Aug 22, 2016 at 9:20 AM -0400, "Émile Fugulin" <notifications@github.com> wrote:












Yes I noticed that also, I will need to check the css for that.

Thanks for reporting!

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?
