### ISSUE TITLE
Small sliver of sidebar still visible when "hide sidebar" enabled for OSX

### ISSUE THREAD

**Issue by ShahrumAmiri** [aluxian/Messenger-for-Desktop#512]
When "Auto-Hide Sidebar" is enabled for the OS X version, a tiny sliver of the sidebar is still shown, regardless of window/screen size.

<img width="151" alt="messenger_and_new_issue_ _aluxian_facebook-messenger-desktop" src="https://cloud.githubusercontent.com/assets/16479237/17812268/4c051390-65f4-11e6-9a91-2ef8751e52c3.png">

**Comment by Sytten** [comment]
Thanks for reporting, we will fix it :)

**Comment by aluxian** [comment]
Tracked here: https://github.com/aluxian/Messenger-for-Desktop/issues/512
