### ISSUE TITLE
Clicking "beta" on the update preferences unchecks "stable" but does not check "beta"

### ISSUE THREAD

**Issue by ekolis** [aluxian/Messenger-for-Desktop#517]
Not sure if it's a graphical glitch or I actually disabled all updates whatsoever...

This is v1.5.0b1 on Windows 10.

**Comment by Sytten** [comment]
Ho, thats true. Thats probably just a graphical glitch.

**Comment by Sytten** [comment]
Yep just a graphical glitch, its working on linux.
Meanwhile the dev on branch V1.5.X will continue on my fork only.

**Comment by Sytten** [comment]
V1 not supported anymore
