### ISSUE TITLE
[2.0.0-beta] Menu bar and tray icon menu are inconsistent (they have different subsets of functionality), and there's no way to restore the menu bar once it's hidden

### ISSUE THREAD

**Issue by ekolis** [aluxian/Messenger-for-Desktop#527]
Thus removing some functionality...

**Comment by Sytten** [comment]
Thats a problem.
Thanks for reporting
@Aluxian

**Comment by aluxian** [comment]
Assuming this is Windows.

The menu bar can be toggled with the kb shortcut. Also, if you restart the app it'll come back.
