### ISSUE TITLE
Right-click menu disabled due to Javascript error in chat window

### ISSUE THREAD

**Issue by ekolis** [aluxian/Messenger-for-Desktop#528]
![image](https://cloud.githubusercontent.com/assets/2612506/18022886/f425bbc0-6bc0-11e6-8c0f-03110fe26590.png)

**Comment by Sytten** [comment]
Yes we are aware! Thanks
@Aluxian

**Comment by aluxian** [comment]
In the new versions I temporarily disabled this until we fix it.

**Comment by aluxian** [comment]
Added back in 2.0.7, will reopen if the error pops up again.
