### ISSUE TITLE
[2.0.0] Text box for typing messages in is too small

### ISSUE THREAD

**Issue by ekolis** [aluxian/Messenger-for-Desktop#529]
I don't think it's a Facebook issue because it was bigger in 1.5.0. Now it's on the same line with the emoji buttons and such; they used to be on their own line.

**Comment by Sytten** [comment]
Thanks for reporting
@Aluxian

**Comment by aluxian** [comment]
I think it's back to full width now? Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?
