### ISSUE TITLE
[2.0.0] Windows vertical scrollbars if I make the window bigger than smaller

### ISSUE THREAD

**Issue by ekolis** [aluxian/Messenger-for-Desktop#530]
These aren't the chat scrollbars; they're the Windows scrollbars. I would attach a screenshot but I already reinstalled 1.5.0!

**Comment by Lubieerror** [comment]
This same bug :( 
![gith](https://cloud.githubusercontent.com/assets/11427815/18034568/8961c4ec-6d40-11e6-9f48-9bbc79609b90.png)

**Comment by Sytten** [comment]
Thanks for reporting 
@Aluxian

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?
