### ISSUE TITLE
2.0 Installer is nasty

### ISSUE THREAD

**Issue by mzso** [aluxian/Messenger-for-Desktop#533]
- It doesn't show any options. It appears to the user that this is the program executable
- It automatically installs into into a folder not shown, and undesired.
- It creates a start menu folder without asking, or even telling you about it. It's a uninformative "Alexandru Rosianu" folder.
- It doesn't deal with the <v2 messenger.

**Comment by Sytten** [comment]
Thanks for reporting
@Aluxian

**Comment by aluxian** [comment]
- i can't customise the installer and I don't want to change the framework (also, i agree with the current design)
- start menu folder changed to MFD
