### ISSUE TITLE
Top of the Window Black Notification

### ISSUE THREAD

**Issue by szekeres2016** [Aluxian/Messenger-for-Desktop#534]
Since I use older Android devices with low resources I don't have the mobile version of messenger installed. Because of this the web and this version puts a quite noticeable reminder about the fact I should totally download it to my device. There is no way to remove it on the web version so I was hoping for a solution to this in this application. Also there seems to be no tray icon anywhere on ubuntu 16.04. Great application once the bugs are gone!

![kepernyokep 2016-08-29 22-00-20](https://cloud.githubusercontent.com/assets/20751590/18065661/25de3c66-6e35-11e6-8e79-737ad499427a.png)

**Comment by Sytten** [comment]
This software is a just a webwrapper for the messenger.com website.
That being said, its just html behind the scene so its totally possible to remove that banner.
I will add it to the todo list.

**Comment by Sytten** [comment]
As for the tray icon, we have a hard time making it work on android. An update of NWJS is necessary, but I haven't had the time yet.

**Comment by Aluxian** [comment]
I fixed this, I don't think it's pushed to develop yet.

**Comment by szekeres2016** [comment]
Wow awesome, thank you! :)

**Comment by AncientRepositoryOfKnowledge** [comment]
Issue still present as of 12/09/2016 using v2.0.1beta.

**Comment by Aluxian** [comment]
Thanks for letting us know, we'll check again... it seems our fix didn't work.

**Comment by nistath** [comment]
#1165 works for me.

**Comment by Sytten** [comment]
Yes, but it will pop-up again if they change the variable name which happens all the time :)

**Comment by nistath** [comment]
It's been the same


________________________________

**Comment by nistath** [comment]
It's been the same for the past couple of months, so I don't see why not. CSS is CSS and they won't be changing that banner soon.
