### ISSUE TITLE
When i am clicking the right mouse button in the applicat...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#535]
**Description:**
When i am clicking the right mouse button in the application is shows:
Java Script Error in the main process
Error: Attempting to call a function in the renderer that has been closed or released.
Function provided here: Object.<anonymous>

...(it has more)...

**Steps to reproduce:**
When i am clicking the right mouse button in the application

**App version:**
2.00 beta

**OS:**
Windows 10 64-bit

**Works in WhatsApp Web:**

**Extra:**
Also the menu with the friend was hiding, now this function is gone. Can you take it back?

**Comment by Sytten** [comment]
Thanks for reporting
@Aluxian
