### ISSUE TITLE
Switch chat windows with ⌘+1,2,3...

### ISSUE THREAD

**Issue by eoger** [aluxian/Messenger-for-Desktop#540]
I can do it on Firefox, Textual and WhatsApp, it would be great to have it here too!

**Comment by Sytten** [comment]
Thanks for the suggestion!

**Comment by aalvarado** [comment]
wasn't this already in the app?

**Comment by Sytten** [comment]
Maybe I have not tested it

**Comment by aluxian** [comment]
Fixed in 2.0.7 (will be released soon)
