### ISSUE TITLE
[2.0] Feature Request: Option to disable 'seen' receipts.

### ISSUE THREAD

**Issue by lilchancep** [Aluxian/Messenger-for-Desktop#542]
A lot of my friends use it and i can see how it would be helpful to a lot of people. there are chrome extensions for it ( im under the assumption this is still a chrome wrapper). i have no idea how hard it would be to implement this

**Comment by Osyx** [comment]
The new update has this: If you go to Facebook > Block seen/typing indicators, you can enable it there.

**Comment by Sytten** [comment]
I think he is requesting it for the V2. It will be done after the critical bugs are fixed.
@Osyx 
@lilchancep

**Comment by Osyx** [comment]
@Sytten Ah sorry, you're right.

**Comment by ktsarlz** [comment]
What version did the block seen appear?

**Comment by Sytten** [comment]
V1.5.0

**Comment by GAMELASTER** [comment]
Planning to implement in 2.0? It will be really useful!
