### ISSUE TITLE
custom endpoint urls

### ISSUE THREAD

**Issue by swarupsengupta** [aluxian/Messenger-for-Desktop#543]
i have a different domain i need to connect to instead of facebook.com, eg:- xyz.facebook.com
is it possible to do that?

**Comment by Sytten** [comment]
For now it is not from us, the URL is embedded in the html page that is loaded.
But I guess you could change the URL by unpacking the app and repacking it.

**Comment by swarupsengupta** [comment]
yep that i could, i mean unpacking, changing endpoint and then repacking
the problem is that they havent opened up their apis for custom facebook domains (enterprise accounts)
it seems the enterprise product itself is still in beta, thats why they havent opened up all their apis
they will be coming up with full fledged desktop apps once the product goes out of beta

**Comment by Sytten** [comment]
Not sure if you are talking about facebook or MFD here^^
I am the maintainer of the V1 and I can tell you that the software is just a webwrapper so you can put the URL you want and it will display it :)
