### ISSUE TITLE
(beta 2.0.0) Can't add to Plank Dock (again?) and icon is weird.

### ISSUE THREAD

**Issue by Frantik02** [aluxian/Messenger-for-Desktop#547]
So I downloaded beta 2.0.0 and right off the bat the "Keep in Dock" option for my Plank Dock is not present. Again. I say again because when the _app.html_ thing happened, the updates fixing that issue either wouldn't allow me to dock the app or would allow me to dock the app but with a duplicate icon. V 1.5.0 solved this issue entirely. However, if I attempt to go back to 1.5.0, the "Keep in Dock" option is not present. I tried many things, modified various files, and now opening 1.5.0 displays an njws error. I'm going to stay in v2.0 so that I can keep being up to date, and fix the docking issue right away.
I don't know if all this is a Plank problem, a problem with the app itself, or maybe a problem with Lubuntu (I'm using Lubuntu 16.04 64-Bit).
Now, the icon that appears in my Plank dock (which I can't _keep_) is way too low res, as it looks all blurry. On top of that, the icon is just the Whatsie icon, but colored blue.
![untitled](https://cloud.githubusercontent.com/assets/20121301/18361969/755530b8-75da-11e6-9e01-9686a7f7c4cc.png)

Please, please fix the dock issue, as it has been bugging me for a little while now. Bring back the old icon as well, which was way prettier. And please also tell me if I'm complaining too much. Thanks. 

Regards,
Frantik02

**Comment by Aluxian** [comment]
We're still working to fix all these annoying bugs.

I changed the icon to prevent any possible inquiries from Facebook. I want to make it even more obvious this is an unofficial app.

**Comment by Frantik02** [comment]
I see. The blue Whatsie icon doesn't really bother me, but it bugs me just a bit that it is low-res. I hope you can fix the docking issue soon. This is a great app, man. Cheers and thank you.

**Comment by Sytten** [comment]
For the backport, you need to delete the cache folder (see the wiki).

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
