### ISSUE TITLE
Video calls redirected to desktop browser in 2.0

### ISSUE THREAD

**Issue by szekeres2016** [aluxian/Messenger-for-Desktop#551]
Hi, I'm not sure if this is the intended functionality of the app, but whenever I video call someone the desktop browser is opened and I have to log in and make the call there instead of the desktop messenger app.

**Comment by Sytten** [comment]
Ho thanks for reporting. It will be fixed.

**Comment by aluxian** [comment]
Hey, try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
