### ISSUE TITLE
Can you add group call? because it's boring to always swi...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#552]
**Description:**
Can you add group call? because it's boring to always switch between computer and iPod for a group call .-.

**Operating system:**
Windows

**Best thing about Whatsie:**
Performance

**Worst thing about Whatsie:**
No group call ;-;

**Extra:**
Mini games ?

**Comment by AlexGameQc** [comment]
:D
