### ISSUE TITLE
Missing slash in repo address on main page.

### ISSUE THREAD

**Issue by dominikduda** [Aluxian/Messenger-for-Desktop#559]
Slash is missing after `https://dl.bintray.com/aluxian/deb` on github page (ubuntu installation section).

Screen:
![image](https://cloud.githubusercontent.com/assets/14922999/18446765/0f2056fe-7924-11e6-98e6-ca9b971e3d7d.png)

It took me an hour to figure out whats wrong.

**Comment by dominikduda** [comment]
I created PR.

https://github.com/Aluxian/Facebook-Messenger-Desktop/pull/560

**Comment by Aluxian** [comment]
Thanks!
