### ISSUE TITLE
Trojan(as said by WebRoot Antivirus)

### ISSUE THREAD

**Issue by lolAJhere** [aluxian/Messenger-for-Desktop#563]
- Operating system: Windows 8
- Messenger for Desktop version:
  HI I am new to this messenger for desktop thing.
  I use WebRoot Antivirus as a malware protection.
  I downloaded it from the official site.
  When I tried to install it; my antivirus blocked it.
  then i disabled antivirus then installed successfully.
  After that i enabled antivirus then what happened next is shown in Screenshot below.
  (I dont know whats wrong or how to fix it!)
  Need help here
  ![untitled](https://cloud.githubusercontent.com/assets/18498932/18460437/369ef902-7991-11e6-8973-4238acc3e8a3.png)

**Comment by Sytten** [comment]
Just make an exception for the executable.
Avira also flag a false positive.
