### ISSUE TITLE
wrong link on web

### ISSUE THREAD

**Issue by imerio** [aluxian/Messenger-for-Desktop#566]
- Operating system: win 7 sp1 and win 8.1
- Messenger for Desktop version: I tried to download from your link on website (blue button "windows") and it relink me to filehorse...but when I download that file it's not working on any windows machine, it's still connecting and antivirus detects some problem. Than I tried to download messenger from github v. 2.0.1 and it works well so....

Thanks for your work on this helpful app.

**Comment by jorisw** [comment]
I didn't even trust it anymore when I saw the FileHorse website come up. Then I came to GitHub instead.
