### ISSUE TITLE
Preference for escape key behavior

### ISSUE THREAD

**Issue by nikreiman** [Aluxian/Messenger-for-Desktop#569]
When I press "escape", Messenger minimizes into my tray. It's really annoying and also happens if Messenger is the active app while pressing escape during alt+tab or win+tab. Whatsie doesn't behave this way, so I find it very odd that Messenger does.
- Operating system: Windows 10
- Messenger for Desktop version: Latest version

**Comment by Aluxian** [comment]
There's now a preference for this: Window > Close with escape key. (starting from v2)
