### ISSUE TITLE
Focus problem

### ISSUE THREAD

**Issue by rontav** [aluxian/Messenger-for-Desktop#570]
The app is unfocused. It stays on my second monitor, while I browse on the main one.

In v1, if I clicked any input in the app, it would behave like I expected: the input would become focused. 
Now, in v2, I have to click the input twice to get it focused.
- Operating system: Windows 7 64-bit
- Messenger for Desktop version: 2.0.1-beta

**Comment by rontav** [comment]
It behaves really strangely. Sometimes, it works like it should, but I can't find a pattern.

**Comment by aluxian** [comment]
Fixed in 2.0.7 (will be released soon): I added an item menu `Window > Accept First Click`
