### ISSUE TITLE
Application Stuck at connecting/ White screen of death

### ISSUE THREAD

**Issue by ollipop** [aluxian/Messenger-for-Desktop#574]
- Operating system: MAC OSX ELCAPITAIN 10.11.6
- Messenger for Desktop version: Version 1.4.8 (1.4.8)

The application stays stuck on a white screen the status bar shows "Connecting" without anything ever happening. Tried to delete and reinstall.. Same issue persist.

**Comment by dnlm92** [comment]
I have the same issue, I tried to delete the prefPane "com.aluxian.messengerfordesktop.plist" but still the same.

**Comment by preneond** [comment]
Same issue there!

**Comment by jack7kim** [comment]
Just updated the app and experiencing the same issue - can't use the app at all :(

**Comment by dnlm92** [comment]
I'm using the 2.0.1-beta and its working fine.

**Comment by jakeorr** [comment]
2.0.1-beta fixed this issue for me!

**Comment by ysim** [comment]
Experiencing the same issue with v1.4.8. Had to force quit. Can also confirm that 2.0.1-beta worked for me.

**Comment by ollipop** [comment]
@ysim Tried the beta, it logs in  but freezes from time to times.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
