### ISSUE TITLE
In new version of Messenger, Themes won't change.

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#577]
**Description:**
In new version of Messenger, Themes won't change.

**Steps to reproduce:**
Repair

**App version:**
2.0.1 beta

**OS:**
Windows 10

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by TheWrongAlice** [comment]
Same issue for me, I just logged in for the first time and nothing happens when I try to switch themes.

**Comment by TheWrongAlice** [comment]
Restarting the application and changing theme before I logged in solved the issue for me :)
