### ISSUE TITLE
New Messenger update can't be installed on Windows Xp

### ISSUE THREAD

**Issue by seketaferrari** [Aluxian/Messenger-for-Desktop#581]
- Operating system: Windows XP 32bit SP3
- Messenger for Desktop version: 2.0.2 

New Messenger update (2.0.2) isn't available for installing on Windows XP, please make it available.

**Comment by Sytten** [comment]
I dont think the new framework supports it.
Update your computer, XP is old........

**Comment by Aluxian** [comment]
Windows XP is not supported by v2 and newer. Please update your Windows or switch to MFD 1.x releases.
