### ISSUE TITLE
Let user toggle mini mode, because with "autohide sidebar...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#587]
**Description:**
Let user toggle mini mode, because with "autohide sidebar" feature it's not really useful, and less comfortable to find contacts.

**Operating system:**
Windows

**Best thing about Whatsie:**
Ease of use

**Worst thing about Whatsie:**
Nothing, it's great. maybe lack of keyboard shortcuts or documentation on them?

**Extra:**
[Not answered]

**Comment by lkgarrison** [comment]
I somehow accidentally toggled autohide sidebar and I can't get it back! I don't want it to autohide! Do you know how to reset this setting? I think some sort of keyboard shortcut triggered it?
