### ISSUE TITLE
Messenger beta 2.0.1 doesn't have a tray(notification) icon in Ubuntu 16.04.1

### ISSUE THREAD

**Issue by 19darion91** [aluxian/Messenger-for-Desktop#591]
- Operating system:Ubuntu Mate 16.04.1
- Messenger for Desktop version: 2.0.1 beta
  I just installed it on a fresh OS install and the icon doesn't appear in the tray.
  ![1](https://cloud.githubusercontent.com/assets/7683375/18580232/3f20ab76-7bf2-11e6-9110-20fc88cbd2af.png)

**Comment by CrocodileDandy** [comment]
Indeed, would be greatly appreciated :-)

Much <3

**Comment by fliker09** [comment]
Window -> Show in Tray
I've got another problem - app doesn't open on clicking the icon in the tray, so I am forced to use right-click menu, which is quite annoying

**Comment by aluxian** [comment]
Please check the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Left click still doesn't the app though.

**Comment by fliker09** [comment]
Is there a hope that left-click issue will be fixed?

**Comment by aluxian** [comment]
I don't know the cause. I did assign left-click and right-click listeners (left: open the app, right: open menu), but it doesn't seem to work (either because of https://electron.atom.io or Ubuntu).

**Comment by fliker09** [comment]
Yeah, read some issues on this subject... Sad story :(
