### ISSUE TITLE
Right-clicking causes a javascript error.

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#596]
**Description:**
Right-clicking causes a javascript error.

**Steps to reproduce:**
Right-click anywhere in the window

**App version:**
V2.0.0 and V2.0.1

**OS:**
Windows 10

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by ConnorBradley** [comment]
picking up
