### ISSUE TITLE
Unable to exit the Youtube player?

### ISSUE THREAD

**Issue by beppe9000** [aluxian/Messenger-for-Desktop#599]
When I open a youtube video and click the fullscreen button "[ ]" i have to restart the app to exit the fullscreen mode of the video. Pressing F11 only exits window-level's fullscreen but not at the player level.

Is there a keyboard shortcut I am missing? Or a menu item?

**Comment by aluxian** [comment]
Does clicking on the same icon when in full screen (something like `][`) exit full screen?

Does Esc work?

Can you please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?
