### ISSUE TITLE
Intrusive, unskippable, forced spyware

### ISSUE THREAD

**Issue by SystemDisc** [aluxian/Messenger-for-Desktop#606]
This is outrageous.

https://dl.dropboxusercontent.com/u/91771805/forcedspyware.mp4

**Comment by TheWrongAlice** [comment]
Hm, I had a checkbox there that I could uncheck on that page. Weird that you don't.

**Comment by amlozano1** [comment]
The checkboxes comes up if you click the underlined "Click here". That said, this is still dumb enough that I don't want to use this software anymore.

**Comment by Sytten** [comment]
See https://github.com/aluxian/Messenger-for-Desktop/issues/1153#issuecomment-283514347
