### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by martinoutheone** [aluxian/Messenger-for-Desktop#616]
OSX El Capitan : 10.11.6
Messenger 1.4.8

No launch, only white window with title "Messenger - Connecting" 
Can't do a thing about it, worked perfectly well before offering me to upload to 2.0.2 and then didn't download, went up to the website to download latest version which was 1.4.8 so not what the alert message offered me to do. Did that and now i'm fucked... Loved that app

**Comment by martinoutheone** [comment]
Worked when I downloaded the beta 1.5.0
At startup it offers me to upgrade to 2.0.2 again, if I click yes it crashes and get stuck
If I click no then it goes to connection window and works !

**Comment by martinoutheone** [comment]
My bad, link from website is broken, i found the 2.0.1 and it works

**Comment by QCaudron** [comment]
I'm having this issue too on OSX 10.11.4, with Messenger 2.0.2. It hangs on "Connecting", and there's an instance of nwjs Helper that chews through a full CPU ( with two other instances doing nothing ). Previous version of 1.5.4 ( I think ) worked great.

**Comment by pkuczynski** [comment]
I had the same issue after downloading the version from main page. But then I found github releases and once I got latest 2.0.1 the problem is gone...

**Comment by aluxian** [comment]
Please check the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
