### ISSUE TITLE
Request: docking

### ISSUE THREAD

**Issue by blureshadow** [aluxian/Messenger-for-Desktop#617]
- Operating system: W10
- Messenger for Desktop version: 2.0.1 beta

Would be nice to be able to dock the app on the side of windows, I talk a lot on facebook while browsing and it would be nice to move my mouse to the window and write then come back, but my current setup is DYI, with the messenger window as slim as possible on the right side of the screen and the browser is not maximized but has the right margin at the messenger window. Also the title bar is visible for messenger which makes me feel bad for a reason.

**Comment by aluxian** [comment]
I can't "dock" it like that because of the way it's built. You can hide the menu bar from View.
