### ISSUE TITLE
Javascript update 2.0.2

### ISSUE THREAD

**Issue by GarciaPL** [aluxian/Messenger-for-Desktop#631]
- Operating system: Linux (Ubuntu 16.04)
- Messenger for Desktop version: 1.4.3

Description:
Javascript update 2.0.2

[IMG](http://tinypic.com/r/24mf0y8/9)

**Comment by mawiseman** [comment]
- Operating System: Windows 10 Build 14393.187
![messenger_2016-09-23_08-29-01](https://cloud.githubusercontent.com/assets/1597273/18768435/6f4962cc-8168-11e6-8b2f-d4b33b6f4df9.png)

**Comment by TaylorRNelson** [comment]
I am also seeing this message, clicking OK does nothing. There doesn't seem to be a 2.0.2 update available for download?

**Comment by destro014** [comment]
Yeah i am having the same problem.

**Comment by cabban** [comment]
me to please fix the issue

**Comment by danieltomasz** [comment]
I have the same issue

**Comment by baxthesailor** [comment]
I have the same problem, anybody can help?

**Comment by Deleetdk** [comment]
Clicking cancel a lot of times makes it go away temporarily.

System: Mint 18.

**Comment by cabban** [comment]
![error](https://cloud.githubusercontent.com/assets/19514493/19408191/b886b2c2-92b7-11e6-8305-150e175504b0.jpg)

@Aluxian  PLEASE fix this issue with your awesome app:/

**Comment by RobertFischer** [comment]
I have this problem as well. It makes the app extremely obnoxious.

**Comment by Sytten** [comment]
See https://github.com/aluxian/Messenger-for-Desktop/issues/1009
