### ISSUE TITLE
right clicking on a person in the contacts list throws

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#637]
**Description:**
right clicking on a person in the contacts list throws

**Steps to reproduce:**
right click on someone in contacts list

**App version:**
2.0.1-beta

**OS:**
windows 10 v1607; build 14393.187

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by sideroff** [comment]
The exact error I get is: 
![exact_error](https://cloud.githubusercontent.com/assets/14294595/18741245/b5798d74-80b6-11e6-812a-4d0ad6379b7a.png)
