### ISSUE TITLE
I want to keep track of all the messages and messages from all of my friends. 

### ISSUE THREAD

**Issue by afcentry** [aluxian/Messenger-for-Desktop#639]
- Operating system:linux64
- Messenger for Desktop version:2.0.1
  I want to keep track of all the messages and messages from all of my friends. But  i do not know where these come from?

**Comment by afcentry** [comment]
Where can I go to all the news and friends information?

**Comment by afcentry** [comment]
Please help `me...>`

**Comment by aluxian** [comment]
What do you mean? MFD is just a wrapper for https://www.messenger.com

It doesn't provide all the functionality of facebook.com
