### ISSUE TITLE
Tray icon animation in Windows responds too slow

### ISSUE THREAD

**Issue by poisonborz** [aluxian/Messenger-for-Desktop#643]
- Operating system: Windows
- Messenger for Desktop version: 2.0.1-beta

The new tray icon animation is downright bad UX - the slowly blinking blue icon is much worse than the red dot that displayed previously. Instead of the instant feedback the red dot provided, the user now must stare at the slowly blinking icon whether it blinks or not. It requires full attention instead of a quick glance. I think a constant icon change should be brought back, or at least be optional (eg no-blinking blue icon).

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?
