### ISSUE TITLE
Windows Alt-key functionality non-platform conforming

### ISSUE THREAD

**Issue by poisonborz** [aluxian/Messenger-for-Desktop#644]
- Operating system: Windows
- Messenger for Desktop version: 2.0.1-beta

Currently, the app can have its menu bar hidden with view/toggle menu bar or Ctrl-Alt-B (the setting is sadly not saved upon restart). This is the only way to toggle the menu bar.
In Windows, most applications conform to the rule that whenever the menu bar is hidden, it's temporarily re-shown when pressing the Alt button (so that automatic Alt-shortcuts could be applied) and hidden when the menu gets out of focus. It would be great if MfD would behave similarly.

**Comment by aluxian** [comment]
This is a shortcoming of Electron, issue: https://github.com/electron/electron/issues/2504

**Comment by aluxian** [comment]
Actually, Electron already has this, I was looking at the wrong flags. Fixed in 2.0.7 (will be released soon)

**Comment by poisonborz** [comment]
\o/
