### ISSUE TITLE
not taking image from paste

### ISSUE THREAD

**Issue by tygas** [aluxian/Messenger-for-Desktop#652]
hey guys
i see one bug in messenger
when i make i print screen with greenshot and want to paste directly to chatter it does not take it
need to paste it first to paint and then to messenger

Not sure if it is greenshot or messenger bug.
http://getgreenshot.org/
- Operating system:
- Messenger for Desktop version:

**Comment by mdsolver** [comment]
Have same issue, used to work before 2.0.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?
