### ISSUE TITLE
Keeps connecting after launch

### ISSUE THREAD

**Issue by radimne** [aluxian/Messenger-for-Desktop#654]
After launch, a black window opens and the headline says "Messenger - Connecting". Tried restarting the app and Mac and even reinstall.
- Operating system: macOS Sierra 10.12.1 Beta (16B2327e)
- Messenger for Desktop version: Version 1.4.8 (1.4.8)

**Comment by smidaharoun** [comment]
Same here, any suggestion

**Comment by smidaharoun** [comment]
[v2.0.1-beta](https://github.com/Aluxian/Facebook-Messenger-Desktop/releases) worked for me.
You should try it.

**Comment by radimne** [comment]
This works. Thanks!

28. 9. 2016 v 9:58, Haroun SMIDA <notifications@github.com>:

v2.0.1-beta <https://github.com/Aluxian/Facebook-Messenger-Desktop/releases> worked for me.
You should try it.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
