### ISSUE TITLE
Black notification “Keep the conversation going from your...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#661]
**Description:**
Black notification “Keep the conversation going from your phone. Get App” is always shown, even if I already have a Facebook Messenger on my iPhone.

It's a little bit annoying.

**Steps to reproduce:**
To hide notification or let the user hide or close it.

**App version:**
Facebook Messenger for Desktop 2.0.1-beta

**OS:**
Windows 8.1

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by raine** [comment]
Updated and started seeing it.
