### ISSUE TITLE
Hey. :)

Could You please add an internal Options, or sim...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#668]
**Description:**
Hey. :)

Could You please add an internal Options, or similar, to edit the in-app shortcuts?

I am a Linux user and apply alt+shift to switch between keyboard layouts (a thing I do very often) and each time I press alt, the Menu Bar drops down automatically (even if I hide it).

I can imagine people having different shortcuts for different stuff, and my suggestion could improve such little nuisances.

To put my suggestion in an example, changing the in-app 'ctrl+alt+i' combo into something else, like 'ctrl+m', or instead of 'alt' for the menu to '1'.

I hope I was clear enough.

In any case, thank You for the amazing app, You know by now that it's the best! Great work. Also, Romania is beautiful. :D

Enjoi,
m

**Operating system:**
Linux

**Best thing about Whatsie:**
Performance

**Worst thing about Whatsie:**
What I described. :D The only other issue I encountered, at least for so far, is that the suggestion to install the app for my mobile does not disappear (I don't have such a phone atm).

**Extra:**
Enjoy life and keep up the good work on making the world a better place with free and high-quality stuff. By this, You contribute to saving our society at large. Thank You. :)

**Comment by mozzribo** [comment]
Thanks, Aluxian. ;)

Great job with the new version and its feats.

**Comment by Aluxian** [comment]
I've adjusted some shortcuts, I'll adjust more and release an update soon.  Cheers :)
