### ISSUE TITLE
Styles/ Themes

### ISSUE THREAD

**Issue by DaniranS** [Aluxian/Messenger-for-Desktop#669]
- Operating system: Windows 10
- Messenger for Desktop version: 2.0.1

The theme Dark, keeps the blank letters without being able to read them, because of the white color, I recommend switching to black...
Before:
![image](https://cloud.githubusercontent.com/assets/12533338/18848138/10d54680-83fb-11e6-8bbc-e3f2442bccc3.png)
![image](https://cloud.githubusercontent.com/assets/12533338/18848193/54f02330-83fb-11e6-8521-6f17dbe5bf2f.png)

After:
![image](https://cloud.githubusercontent.com/assets/12533338/18848246/79431d3c-83fb-11e6-99f9-5586b8d9ec9f.png)
![image](https://cloud.githubusercontent.com/assets/12533338/18848278/94f5414a-83fb-11e6-89a9-6cdd1ef17fba.png)

**Comment by Aluxian** [comment]
Are you sure you're running v2? I think you're running the old version judging by your window icon (and the path says .../nw/...).
