### ISSUE TITLE
Add clear way to refuse Yahoo crapware

### ISSUE THREAD

**Issue by raptormama** [aluxian/Messenger-for-Desktop#676]
I don't want Yahoo crapware but I don't see a checkbox to check/not check to allow me to not install it. I'm passing on this update (or using the portable version, which has no installer) until this is added.

It should also default to 'do not install'.

I like Messenger for Desktop, but I am not going to install Yahoo. I am actively avoiding them by choice thanks to their irresponsible distribution of tens of millions of users' personal information.

The apparently-forced inclusion of Yahoo crapware makes this product look bad.

**Comment by aluxian** [comment]
All the app suggestions are optional. If you find something weird or that you can't disable please send me screenshots and I'll report it.
