### ISSUE TITLE
the new version of messanger is not starting anymore... i...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#682]
**Description:**
the new version of messanger is not starting anymore... is loading forever. The previous version also is not working as expected because is forcing you to upgrade.

**Steps to reproduce:**
open destop messanger

**App version:**
2.0.1 -beta

**OS:**
Windows

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by mradzinski** [comment]
And it doesn't allow you to exit either

**Comment by bloqhead** [comment]
Running into the same issue here too on OS X 10.10.5. I have to force-quit the app via CMD + OPT + ESC.

**Comment by Streppel** [comment]
Same here for Linux (elementary OS 0.4 Loki). So this happens on all platforms. Weird...

**Comment by Streppel** [comment]
Does anyone has any idea of the reason? I'll try to inspect a little bit further but I don't know if there's anyone look at it in the meanwhile... I still haven't got the chance to test this application because of this.

**Comment by mradzinski** [comment]
Previous versions are working fine, so I guess it must be something introduced into this new beta. If you wanna try the application just download the previous version (2.0.0-beta) from the releases page here on Github.

**Comment by hickscorp** [comment]
Same here on Ubuntu 16.04.
Also sometimes I get stuck with this:

![image](https://cloud.githubusercontent.com/assets/822933/19020985/069390ba-88af-11e6-985e-de9f9e8a028f.png)
