### ISSUE TITLE
app wont load except the whole white screen appears

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#694]
**Description:**
app wont load except the whole white screen appears

**Steps to reproduce:**
no idea

**App version:**
messenger for desktop

**OS:**
windows 10 64 bit version

**Works in WhatsApp Web:**

**Extra:**
no

**Comment by kpau** [comment]
This is happening to me too,
When I open the app it shows the loading screen, and nothing else happens.

OS: Windows 8.1 64-bit,
v2.0.1-beta
