### ISSUE TITLE
Update issues ~ it won't update

### ISSUE THREAD

**Issue by Laliat** [aluxian/Messenger-for-Desktop#699]
- Operating system: Windows 10
- Messenger for Desktop version: I have no idea, but...

Since it keeps asking me to update to 2.02, I assume I have whatever version before 2.02. The problem is that it doesn't actually update. Whenever I click on Yes, it gets stuck on a white screen with a loading animation. Then it'll say something about nwjs being unresponsive and asking me to restart, which just gets stuck on the loading animation again.

Does the update just take long to install and I should just wait for it to finish eventually or would I just be staring at the loading screen for nothing?

**Comment by hickscorp** [comment]
Same issue here, at startup.

![image](https://cloud.githubusercontent.com/assets/822933/19020975/cd502160-88ae-11e6-8a60-75b4c1993a5b.png)

**Comment by PixelPolish** [comment]
Same here. Downloading the installer also doesn't help as it's the same exact size as the previous version, so it doesn't seem like it was updated to 2.0.2

**Comment by ForumLiker** [comment]
Where did you get the version 2.0.2??
![2016-10-03 16-38-09](https://cloud.githubusercontent.com/assets/11502792/19039265/e504e8a2-8987-11e6-8686-773c2735db60.png)

**Comment by PixelPolish** [comment]
I didn't, that's the problem.

**Comment by hickscorp** [comment]
@ForumLiker I'm pretty sure the version displayed by this popup has nothing to do with the version of the app. It's more about a Javascript runtime, or a component from Electron.

**Comment by hickscorp** [comment]
@ForumLiker Read our request again. We don't have 2.0.2. I tried with both 2.0.1 and beta, and both are **asking me** to upgrade to 2.0.2 on startup.

**Comment by TheHaso** [comment]
@Laliat @hickscorp @PixelPolish 

There's no issues, but you guys are starting the old application instead of the new one.

Just uninstall the messerger (all of them you can find), and install the latest release from the dev [here - v2.0.1](https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v2.0.1)

**Comment by hickscorp** [comment]
@TheHaso & @ForumLiker I think I get what's going on. The version set for download on the main website is 1.5. Maybe that old version had problems. I'm trying to download the 2.0.1 now, but the S3 bucket is slow as a slug, my download stall around 5MB.

**Comment by bogiman** [comment]
Ok,i have same problem ..i updated my version,and  i start program  from :internet"s programs-as administrator..Work for me now..

**Comment by PixelPolish** [comment]
Heh, yeah, seems like it was a problem with 1.5.0 from the site. Fixed now ;)

**Comment by bogiman** [comment]
![2016-10-04 00 57 55](https://cloud.githubusercontent.com/assets/22604085/19057121/f8cf9198-89cd-11e6-8ce9-2ed8d1716e97.png)
Its work fine with my Zorin Os

**Comment by mikegron** [comment]
I updated to 2.0.2 and got a virus, I'm pretty sure 2.0.2 is a fake, don't update!

I entered another issue for that: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/804

**Comment by TheHaso** [comment]
@mikegron 

There is no v2.0.2, i dont know what you downloaded, but that thing you reffer to is an ad and skipable.

**Comment by mikegron** [comment]
@TheHaso 
That's my point. If you open the app version 2.0.1, it tell you there is an update for version 2.0.2, and clicking the "ok" button doesn't do anything. I didn't know 2.0.2 didn't exist until I checked the releases here but the download link on the website includes a virus.

**Comment by TheHaso** [comment]
@mikegron 
I see, thats very bad if its the case. Im currently sticking with Rambox and have top-notch experience.
Posted about it at #805 so others can be aware.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
