### ISSUE TITLE
do some thing like Facebook massager,left side showing al...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#701]
**Description:**
do some thing like Facebook massager,left side showing all those who online beside green it will great help as for check form hear directly neither need to go to browser to check how many friend are online right now,and i hop you will defenetally done it .

**Operating system:**
Windows

**Best thing about Whatsie:**
Performance

**Worst thing about Whatsie:**
theme,it has no better theme dud

**Extra:**
i already suggest to you in my upper side msg

**Comment by TheHaso** [comment]
oh god, please do something your self. you can press the gear icon and select online friends.
