### ISSUE TITLE
I don't get notifications when the window is minimized

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#703]
**Description:**
I don't get notifications when the window is minimized

**Steps to reproduce:**
I minimize the window and I don't know if a message comes in

**App version:**
2.0.1.-beta

**OS:**
Windows 10

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by TheHaso** [comment]
Press the gear icon, then settings and enable desktop notifications
