### ISSUE TITLE
if you right-click anywhere at all in the application win...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#710]
**Description:**
if you right-click anywhere at all in the application window, you get a javascript error box pop-up

Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: listeners.js:16:42.
    at WebContents.callIntoRenderer (/opt/messengerfordesktop/resources/electron.asar/browser/rpc-server.js:189:19)
    at emitTwo (events.js:111:20)
    at WebContents.emit (events.js:191:7)

**Steps to reproduce:**
launch application, right click anywhere

**App version:**
2.0.1-beta

**OS:**
ubuntu 14.04

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by wowwood** [comment]
Same issue on windows 10 Pro 64bit. 
![image](https://cloud.githubusercontent.com/assets/6392165/19121011/daa05766-8b1c-11e6-9332-f9b48d8ebfbf.png)
