### ISSUE TITLE
info bar on the right side of chat is not hiding, when wi...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#712]
**Description:**
info bar on the right side of chat is not hiding, when window is resized to very small sizes it doesnt show the chat like it used to, instead the right side bar covers the entire window

**Steps to reproduce:**
resize the window to something like 400x400

**App version:**
I was on beta 1.5 now on 2.0.1 and still see this behavior, I updated to 2.0.1 to see if it was fixed but nope

**OS:**
w10 14393 x64

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by johndbritton** [comment]
@aluxian-huginn I was experiencing the same problem, if you click the `i` icon in the top right you can hide that sidebar and the app is usable at least.
