### ISSUE TITLE
The spell checker is not working

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#716]
**Description:**
The spell checker is not working

**Steps to reproduce:**
Enable check spelling while typing in program Edit menu. Set language (English). Type messages and attempt to activate spell checker in any imaginable way. Watch all the misspelled words remain unchanged and unmarked, and without any action applicable that might relate to spell checking.

**App version:**
2.0.1-beta

**OS:**
Windows 7 Pro, 64-bit

**Works in WhatsApp Web:**

**Extra:**
Thank you for making this application available!

**Comment by edbelize** [comment]
Same on Linux Ubuntu 17.04, no spellchecking working.

**Comment by Shankaraya** [comment]
same on linux mint 17.3
