### ISSUE TITLE
All of a sudden, an options sidebar showed up - it shows ...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#717]
**Description:**
All of a sudden, an options sidebar showed up - it shows the options to change the chat color, view the photos from the chat, etc. But there is no way to remove it, and it makes the window huge since if you try to size it, that menu bar literally takes over the chat area. I use this app at work, but now I can't because I can't make it small and inconspicuous, and the photos are glaringly obvious. If this is a new feature, it isn't a good one!

**Steps to reproduce:**
Use the app. I even tried redownloading and installing it, and that didn't work.

**App version:**
2.0.1-beta

**OS:**
Windows 7

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by Music-Theory** [comment]
There should a button in the top right that looks like an 'i'; it should be highlighted blue. That should toggle the sidebar.
