### ISSUE TITLE
Shortcut keys

### ISSUE THREAD

**Issue by n4sedo** [Aluxian/Messenger-for-Desktop#72]
I suggest adding some keyboard shortcuts, i.e. ctrl+(shift+)tab and ctrl+(1-9) for changing conversations, ctrl+n for new conversation, ctrl+f to find people, etc
like i've made it here
https://github.com/sernick/Messenger/blob/master/Messenger/Data/Scripts/app_shortcuts.js

**Comment by Aluxian** [comment]
Thanks, I'll take a look and add them.

**Comment by cowboy** [comment]
Those keybinds would be awesome. Also, a keybind to toggle showing/hiding the sidebar would be great!

**Comment by tiagonbotelho** [comment]
+1 This might be the biggest reason to change to a native app instead of using the browser version
