### ISSUE TITLE
I would like to share content from any application to Messenger

### ISSUE THREAD

**Issue by pkuczynski** [Aluxian/Messenger-for-Desktop#721]
- Operating system: macOS
- Messenger for Desktop version: any

On macOS an application can register as an extension allowing to receive shared items. Once enabled it will be listed on the Share menu (e.g. in Safari it is displayed on the top right corner with an icon similar to iOS).

It would be great to have this ability to share the pages I am browsing directly into Messenger without annoying copy paste...

**Comment by bergomel** [comment]
I would love that! Messenger is my most used  sharing service, it's a pain to login every time I want to share a link or file with friends.
