### ISSUE TITLE
Time is shown as 12-hour clock

### ISSUE THREAD

**Issue by bardi15** [aluxian/Messenger-for-Desktop#724]
- Operating system: W10
- Messenger for Desktop version: 2.01

Automatically clock is set to 12- hour AM/PM, but locally it should be 24 hour. No way to change in settings.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?

If you open messenger.com in Chrome/Chromium, does it show correctly?
