### ISSUE TITLE
When switching over to MfD from another window, even if I...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#726]
**Description:**
When switching over to MfD from another window, even if I click in the Type a message... box, I have to click in it again to begin typing. I would expect to be able to begin typing as soon as I switch over, like Skype does.

**Steps to reproduce:**
With another window active, move the mouse over the MfD window and click within it, outside of the Type a message... box. The MfD window will become active, but you will not be able to begin typing until you click in the Type a message... box.

**App version:**
Version 2.0.1-beta

**OS:**
Windows 10 Home Edition

**Works in WhatsApp Web:**

**Extra:**
When using a dark theme, I'd like the bits of dark text (such as the information about the person you're messaging at the top of their message log) to change to white text, so they are easier to read.

**Comment by dominateeye** [comment]
Additional: Right-clicking in MfD causes a box to pop up saying "JavaScript error in the main process"
