### ISSUE TITLE
Wrong color in the Dark and Mosaic themes

### ISSUE THREAD

**Issue by dimitar032** [aluxian/Messenger-for-Desktop#733]
- Operating system: Kubuntu 16.04 LTS
- Messenger for Desktop version:  2.0.1  deb

Hello , i am using the app its awesome, when i switch to Dark or Mosaic the input bar field background color is white and the white is not the write color.

//dark.css
**It should be: (or simillar dark color)**
._4rv3 {
    border-top-color: rgba(0, 0, 0, .1) !important;
}

**Now its: (for the default theme this is the right color but not for the Dark and Mosaic)**

._4rv3 {
    border-top-color: rgba(255,255, 255, .1) !important;
}

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?
