### ISSUE TITLE
I don't get notifications in the action center when I rec...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#734]
**Description:**
I don't get notifications in the action center when I receive new messages.
## **Steps to reproduce:**

**App version:**
2.0.1-beta

**OS:**
windows 10 edu

**Works in WhatsApp Web:**

**Extra:**
windows > notifications badge in taskbar is checked.
All options are fine in the windows' settings. Notifications are turned on.

**Comment by klenium** [comment]
Why did you close this? I've installed 2.0.4-beta, still not working. Have to install the old 1.8 again...
