### ISSUE TITLE
cannot install on arch

### ISSUE THREAD

**Issue by busbauen** [aluxian/Messenger-for-Desktop#741]
- Operating system: ARCH
- Messenger for Desktop version: XFCE-4/i3

Hey,
I can't install the messenger. I know the issue but don't know how to fix it.

yaourt -S messengerfordesktop
npm ERR! Command failed: git clone --template=/home/kmille/.npm/_git-remotes/_templates --mirror git://github.com/nevercast/nw-builder.git /home/kmille/.npm/_git-remotes/git-github-com-nevercast-nw-builder-git-mfd-66c6b499
npm ERR! Klone in Bare-Repository '/home/kmille/.npm/_git-remotes/git-github-com-nevercast-nw-builder-git-mfd-66c6b499' ...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Die Wartezeit für die Verbindung ist abgelaufen

Which means session is timed out.
But using https instead of ssh works:
kmille@linbox> git clone --template=/home/kmille/.npm/_git-remotes/_templates --mirror https://github.com/nevercast/nw-builder.git /home/kmille/.npm/_git-remotes/git-github-com-nevercast-nw-builder-git-mfd-66c6b499
Klone in Bare-Repository '/home/kmille/.npm/_git-remotes/git-github-com-nevercast-nw-builder-git-mfd-66c6b499' ...
remote: Counting objects: 1301, done.
remote: Total 1301 (delta 0), reused 0 (delta 0), pack-reused 1301
Empfange Objekte: 100% (1301/1301), 374.13 KiB | 330.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (778/778), Fertig.
kmille@linbox>

**Comment by aluxian** [comment]
I don't maintain the AUR package. Please retry or submit a comment there.
