### ISSUE TITLE
JavaScript error in the main process

### ISSUE THREAD

**Issue by YasseenDeHerdt** [Aluxian/Messenger-for-Desktop#755]
- Operating system: Windows 10
- Messenger for Desktop version: Yes
  ![messenger for desktop_2016-10-10_19-15-46](https://cloud.githubusercontent.com/assets/18115558/19244746/0cc44e3c-8f1e-11e6-8862-a226dbd09355.png)
1. Make clean install of app
2. Open app
3. Rightclick in conversation

And then this popped up

**Comment by dim4o** [comment]
The same problem after clean install and right click on conversation. 
OS: Windows 8.1
