### ISSUE TITLE
After updating to the newest version, it shows the loadin...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#764]
**Description:**
After updating to the newest version, it shows the loading icon for a while and then just shows blank. So the entire frame of the app is visible, all of the option buttons "App, Edit, View, Theme ..." are visible, and the rest of the app does not work.

**Steps to reproduce:**
The issue is constant.

**App version:**
The newest version.

**OS:**
I'm not sure, but I'm using a Lenovo Carbon X1 with Windows 10 installed.

**Works in WhatsApp Web:**

**Extra:**
no, thank you

**Comment by llbraughler** [comment]
I have the same issue on Mac OS X 10.10, reverting to the older version fixes the problem.

**Comment by ShahrumAmiri** [comment]
Same issue here :(
