### ISSUE TITLE
Using AltGr shortcuts on numbers (0, 1, 2, 3) causes them...

### ISSUE THREAD

**Issue by aluxian-huginn** [aluxian/Messenger-for-Desktop#767]
**Description:**
Using AltGr shortcuts on numbers (0, 1, 2, 3) causes theme changes (typing characters: ˝ ~ ˇ ^).

This is not an issue on the web messenger (so it 'works', there are no theme changes).

**Steps to reproduce:**
Press AltGr (effectively Ctrl+Alt) and 0, 1, 2 or 3.

**App version:**
2.0.1 beta

**OS:**
Windows 10

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by PrimozR** [comment]
Currently on 2.0.5 beta, this issue persists.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

**Comment by aluxian** [comment]
Wrong comment, see edit ^
