### ISSUE TITLE
Messenger suddenly ignoring config file

### ISSUE THREAD

**Issue by jkugler** [aluxian/Messenger-for-Desktop#776]
- Operating system: Ubuntu 16.04
- Messenger for Desktop version: 1.5.0 Beta.

I have been using Messenger for quite a while.  Works well! Thanks!

I recently upgraded to Ubuntu 16.04 from 14.04, and Messenger was still working fine. Today I restarted it, and I noticed two things: the left column was narrow (just the pictures, no names), and escape closed application, contrary to the config settings for both those things. This was 1.4.x  I upgraded to the 1.5.x beta, and still had the same behavior.  The key sequences for adjusting the column setting don't seem to be documented anywhere, so I couldn't adjust the columns.  This is the preferences.json file:

``` javascript
jkugler:~/.config/Messenger] $ cat preferences.json 
{"settings":{"launchOnStartup":false,"openLinksInBrowser":true,"autoHideSidebar":false,"asMenuBarAppOSX":false,"windowState":{"mode":"normal","x":1120,"y":25,"width":800,"height":600},"theme":"default","checkUpdateOnLaunch":true,"closeWithEscKey":false}}
```

Any ideas? :)

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
