### ISSUE TITLE
Text is out of window

### ISSUE THREAD

**Issue by skyli91** [aluxian/Messenger-for-Desktop#778]
- Operating system: Win 10
- Messenger for Desktop version: 2.0.1 beta

![image](https://cloud.githubusercontent.com/assets/7442913/19301872/eda21fda-9061-11e6-823e-adf428cc0e39.png)

I think something changed in the web app, some new css i guess..

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue? Also try to resize the app.
