### ISSUE TITLE
Icon in the systray is invisible. There's is a blank spac...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#780]
**Description:**
Icon in the systray is invisible. There's is a blank space. Hidden messenger shows up when I click on this invisible icon.

**Steps to reproduce:**
1. Minimize program to systray by clicking 'close' button. 2. Take a look at systray.

**App version:**
2.0.1-beta

**OS:**
Windows 7 Professional

**Works in WhatsApp Web:**

**Extra:**
e-mail me if you want a screenshot:)

**Comment by granthgh** [comment]
Tray icon is also invisible on Mint KDE 17.3 using 'messengerfordesktop-2.0.1-linux-amd64.deb' package. 

Tray icon is fine in the release 1.50 version.
