### ISSUE TITLE
Chrome notifications instead of native Windows ones

### ISSUE THREAD

**Issue by HRoland1** [Aluxian/Messenger-for-Desktop#79]
As I noticed, this app is Chromium based. The Chrome notifications are much more elegant than the Windows 8 ones. Is there any way at the moment to change the notification type or will there be a switch in the settings to do this? :)

**Comment by ferdau** [comment]
+1, an option in the setting screen would be great.

**Comment by bwat47** [comment]
personally I'd prefer it use native windows notifications, I wouldn't be opposed if it was optional though

**Comment by alopix** [comment]
Would be a nice option as Chrome notifications are more beautiful.

**Comment by mcyo** [comment]
+1

**Comment by iBobik** [comment]
What it will be like on OS X? Chrome's custom notifications are not welcome by most users there, most Mac users want native OS X notifications.

**Comment by Aluxian** [comment]
I know, me too. It will be just an additional setting. Native by default.


--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On Sun, May 31, 2015 at 1:34 pm, Jan Pobořil < notifications@github.com [notifications@github.com] > wrote:
What it will be like on OS X? Chrome's custom notifications are not welcome by
most users there, most Mac users want native OS X notifications.

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/79#issuecomment-107152416] .[https://github.com/notifications/beacon/ABWmdsrRZpUtIS52yBZ6ubykZVZenSegks5oOtsegaJpZM4EUy3B.gif]

**Comment by HRoland1** [comment]
Do you have any release date @Aluxian ? :)
