### ISSUE TITLE
Ability to resize different sections. Also right click error.

### ISSUE THREAD

**Issue by DanielMidler** [aluxian/Messenger-for-Desktop#794]
The message textbox is too small/short. I'm pretty sure it used to be taller. Even if it wasn't, I think you should be able to resize the different sections. So the left side with the people/groups and the bottom message textbox.

Also the right click error is pretty annoying.
- Operating system: Windows 7
- Messenger for Desktop version: 2.0.1

**Comment by aluxian** [comment]
I think it's back to full width now, try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Right-click menu is temporarily disabled until it's fixed. Tracked here: https://github.com/aluxian/Messenger-for-Desktop/issues/528
