### ISSUE TITLE
Please Release Ver 2.0.2

### ISSUE THREAD

**Issue by Leolad** [aluxian/Messenger-for-Desktop#795]
- Operating system: Win7
- Messenger for Desktop version: 2.0.1

Every time I open it I am told there is a new Version 2.0.2 and Do I Want To Update to it.
It's a little annoying.

Trevor

**Comment by peci1** [comment]
Mee too on Linux.

Until I cancel this dialog, the app will not load.

**Comment by ValiDeaconu** [comment]
I've this problem too, on Ubuntu 16.04.

Even if I upgrade it to the version I am redirected to, the dialog still appears.

**Comment by sheldonhull** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/804

Please read this immediately. In case I'm wrong, i'm hoping for further updates.

**Comment by Sytten** [comment]
See https://github.com/aluxian/Messenger-for-Desktop/issues/1009
