### ISSUE TITLE
Virus with version 2.0.2

### ISSUE THREAD

**Issue by mikegron** [aluxian/Messenger-for-Desktop#804]
- Operating system: Windows 
- Messenger for Desktop version: 2.0.1

Be aware!

From the homepage (https://messengerfordesktop.com/), if you click on the Windows download link, it redirects you to http://messengerfordesktop.searchmgr.com/ which will download a version 2.0.2 with a trojan virus, a "search manager" chrome extension, yahoo toolbar, a fake anti-malware and a driver installer of some kind (probably all malwares).

Also, the version 2.0.1 of the program will tell the user that version 2.0.2 is available when opening it.

**Comment by sheldonhull** [comment]
How did this happen? Any updates on how this hijacked the url? Maybe you could remove the url from the front readme?

**Comment by sheldonhull** [comment]
This shows even the 2.0.1 from the front page is giving me a request for additional software. 
Is this an expected behavior and a more recent change?

![2016-10-28_19-51-08](https://cloud.githubusercontent.com/assets/3526320/19826049/ed25500c-9d47-11e6-874e-370819297874.png)

**Comment by Sullynm** [comment]
Operating system Win 10
Messenger for Desktop 2.02
I get the following from Norton when i try to install the update. the very first time, it gave me the option of installing some optional software, to which i declined.  now its a trojan or so says norton,  and apparently many other virus programs.  I think you are right, and they need to take down the link until they get things on their end fixed. 

![messenger update trojan](https://cloud.githubusercontent.com/assets/23183844/19880592/471e8f14-9fc4-11e6-8931-ec3796d86136.jpg)
![202 trojan](https://cloud.githubusercontent.com/assets/23183844/19880636/9cfdc7ce-9fc4-11e6-9429-5bdfecd766e5.jpg)

**Comment by sheldonhull** [comment]
Are there some other responses I'm missing. This seems like a huge priority for the project itself. I can not recommend this to anyone at this point due to the potential for malware. Anyone have something to chime in on? In the meantime, I need to flag the repo since it's still showing the links so no one gets any malware.

**Comment by sheldonhull** [comment]
I flagged this to github for now, as no updates. 

I just traced the activity and found that the JSON for the updates goes to a completely different site, after I download the file directly from the JSON for 

http://mac.filehorse.com/download-messenger-XXXXXXX

![image](https://cloud.githubusercontent.com/assets/3526320/20015469/9eebf656-a289-11e6-9901-45cfe5699099.png)

Something has compromised it. This change shows the original owner changed around 26 days ago, and no response, so this makes me question the validity of this repo. I would HIGHLY recommend anyone reading this avoid this repo until it's been checked out and owner removes links and sheds some light on situation. 

Please make sure anyone flagged 2.0.2 update issues in the issues tab is notified of this thread so they can monitor for resolution. I'll be uninstalling for now

**Comment by sheldonhull** [comment]
I ran VirusTotal on the installer. 

It flagged one scan: 
**ESET-NOD32	a variant of Win32/FusionCore.J potentially unwanted**	

https://www.virustotal.com/en/file/ef7632f33a8b6d361fa36b1bcc4936869d20f41095c77ad28690e56eb2e3b032/analysis/1478280199/


This shows MessengerForDesktopSetup, but the file detail seems to point to 2.0.1, not the 2.0.2 update. Not sure why. This is all the research I can do at the moment, but hopefully someone will chime in soon. Until then I'm uninstalling and not recommending this app further.

**Comment by voidstarfire** [comment]
Can confirm that the Mac link also produces a virus. Reported by Avast for Mac.

**Comment by matejkramny** [comment]
wow, this is really concerning.

**Comment by SladeNoctis** [comment]
Any update on this?

**Comment by Sullynm** [comment]
https://github.com/Aluxian/Messenger-for-Desktop/releases/tag/v2.0.1

 

just searched, and that popped up.  Downloaded it and didn’t show any virus pop up from Norton. So I think we are ok now. **crosses fingers**

**Comment by mikegron** [comment]
if you download directly from the GitHub Releases, it's fine

**Comment by SladeNoctis** [comment]
The homepage should be updated as well, since that would be the likely the landing page looking for this on SERPs.

**Comment by pkuczynski** [comment]
Another option for OSX is to install via brew:

`brew cask install messenger-for-desktop`

**Comment by insideClaw** [comment]
4 months later, website still supplies malware. Judging by the website [registrant](https://whois.domaintools.com/messengerfordesktop.com), the developer of this software might not even be the owner of the site (at least anymore).

On the upside the above solutions, among which simply following the Github instructions and obtaining from here, work flawlessly for using a clean Messenger.

**Comment by Sytten** [comment]
Please see https://github.com/aluxian/Messenger-for-Desktop/issues/1153#issuecomment-283514347
