### ISSUE TITLE
Since this project is currently dead, Rambox is an good alternative!

### ISSUE THREAD

**Issue by TheHaso** [aluxian/Messenger-for-Desktop#805]
Hi lads.

I would not normally do this, but as v1.5.x and v2.0.1 is totally dead and not working, Rambox is an extremely good open-source alternative untill this works again.

Also Rambox supports many chatproviders and email. Gathering them all in one place.

PS. i will not post the link, just google it. Also this is not ment for disrespect the dev of messenger for desktop. All respect to him, but its currently not working, therefore some need alternatives for now.

**Comment by Sytten** [comment]
Not dead ;P
