### ISSUE TITLE
The Messenger For Desktop windows stays blank at startup....

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#812]
**Description:**
The Messenger For Desktop windows stays blank at startup. I can see the menus, but no content is loaded.

**Steps to reproduce:**
It simply happens every time I start, restart or reload Messenger For Desktop. There is no way the content of the window gets loaded.

**App version:**
Windows 2.0.1-beta

**OS:**
Windows 10 Professionnal (version : 1607 - OS version : 14393.321

**Works in WhatsApp Web:**

**Extra:**
Your apps are very cool and usefull, but not very stable. I stopped using Whatsie a month ago because of too much new bugs, and now MessengerforDesktop also starts to show bugs. I hope you get these problems fixed !

**Comment by montepente** [comment]
I'm having the exact same problem with Mac OSX 10.10.5 Yosemite. It opens a white page, I can go through the menus, but nothing loads, in the bar over the app is says "Connecting" but it never ends. I can't close the App by clicking close from the menu, I'm forced to force kill it via the console.

It didn't happen to me in an older version, but in the current version it doesn't work (1.4.8) for me anymore.

Could it be a conflict of configuration stored on the computer from an old version to this one?

**Comment by HedvigS** [comment]
I also have this problem. What's up??

**Comment by HedvigS** [comment]
I downloaded the latest version, it seems fixed now and was mentioned in the list of updates. However, the old app never told me it needed updating.. perhaps that could be a new feature for next version?

**Comment by soaro77** [comment]
I'm having the same problem on MacOS 10.12.6 Sierra

**Comment by soaro77** [comment]
I was having the same problem and switched it to Workplace Messenger and then back. Now it's working fine.
