### ISSUE TITLE
Issues w/Toggle Function - Menu Bar

### ISSUE THREAD

**Issue by jessicaxr1** [aluxian/Messenger-for-Desktop#813]
There's a way to hide the toggle menu w/formatting options for Messenger (from the top), but no way to bring it back up.

Is there a shortcut I'm missing?

Operating system: Windows 10
Messenger for Desktop version: 2.0.1

Also having a lot of virus issues with the new update.

**Comment by Ligerx** [comment]
Just ran into the same problem.
Toggled the menu to see what it would look like, can't bring it back up.

**Comment by erykosky** [comment]
Guys press Ctrl+Alt+B :)

**Comment by aluxian** [comment]
There's a shortcut: Ctrl+Alt+B

Also, you can quit and restart the app.
