### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#815]
**Description:**
App does not start

**Steps to reproduce:**
Just start an app. New window is opened, and always white. This version worked twice after instalation. Previous version works.

**App version:**
2.0.1-beta

**OS:**
Windows 7, x64

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by undersmusic** [comment]
I have the same issue on OSX 10.10.5. Last version worked perfect but dont have that installer anymore as this update overwrote the last one. 

i miss the app.
