### ISSUE TITLE
Messenger Stuck on White "Connecting" Screen

### ISSUE THREAD

**Issue by Swailem95** [aluxian/Messenger-for-Desktop#831]
- Operating system: OS X
- Messenger for Desktop version: 1.4.8

I've tried reinstalling the application 3 different times and I get the same result every single time. When I open up the application, I see a white screen and it just says "Connecting at the top". I've left it for hours and nothing changes.

**Comment by TPetterson** [comment]
I have the same problem, pls help :(

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
