### ISSUE TITLE
JavaScript Error!

### ISSUE THREAD

**Issue by JuniorK92** [aluxian/Messenger-for-Desktop#857]
- Operating system: Windows 7 Professional SP1 x86
- Messenger for Desktop version: 2.0.1

This happens when trying to execute the program.

This has happened several times and the solution is to reinstall it.

Didn't happen in previous versions.

![capture](https://cloud.githubusercontent.com/assets/10118715/19490871/e03b2030-953e-11e6-9fed-394c20aa056c.PNG)

**Comment by Sytten** [comment]
We will continue the discussion here: https://github.com/aluxian/Messenger-for-Desktop/issues/1170
