### ISSUE TITLE
Linux: Startup notification icon in Unity stays after the application launched

### ISSUE THREAD

**Issue by jnv** [aluxian/Messenger-for-Desktop#867]
- Operating system: Ubuntu 16.10 x64
- Messenger for Desktop version: 2.0.1-beta

When Messenger for Desktop is started, the pulsating StartupNotification icon appears in the dock and stays even after the application's main window appears.

![](https://cloud.githubusercontent.com/assets/616767/19514293/553cf85e-95f3-11e6-827f-bd975cde4721.png)

The root cause seems to be in `WM_CLASS`. The .desktop launcher for Messanger for Desktop contains:

```
StartupWMClass=messengerfordesktop
```

However, running `xprop WM_CLASS` on Messenger for Desktop returns the following line:

```
WM_CLASS(STRING) = "messenger for desktop", "Messenger for Desktop"
```

Therefore StartupWMClass doesn't match and WM doesn't know the application already started.

The easiest solution is to modify the .desktop file with

```
StartupWMClass=messenger for desktop
```

However I wonder how the full name got to WM_CLASS in the first place, since I suppose Electron should use application's name (i.e. the one set in package.json).

**Comment by aurimus** [comment]
+1 I have an issue where Plank would display blurred icon, and some people guess it's because of this. I can't reproduce what you are describing with unity though.

![screenshot from 2016-10-26 12-09-55](https://cloud.githubusercontent.com/assets/1052992/19744165/f4d60c84-9bd4-11e6-8094-42f0f18a0ffe.png)

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

**Comment by jnv** [comment]
Yeah seems fixed, thanks! :+1:
