### ISSUE TITLE
MfD Window won't maximise

### ISSUE THREAD

**Issue by dfl1955** [aluxian/Messenger-for-Desktop#868]
- Operating system: Windows 10, post anniversary edition
- Messenger for Desktop version: Current

I have installed MfD on on W10 laptop which I use at work and home and places in between. I change wifi SSIDs frequently. I also use external monitors frequently.

The MfD window will not display when I try and open the window. I use the task bar icon and have used the task manger, switch to function. I uninstalled and installed the package (yesterday), which worked on the first instance, but failed again when I moved the laptop's location.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?
