### ISSUE TITLE
Remember window position

### ISSUE THREAD

**Issue by a-woo** [Aluxian/Messenger-for-Desktop#89]
Not sure if this is an issue with the app itself, but usually when I Ctrl-click to close an application, it remembers the previous window position when it runs the next time. Doesn't seem to happen for Messenger.

**Comment by alopix** [comment]
I think remembering window position should be part of the app already. Unfortunately it doesn't seem to work in a multi-monitor environment either :(

**Comment by Aluxian** [comment]
I think ctrl-click force closes the app, that's why the position isn't remembered.

**Comment by hikaritenchi** [comment]
Not sure if this goes here, or should be an additional issue, but the window doesn't reposition when the app is positioned in a monitor that has been disconnected. Using Win+Arrow key in Windows will reposition it correctly.
