### ISSUE TITLE
suggestion: try to detect if `nvm` is used instead of installing npm/nodejs semver and etc

### ISSUE THREAD

**Issue by tunnckoCore** [Aluxian/Messenger-for-Desktop#896]
- Operating system: Archlinux

I just tried installing it and it seems it not detects that I'm using `nvm`. I believe it would be good thing. We intentionally don't want global install of nodejs (or at least, most of node devs uses nvm or some other version manager).

**Comment by Aluxian** [comment]
Node.js is packaged with the app, and so are all the modules. This is how http://electron.atom.io works.
