### ISSUE TITLE
"Auto Hide Sidebar" problem

### ISSUE THREAD

**Issue by sol-dier** [aluxian/Messenger-for-Desktop#899]
- Operating system: Windows 7 x64
- Messenger for Desktop version: 2.0.1 Beta

I enjoy that messenger very much, got just one problem: "Auto Hide Sidebar" doesn't work. Are there any dependencies on Windows-Functions and/or services or what else can I do ? I deinstalled and reinstalled a lot of times, but the prob remains the same. The left border is cut away with the icon and a part of the conversation, looks like that:

![unbenannt](https://cloud.githubusercontent.com/assets/23011245/19625912/b6dbf814-9925-11e6-80ed-2117d1e63a24.PNG)

P.S.; The only way to restore the sidebar is with "View" -> removing checkmark "Auto Hide Sidebar".

**Comment by LackOfGumption** [comment]
I've experienced the same problem. What I've found is when my window is maximized the "Auto Hide Sidebar" begins working.

**Comment by sol-dier** [comment]
That's right, the bigger, the better it works, but I wanna watch my 
IRC-channel, too. Would you please send me a notice, when there's a new 
version with that bug fixed ?

Kind regards


Am 18.01.2017 um 04:31 schrieb Rowan C.:

**Comment by aluxian** [comment]
Tracked here: https://github.com/aluxian/Messenger-for-Desktop/issues/862
