### ISSUE TITLE
Ubuntu Repository?

### ISSUE THREAD

**Issue by Hillshum** [Aluxian/Messenger-for-Desktop#90]
I don't know if this is the right place to ask this, but would making an Ubuntu repository be helpful? I'm willing to maintain it...

**Comment by Aluxian** [comment]
Hi @Hillshum, currently there's no official repository. If you're willing to maintain one please do so and I'll add a link on the website :)

**Comment by Hillshum** [comment]
Alrighty. I'll look into packaging it.
