### ISSUE TITLE
the zoom in function works not that well. I had to zoomed...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#903]
**Description:**
the zoom in function works not that well. I had to zoomed in whenever I change to chat with someone else.

**Steps to reproduce:**
I hope that you would fix that problem because I really love this app.

**App version:**
2.0.1a

**OS:**
Win10 anniversary

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by mecjuszfufecjusz** [comment]
Maybe you could set a global variable to scale user interface that will be remembered (for example Telegram desktop – at least on Linux – does it very well).
