### ISSUE TITLE
request for HiDPI scaling options

### ISSUE THREAD

**Issue by raininja** [aluxian/Messenger-for-Desktop#904]
- Operating system: arch linux
- Messenger for Desktop version: 1.6.0

Requesting HiDPI scaling functions for this program, ala --force-device-scaling-factor.

almost unusable for me on this Ideapad Yoga 900.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

**Comment by raininja** [comment]
Works perfectly! Thanks!!!
