### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by Leolad** [aluxian/Messenger-for-Desktop#905]
- Operating system: Linux Mint 18
- Messenger for Desktop version: 2.0.1

Always asks me to upgrade it to 2.0.2, and after I cancel that it fails to make contact with FB and load my chat heads list

**Comment by Leolad** [comment]
Ok, I did another download of the programme from the dialogue telling me to upgrade to 2.0.2 and it's now working.

Cheers

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
