### ISSUE TITLE
Please Add filter for Connected friends and Not Connected...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#908]
**Description:**
Please Add filter for Connected friends and Not Connected friends.
there is long list and its make easy to find Out.
 Please Order by Online friends.

**Operating system:**
Windows

**Best thing about Whatsie:**
Performance

**Worst thing about Whatsie:**
[Not answered]

**Extra:**
[Not answered]

**Comment by ForumLiker** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/898
