### ISSUE TITLE
Install of 2.02

### ISSUE THREAD

**Issue by redbourn** [aluxian/Messenger-for-Desktop#910]
- Operating system: Windows 7
- Messenger for Desktop version: 2

Every time i open the app it asks me if I wanted to install, I go through the process but it has issues "checking if the squirrelSetup.log exists.." . It fails then continues whatever it can. 

Been doing this for a few weeks now

**Comment by zeroarst** [comment]
Same...I was kept asking.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?
