### ISSUE TITLE
Hiding the bar on the right side?

### ISSUE THREAD

**Issue by kingmustard** [Aluxian/Messenger-for-Desktop#911]
Operating system: Windows 10 x64
Messenger for Desktop version: 2.0.1 (beta)

The bar on the right started to appear around two weeks ago.

Is there a way to hide it?

![eb_removerightbar-1](https://cloud.githubusercontent.com/assets/1947304/19664017/9cd412c8-9a36-11e6-959b-46e544c49563.png)

**EDIT:** Tapping the "i" on the top-right corner closed it.

**Comment by Aluxian** [comment]
So it's solved. There's nothing else I can do.
