### ISSUE TITLE
Paused Video begins playing on new message

### ISSUE THREAD

**Issue by felix-starman** [aluxian/Messenger-for-Desktop#934]
- Operating system: OSX 10.12
- Messenger for Desktop version: 2.0.1-beta (2.0.1.26)

This seems intermittent (I will flesh this out later with more testing).

Given a video in convo is paused but visible in the convo
When  a new message is received
Then the video begins playing

I think it may be scrollToBottom, since more messages came in and it would still play but only for a second or so. I'm guessing it has something to do with the code surrounding auto-play and where the viewport is over the element.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?
