### ISSUE TITLE
The red badge on the app icon indicating a new message no...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#947]
**Description:**
The red badge on the app icon indicating a new message no longer stays until the message is read; it disappears on its own after a few seconds, which is not useful.

**Steps to reproduce:**
Receive a message and wait a few seconds; the red badge disappears.

**App version:**
2.0.1-beta

**OS:**
Windows 10 Pro 64-bit

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by ekolis** [comment]
Why were this issue and #939 closed without comment?

**Comment by Aluxian** [comment]
I closed all issues that come from typeform because they were too many to sort through.

**Comment by Aluxian** [comment]
I'm trying to find a more efficient way of getting issues. I'd rather have them reported on GitHub (think technical user who can help debug and understands things VS normal user).

**Comment by ekolis** [comment]
How will requiring issues to be reported directly on github discourage "normal" users from reporting them? Don't you want to get issues reported by all users? Sorry if I'm coming across as argumentative; if you'd rather not discuss this, I'll drop it!
