### ISSUE TITLE
Multi-services app

### ISSUE THREAD

**Issue by iBobik** [Aluxian/Messenger-for-Desktop#950]
How about to create app supporting also other services what have web app (Slack, Mattermost, Hangout, ...) and allow to use them simultaneously?

UI could be simple like from Slack app (sidebar will contain multiple account from one or multiple services):

![slack-sidebar](https://cloud.githubusercontent.com/assets/614232/19894342/f334c768-a04c-11e6-9097-77fe4e830312.PNG)

It will probably be good to design plugin architecture, so adding new service driver will require to write only some JavaScript integrating specific web app, not common thinks like handling system notifications and common UI.

It also could be easily portable to other platforms, because service drivers will be multi-platform.

What do you thing about it?

**Comment by Aluxian** [comment]
I intend to keep MFD a standalone app. See http://meetfranz.com
