### ISSUE TITLE
"Error" in Title bar of popup
Java script error in the ma...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#956]
**Description:**
"Error" in Title bar of popup
Java script error in the main process

**Steps to reproduce:**
When I am in the app, in the view with contacts listed on left, dialogue center, contact detail on right, if I RIGHT click on any contact in LEFT column, it produces an error.

**App version:**
version 2.0.1 beta

**OS:**
Win 7 Home Premium

**Works in WhatsApp Web:**

**Extra:**
I had to uninstall, then reinstall the app to restore the menu bar I INADVERTENTLY deslected in the menu, because I could find no option to restore it.

**Comment by dbReed53** [comment]
Did my typeform I submitted have the "messengerError.bmp" file attached?
If not, here it is;

![messengererror](https://cloud.githubusercontent.com/assets/23218250/19948132/17e91722-a119-11e6-961f-766cb1394233.png)
