### ISSUE TITLE
Update situation is a bit confusing

### ISSUE THREAD

**Issue by wisq** [aluxian/Messenger-for-Desktop#961]
* Operating system: OSX 10.11.6
* Messenger for Desktop version: 1.4.3 originally, now 2.0.1-beta

So in 1.4.3, there's a popup saying I should download the latest version (2.0.2).  This didn't do anything for a while, but I eventually decided to try it again, and it took me to a Filehorse link.

I'm assuming the Filehorse link is legit, but I hadn't heard of Filehorse before, and I was being a bit paranoid, so I went back to the official `messengerfordesktop.com` site instad to make sure I was getting a legit copy.  And that's where I realised things are a bit confusing right now:

* the page gives you 1.4.3 (in an unversioned `Messenger.dmg` file)
  * but 1.4.3 suggests you download 2.0.2 when you launch it
* the "download from Github" link takes you to the 2.0.1-beta release, not 2.0.2
* the "download beta releases" link takes you to the 1.5.0-beta.1 release, not 2.0.1-beta

I did eventually go with 2.0.1-beta and I'm fine now, but I just thought it might be worth noting that the current download situation is *very* confusing and could probably use some cleaning up. :)

Thanks for the great app!

**Comment by sheldonhull** [comment]
Please immediately see this. Possible virus/adware/malware. Do not update to 2.0.2 and watch this thread for updates. 

https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/804

**Comment by dansk** [comment]
Any updates about this?  I'm getting it too, have been since I first installed the program.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
