### ISSUE TITLE
The change emoji option doesn't work and in chats that ha...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#984]
**Description:**
The change emoji option doesn't work and in chats that have already been changed I can only use the default thumbs up like

**Operating system:**
OS X, Windows, Linux

**Best thing about Whatsie:**
Ease of use, Design

**Worst thing about Whatsie:**
Cannot hide the right side of the screen would be nice if it had a little arrow to hide and open

**Extra:**
[Not answered]

**Comment by Eddcakes** [comment]
This was just a bug, after ending processes and restarting it worked how it should. Can delete >.>
