### ISSUE TITLE
Window going Black over time

### ISSUE THREAD

**Issue by Saborknight** [aluxian/Messenger-for-Desktop#996]
* Operating system: Windows 10 64bit Latest
* Messenger for Desktop version: 2.0.1-beta
# Description
After a certain amount of time (more than 2 hours, less than a day) the entire window will go black (Screenshot when the next time the problem arises)
Even after refreshing the window and exiting the window (but the process still showing in Taskbar) do not work. I need to actually completely kill the process to be able to see everything again.

Attached is how it just showed up now. Same symptoms, although for some reason only covering the menu right now. It IS possible to click on where the menu items should be, and their options do drop down, but when the whole window is black then of course I cannot identify this interactivity happening.
![A somewhat similar fuck up](https://cloud.githubusercontent.com/assets/9272259/20086391/c189b4a6-a567-11e6-97d1-57c0fd85f918.png)

**Comment by Saborknight** [comment]
## UPDATE
The image of the problem happening in full: 
![When Messenger for Desktop done fucked up](https://cloud.githubusercontent.com/assets/9272259/20139664/1b034b6a-a67f-11e6-8df4-0b060de3d34f.png)

**Comment by Saborknight** [comment]
# UPDATE
I have reason to believe my nVidia graphics card may be the culprit for this, as during an update, when my screen went black for a few seconds whilst the graphics driver was doing stuff to update, after the screen came back, Messenger was black screened again. Also I can see in this image:
![GPU Usage viewer for nvidia](https://cloud.githubusercontent.com/assets/9272259/20228127/ba8c5e6e-a847-11e6-9c58-930517850054.png)

that messenger uses my nvidia GPU. If this is the case, how do I tell Messenger for Desktop to stop using the nvidia graphics card and rather prefer the on board one?

**Comment by Aluxian** [comment]
Telling MFD to use another GPU is like making Chrome/Chromium use another GPU, but I don't know how to do that either — sorry.

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?

**Comment by Saborknight** [comment]
I am on the latest but haven't seen this error re-appear for a long long time. Almost 2 months now? Definitely since new years. So all good and thank you for being attentive!
