### ISSUE TITLE
When there is a new message, the icon should not flash. R...

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#999]
**Description:**
When there is a new message, the icon should not flash. Rather it should be static, but with a red symbol or number on it.

**Operating system:**
Windows

**Best thing about Whatsie:**
Performance, Ease of use

**Worst thing about Whatsie:**
[Not answered]

**Extra:**
[Not answered]

**Comment by Saborknight** [comment]
I personally prefer the flashing. I thought the red icon looked.... meh. I vote to keep the flashing but maybe offer an option under notifications?
